/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DistributionTableIndicatorsFourStar } from './DistributionTableIndicatorsFourStar';
import {
    DistributionTableIndicatorsFourStarFromJSON,
    DistributionTableIndicatorsFourStarFromJSONTyped,
    DistributionTableIndicatorsFourStarToJSON,
    DistributionTableIndicatorsFourStarToJSONTyped,
} from './DistributionTableIndicatorsFourStar';
import type { DistributionTableIndicatorsThreeStar } from './DistributionTableIndicatorsThreeStar';
import {
    DistributionTableIndicatorsThreeStarFromJSON,
    DistributionTableIndicatorsThreeStarFromJSONTyped,
    DistributionTableIndicatorsThreeStarToJSON,
    DistributionTableIndicatorsThreeStarToJSONTyped,
} from './DistributionTableIndicatorsThreeStar';
import type { DistributionTableIndicatorsFeedbackCount } from './DistributionTableIndicatorsFeedbackCount';
import {
    DistributionTableIndicatorsFeedbackCountFromJSON,
    DistributionTableIndicatorsFeedbackCountFromJSONTyped,
    DistributionTableIndicatorsFeedbackCountToJSON,
    DistributionTableIndicatorsFeedbackCountToJSONTyped,
} from './DistributionTableIndicatorsFeedbackCount';
import type { TableItemBaseCommonFeedbackRating } from './TableItemBaseCommonFeedbackRating';
import {
    TableItemBaseCommonFeedbackRatingFromJSON,
    TableItemBaseCommonFeedbackRatingFromJSONTyped,
    TableItemBaseCommonFeedbackRatingToJSON,
    TableItemBaseCommonFeedbackRatingToJSONTyped,
} from './TableItemBaseCommonFeedbackRating';
import type { DistributionTableIndicatorsTwoStar } from './DistributionTableIndicatorsTwoStar';
import {
    DistributionTableIndicatorsTwoStarFromJSON,
    DistributionTableIndicatorsTwoStarFromJSONTyped,
    DistributionTableIndicatorsTwoStarToJSON,
    DistributionTableIndicatorsTwoStarToJSONTyped,
} from './DistributionTableIndicatorsTwoStar';
import type { DistributionTableIndicatorsFiveStar } from './DistributionTableIndicatorsFiveStar';
import {
    DistributionTableIndicatorsFiveStarFromJSON,
    DistributionTableIndicatorsFiveStarFromJSONTyped,
    DistributionTableIndicatorsFiveStarToJSON,
    DistributionTableIndicatorsFiveStarToJSONTyped,
} from './DistributionTableIndicatorsFiveStar';
import type { DistributionTableIndicatorsOneStar } from './DistributionTableIndicatorsOneStar';
import {
    DistributionTableIndicatorsOneStarFromJSON,
    DistributionTableIndicatorsOneStarFromJSONTyped,
    DistributionTableIndicatorsOneStarToJSON,
    DistributionTableIndicatorsOneStarToJSONTyped,
} from './DistributionTableIndicatorsOneStar';

/**
 * 
 * @export
 * @interface DistributionTableItem
 */
export interface DistributionTableItem {
    /**
     * Артикул WB
     * @type {number}
     * @memberof DistributionTableItem
     */
    nmId?: number;
    /**
     * Название товара
     * @type {string}
     * @memberof DistributionTableItem
     */
    title?: string;
    /**
     * Артикул продавца
     * @type {string}
     * @memberof DistributionTableItem
     */
    vendorCode?: string;
    /**
     * ID предмета
     * @type {number}
     * @memberof DistributionTableItem
     */
    subjectId?: number;
    /**
     * Название предмета
     * @type {string}
     * @memberof DistributionTableItem
     */
    subjectName?: string;
    /**
     * Бренд
     * @type {string}
     * @memberof DistributionTableItem
     */
    brandName?: string;
    /**
     * Название ярлыка
     * @type {string}
     * @memberof DistributionTableItem
     */
    tagName?: string;
    /**
     * ID ярлыка
     * @type {number}
     * @memberof DistributionTableItem
     */
    tagId?: number;
    /**
     * Отзыв закреплён
     * @type {boolean}
     * @memberof DistributionTableItem
     */
    pinnedFeedback?: boolean;
    /**
     * Рейтинг карточки товара
     * @type {number}
     * @memberof DistributionTableItem
     */
    rating?: number;
    /**
     * 
     * @type {TableItemBaseCommonFeedbackRating}
     * @memberof DistributionTableItem
     */
    feedbackRating?: TableItemBaseCommonFeedbackRating;
    /**
     * 
     * @type {DistributionTableIndicatorsFeedbackCount}
     * @memberof DistributionTableItem
     */
    feedbackCount?: DistributionTableIndicatorsFeedbackCount;
    /**
     * 
     * @type {DistributionTableIndicatorsFiveStar}
     * @memberof DistributionTableItem
     */
    fiveStar?: DistributionTableIndicatorsFiveStar;
    /**
     * 
     * @type {DistributionTableIndicatorsFourStar}
     * @memberof DistributionTableItem
     */
    fourStar?: DistributionTableIndicatorsFourStar;
    /**
     * 
     * @type {DistributionTableIndicatorsThreeStar}
     * @memberof DistributionTableItem
     */
    threeStar?: DistributionTableIndicatorsThreeStar;
    /**
     * 
     * @type {DistributionTableIndicatorsTwoStar}
     * @memberof DistributionTableItem
     */
    twoStar?: DistributionTableIndicatorsTwoStar;
    /**
     * 
     * @type {DistributionTableIndicatorsOneStar}
     * @memberof DistributionTableItem
     */
    oneStar?: DistributionTableIndicatorsOneStar;
    /**
     * Отзывы, исключённые из рейтинга
     * @type {number}
     * @memberof DistributionTableItem
     */
    disqualified?: number;
}

/**
 * Check if a given object implements the DistributionTableItem interface.
 */
export function instanceOfDistributionTableItem(value: object): value is DistributionTableItem {
    return true;
}

export function DistributionTableItemFromJSON(json: any): DistributionTableItem {
    return DistributionTableItemFromJSONTyped(json, false);
}

export function DistributionTableItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistributionTableItem {
    if (json == null) {
        return json;
    }
    return {
        
        'nmId': json['nmId'] == null ? undefined : json['nmId'],
        'title': json['title'] == null ? undefined : json['title'],
        'vendorCode': json['vendorCode'] == null ? undefined : json['vendorCode'],
        'subjectId': json['subjectId'] == null ? undefined : json['subjectId'],
        'subjectName': json['subjectName'] == null ? undefined : json['subjectName'],
        'brandName': json['brandName'] == null ? undefined : json['brandName'],
        'tagName': json['tagName'] == null ? undefined : json['tagName'],
        'tagId': json['tagId'] == null ? undefined : json['tagId'],
        'pinnedFeedback': json['pinnedFeedback'] == null ? undefined : json['pinnedFeedback'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'feedbackRating': json['feedbackRating'] == null ? undefined : TableItemBaseCommonFeedbackRatingFromJSON(json['feedbackRating']),
        'feedbackCount': json['feedbackCount'] == null ? undefined : DistributionTableIndicatorsFeedbackCountFromJSON(json['feedbackCount']),
        'fiveStar': json['fiveStar'] == null ? undefined : DistributionTableIndicatorsFiveStarFromJSON(json['fiveStar']),
        'fourStar': json['fourStar'] == null ? undefined : DistributionTableIndicatorsFourStarFromJSON(json['fourStar']),
        'threeStar': json['threeStar'] == null ? undefined : DistributionTableIndicatorsThreeStarFromJSON(json['threeStar']),
        'twoStar': json['twoStar'] == null ? undefined : DistributionTableIndicatorsTwoStarFromJSON(json['twoStar']),
        'oneStar': json['oneStar'] == null ? undefined : DistributionTableIndicatorsOneStarFromJSON(json['oneStar']),
        'disqualified': json['disqualified'] == null ? undefined : json['disqualified'],
    };
}

export function DistributionTableItemToJSON(json: any): DistributionTableItem {
    return DistributionTableItemToJSONTyped(json, false);
}

export function DistributionTableItemToJSONTyped(value?: DistributionTableItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nmId': value['nmId'],
        'title': value['title'],
        'vendorCode': value['vendorCode'],
        'subjectId': value['subjectId'],
        'subjectName': value['subjectName'],
        'brandName': value['brandName'],
        'tagName': value['tagName'],
        'tagId': value['tagId'],
        'pinnedFeedback': value['pinnedFeedback'],
        'rating': value['rating'],
        'feedbackRating': TableItemBaseCommonFeedbackRatingToJSON(value['feedbackRating']),
        'feedbackCount': DistributionTableIndicatorsFeedbackCountToJSON(value['feedbackCount']),
        'fiveStar': DistributionTableIndicatorsFiveStarToJSON(value['fiveStar']),
        'fourStar': DistributionTableIndicatorsFourStarToJSON(value['fourStar']),
        'threeStar': DistributionTableIndicatorsThreeStarToJSON(value['threeStar']),
        'twoStar': DistributionTableIndicatorsTwoStarToJSON(value['twoStar']),
        'oneStar': DistributionTableIndicatorsOneStarToJSON(value['oneStar']),
        'disqualified': value['disqualified'],
    };
}

