/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/salesFunnel)   2. [Ленты заказов](/openapi/analytics#tag/orderFeed)   3. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/searchQueriesForYourItems)   4. [Истории остатков](/openapi/analytics#tag/stocksReport)   5. [Оценки товара](/openapi/analytics#tag/itemRating)   6. [Аналитики продавца в формате CSV](/openapi/analytics#tag/sellerAnalyticsCsv)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Все отзывы за период
 * @export
 * @interface DistributionTableItemV1FeedbackCount
 */
export interface DistributionTableItemV1FeedbackCount {
    /**
     * Прирост оценок за период
     */
    current: number;
    /**
     * Динамика по сравнению с предыдущим периодом, %
     */
    dynamics?: number;
}

/**
 * Check if a given object implements the DistributionTableItemV1FeedbackCount interface.
 */
export function instanceOfDistributionTableItemV1FeedbackCount(value: object): value is DistributionTableItemV1FeedbackCount {
    if (!('current' in value) || value['current'] === undefined) return false;
    return true;
}

export function DistributionTableItemV1FeedbackCountFromJSON(json: any): DistributionTableItemV1FeedbackCount {
    return DistributionTableItemV1FeedbackCountFromJSONTyped(json, false);
}

export function DistributionTableItemV1FeedbackCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistributionTableItemV1FeedbackCount {
    if (json == null) {
        return json;
    }
    return {
        
        'current': json['current'],
        'dynamics': json['dynamics'] == null ? undefined : json['dynamics'],
    };
}

export function DistributionTableItemV1FeedbackCountToJSON(json: any): DistributionTableItemV1FeedbackCount {
    return DistributionTableItemV1FeedbackCountToJSONTyped(json, false);
}

export function DistributionTableItemV1FeedbackCountToJSONTyped(value?: DistributionTableItemV1FeedbackCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current': value['current'],
        'dynamics': value['dynamics'],
    };
}

