/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/salesFunnel)   2. [Ленты заказов](/openapi/analytics#tag/orderFeed)   3. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/searchQueriesForYourItems)   4. [Истории остатков](/openapi/analytics#tag/stocksReport)   5. [Оценки товара](/openapi/analytics#tag/itemRating)   6. [Аналитики продавца в формате CSV](/openapi/analytics#tag/sellerAnalyticsCsv)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DistributionTableItemFiveStar } from './DistributionTableItemFiveStar';
import {
    DistributionTableItemFiveStarFromJSON,
    DistributionTableItemFiveStarFromJSONTyped,
    DistributionTableItemFiveStarToJSON,
    DistributionTableItemFiveStarToJSONTyped,
} from './DistributionTableItemFiveStar';
import type { DistributionTableItemTwoStar } from './DistributionTableItemTwoStar';
import {
    DistributionTableItemTwoStarFromJSON,
    DistributionTableItemTwoStarFromJSONTyped,
    DistributionTableItemTwoStarToJSON,
    DistributionTableItemTwoStarToJSONTyped,
} from './DistributionTableItemTwoStar';
import type { DistributionTableItemOneStar } from './DistributionTableItemOneStar';
import {
    DistributionTableItemOneStarFromJSON,
    DistributionTableItemOneStarFromJSONTyped,
    DistributionTableItemOneStarToJSON,
    DistributionTableItemOneStarToJSONTyped,
} from './DistributionTableItemOneStar';
import type { DistributionTableItemFeedbackRating } from './DistributionTableItemFeedbackRating';
import {
    DistributionTableItemFeedbackRatingFromJSON,
    DistributionTableItemFeedbackRatingFromJSONTyped,
    DistributionTableItemFeedbackRatingToJSON,
    DistributionTableItemFeedbackRatingToJSONTyped,
} from './DistributionTableItemFeedbackRating';
import type { DistributionTableItemFourStar } from './DistributionTableItemFourStar';
import {
    DistributionTableItemFourStarFromJSON,
    DistributionTableItemFourStarFromJSONTyped,
    DistributionTableItemFourStarToJSON,
    DistributionTableItemFourStarToJSONTyped,
} from './DistributionTableItemFourStar';
import type { DistributionTableItemThreeStar } from './DistributionTableItemThreeStar';
import {
    DistributionTableItemThreeStarFromJSON,
    DistributionTableItemThreeStarFromJSONTyped,
    DistributionTableItemThreeStarToJSON,
    DistributionTableItemThreeStarToJSONTyped,
} from './DistributionTableItemThreeStar';
import type { DistributionTableItemFeedbackCount } from './DistributionTableItemFeedbackCount';
import {
    DistributionTableItemFeedbackCountFromJSON,
    DistributionTableItemFeedbackCountFromJSONTyped,
    DistributionTableItemFeedbackCountToJSON,
    DistributionTableItemFeedbackCountToJSONTyped,
} from './DistributionTableItemFeedbackCount';

/**
 * 
 * @export
 * @interface DistributionTableItem
 */
export interface DistributionTableItem {
    /**
     * Артикул WB
     */
    nmId: number;
    /**
     * Название товара
     */
    title: string;
    /**
     * Артикул продавца
     */
    vendorCode: string;
    /**
     * ID предмета
     */
    subjectId: number;
    /**
     * Название предмета
     */
    subjectName: string;
    /**
     * Бренд
     */
    brandName: string;
    /**
     * Название ярлыка
     */
    tagName: string;
    /**
     * ID ярлыка
     */
    tagId: number;
    /**
     * Отзыв закреплён
     */
    pinnedFeedback: boolean;
    /**
     * Рейтинг карточки товара
     */
    rating: number;
    /**
     * 
     */
    feedbackRating: DistributionTableItemFeedbackRating;
    /**
     * 
     */
    feedbackCount: DistributionTableItemFeedbackCount;
    /**
     * 
     */
    fiveStar: DistributionTableItemFiveStar;
    /**
     * 
     */
    fourStar: DistributionTableItemFourStar;
    /**
     * 
     */
    threeStar: DistributionTableItemThreeStar;
    /**
     * 
     */
    twoStar: DistributionTableItemTwoStar;
    /**
     * 
     */
    oneStar: DistributionTableItemOneStar;
    /**
     * Отзывы, исключённые из рейтинга
     */
    disqualified: number;
    /**
     * Является ли товар скрытым из каталога:
     *   - `true` — товар скрыт из каталога
     *   - `false` — товар не скрыт из каталога
     * 
     */
    isShadowed: boolean;
}

/**
 * Check if a given object implements the DistributionTableItem interface.
 */
export function instanceOfDistributionTableItem(value: object): value is DistributionTableItem {
    if (!('nmId' in value) || value['nmId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('vendorCode' in value) || value['vendorCode'] === undefined) return false;
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    if (!('subjectName' in value) || value['subjectName'] === undefined) return false;
    if (!('brandName' in value) || value['brandName'] === undefined) return false;
    if (!('tagName' in value) || value['tagName'] === undefined) return false;
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    if (!('pinnedFeedback' in value) || value['pinnedFeedback'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('feedbackRating' in value) || value['feedbackRating'] === undefined) return false;
    if (!('feedbackCount' in value) || value['feedbackCount'] === undefined) return false;
    if (!('fiveStar' in value) || value['fiveStar'] === undefined) return false;
    if (!('fourStar' in value) || value['fourStar'] === undefined) return false;
    if (!('threeStar' in value) || value['threeStar'] === undefined) return false;
    if (!('twoStar' in value) || value['twoStar'] === undefined) return false;
    if (!('oneStar' in value) || value['oneStar'] === undefined) return false;
    if (!('disqualified' in value) || value['disqualified'] === undefined) return false;
    if (!('isShadowed' in value) || value['isShadowed'] === undefined) return false;
    return true;
}

export function DistributionTableItemFromJSON(json: any): DistributionTableItem {
    return DistributionTableItemFromJSONTyped(json, false);
}

export function DistributionTableItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistributionTableItem {
    if (json == null) {
        return json;
    }
    return {
        
        'nmId': json['nmId'],
        'title': json['title'],
        'vendorCode': json['vendorCode'],
        'subjectId': json['subjectId'],
        'subjectName': json['subjectName'],
        'brandName': json['brandName'],
        'tagName': json['tagName'],
        'tagId': json['tagId'],
        'pinnedFeedback': json['pinnedFeedback'],
        'rating': json['rating'],
        'feedbackRating': DistributionTableItemFeedbackRatingFromJSON(json['feedbackRating']),
        'feedbackCount': DistributionTableItemFeedbackCountFromJSON(json['feedbackCount']),
        'fiveStar': DistributionTableItemFiveStarFromJSON(json['fiveStar']),
        'fourStar': DistributionTableItemFourStarFromJSON(json['fourStar']),
        'threeStar': DistributionTableItemThreeStarFromJSON(json['threeStar']),
        'twoStar': DistributionTableItemTwoStarFromJSON(json['twoStar']),
        'oneStar': DistributionTableItemOneStarFromJSON(json['oneStar']),
        'disqualified': json['disqualified'],
        'isShadowed': json['isShadowed'],
    };
}

export function DistributionTableItemToJSON(json: any): DistributionTableItem {
    return DistributionTableItemToJSONTyped(json, false);
}

export function DistributionTableItemToJSONTyped(value?: DistributionTableItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nmId': value['nmId'],
        'title': value['title'],
        'vendorCode': value['vendorCode'],
        'subjectId': value['subjectId'],
        'subjectName': value['subjectName'],
        'brandName': value['brandName'],
        'tagName': value['tagName'],
        'tagId': value['tagId'],
        'pinnedFeedback': value['pinnedFeedback'],
        'rating': value['rating'],
        'feedbackRating': DistributionTableItemFeedbackRatingToJSON(value['feedbackRating']),
        'feedbackCount': DistributionTableItemFeedbackCountToJSON(value['feedbackCount']),
        'fiveStar': DistributionTableItemFiveStarToJSON(value['fiveStar']),
        'fourStar': DistributionTableItemFourStarToJSON(value['fourStar']),
        'threeStar': DistributionTableItemThreeStarToJSON(value['threeStar']),
        'twoStar': DistributionTableItemTwoStarToJSON(value['twoStar']),
        'oneStar': DistributionTableItemOneStarToJSON(value['oneStar']),
        'disqualified': value['disqualified'],
        'isShadowed': value['isShadowed'],
    };
}

