/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/salesFunnel)   2. [Ленты заказов](/openapi/analytics#tag/orderFeed)   3. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/searchQueriesForYourItems)   4. [Истории остатков](/openapi/analytics#tag/stocksReport)   5. [Оценки товара](/openapi/analytics#tag/itemRating)   6. [Аналитики продавца в формате CSV](/openapi/analytics#tag/sellerAnalyticsCsv)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetV2NmReportDownloads403Response
 */
export interface GetV2NmReportDownloads403Response {
    /**
     * Заголовок ошибки
     */
    title?: string;
    /**
     * Детали ошибки
     */
    detail?: string;
    /**
     * Уникальный ID запроса
     */
    requestId?: string;
    /**
     * ID внутреннего сервиса WB
     */
    origin?: string;
}

/**
 * Check if a given object implements the GetV2NmReportDownloads403Response interface.
 */
export function instanceOfGetV2NmReportDownloads403Response(value: object): value is GetV2NmReportDownloads403Response {
    return true;
}

export function GetV2NmReportDownloads403ResponseFromJSON(json: any): GetV2NmReportDownloads403Response {
    return GetV2NmReportDownloads403ResponseFromJSONTyped(json, false);
}

export function GetV2NmReportDownloads403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetV2NmReportDownloads403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'origin': json['origin'] == null ? undefined : json['origin'],
    };
}

export function GetV2NmReportDownloads403ResponseToJSON(json: any): GetV2NmReportDownloads403Response {
    return GetV2NmReportDownloads403ResponseToJSONTyped(json, false);
}

export function GetV2NmReportDownloads403ResponseToJSONTyped(value?: GetV2NmReportDownloads403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'detail': value['detail'],
        'requestId': value['requestId'],
        'origin': value['origin'],
    };
}

