/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemHistoryResponseInnerProduct
 */
export interface ItemHistoryResponseInnerProduct {
    /**
     * Артикул WB
     * @type {number}
     * @memberof ItemHistoryResponseInnerProduct
     */
    nmId: number;
    /**
     * Название карточки товара
     * @type {string}
     * @memberof ItemHistoryResponseInnerProduct
     */
    title: string;
    /**
     * Артикул продавца
     * @type {string}
     * @memberof ItemHistoryResponseInnerProduct
     */
    vendorCode: string;
    /**
     * Бренд
     * @type {string}
     * @memberof ItemHistoryResponseInnerProduct
     */
    brandName: string;
    /**
     * ID предмета
     * @type {number}
     * @memberof ItemHistoryResponseInnerProduct
     */
    subjectId: number;
    /**
     * Название предмета
     * @type {string}
     * @memberof ItemHistoryResponseInnerProduct
     */
    subjectName: string;
}

/**
 * Check if a given object implements the ItemHistoryResponseInnerProduct interface.
 */
export function instanceOfItemHistoryResponseInnerProduct(value: object): value is ItemHistoryResponseInnerProduct {
    if (!('nmId' in value) || value['nmId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('vendorCode' in value) || value['vendorCode'] === undefined) return false;
    if (!('brandName' in value) || value['brandName'] === undefined) return false;
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    if (!('subjectName' in value) || value['subjectName'] === undefined) return false;
    return true;
}

export function ItemHistoryResponseInnerProductFromJSON(json: any): ItemHistoryResponseInnerProduct {
    return ItemHistoryResponseInnerProductFromJSONTyped(json, false);
}

export function ItemHistoryResponseInnerProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemHistoryResponseInnerProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'nmId': json['nmId'],
        'title': json['title'],
        'vendorCode': json['vendorCode'],
        'brandName': json['brandName'],
        'subjectId': json['subjectId'],
        'subjectName': json['subjectName'],
    };
}

export function ItemHistoryResponseInnerProductToJSON(json: any): ItemHistoryResponseInnerProduct {
    return ItemHistoryResponseInnerProductToJSONTyped(json, false);
}

export function ItemHistoryResponseInnerProductToJSONTyped(value?: ItemHistoryResponseInnerProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nmId': value['nmId'],
        'title': value['title'],
        'vendorCode': value['vendorCode'],
        'brandName': value['brandName'],
        'subjectId': value['subjectId'],
        'subjectName': value['subjectName'],
    };
}

