/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchReportPositionChartItem
 */
export interface SearchReportPositionChartItem {
    /**
     * Дата
     */
    dt: string;
    /**
     * Средняя позиция товара в результатах поиска
     */
    average: number;
    /**
     * Медианная позиция товара в результатах поиска
     */
    median: number;
}

/**
 * Check if a given object implements the SearchReportPositionChartItem interface.
 */
export function instanceOfSearchReportPositionChartItem(value: object): value is SearchReportPositionChartItem {
    if (!('dt' in value) || value['dt'] === undefined) return false;
    if (!('average' in value) || value['average'] === undefined) return false;
    if (!('median' in value) || value['median'] === undefined) return false;
    return true;
}

export function SearchReportPositionChartItemFromJSON(json: any): SearchReportPositionChartItem {
    return SearchReportPositionChartItemFromJSONTyped(json, false);
}

export function SearchReportPositionChartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchReportPositionChartItem {
    if (json == null) {
        return json;
    }
    return {
        
        'dt': json['dt'],
        'average': json['average'],
        'median': json['median'],
    };
}

export function SearchReportPositionChartItemToJSON(json: any): SearchReportPositionChartItem {
    return SearchReportPositionChartItemToJSONTyped(json, false);
}

export function SearchReportPositionChartItemToJSONTyped(value?: SearchReportPositionChartItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dt': value['dt'],
        'average': value['average'],
        'median': value['median'],
    };
}

