/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/salesFunnel)   2. [Ленты заказов](/openapi/analytics#tag/orderFeed)   3. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/searchQueriesForYourItems)   4. [Истории остатков](/openapi/analytics#tag/stocksReport)   5. [Оценки товара](/openapi/analytics#tag/itemRating)   6. [Аналитики продавца в формате CSV](/openapi/analytics#tag/sellerAnalyticsCsv)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PastPeriod } from './PastPeriod';
import {
    PastPeriodFromJSON,
    PastPeriodFromJSONTyped,
    PastPeriodToJSON,
    PastPeriodToJSONTyped,
} from './PastPeriod';
import type { PositionCluster } from './PositionCluster';
import {
    PositionClusterFromJSON,
    PositionClusterFromJSONTyped,
    PositionClusterToJSON,
    PositionClusterToJSONTyped,
} from './PositionCluster';
import type { Period } from './Period';
import {
    PeriodFromJSON,
    PeriodFromJSONTyped,
    PeriodToJSON,
    PeriodToJSONTyped,
} from './Period';
import type { OrderByGrTe } from './OrderByGrTe';
import {
    OrderByGrTeFromJSON,
    OrderByGrTeFromJSONTyped,
    OrderByGrTeToJSON,
    OrderByGrTeToJSONTyped,
} from './OrderByGrTe';

/**
 * Параметры запроса для пагинации по группам:
 *   - `currentPeriod` — текущий период
 *   - `pastPeriod` — предыдущий период для сравнения
 * 
 * @export
 * @interface TableGroupRequest
 */
export interface TableGroupRequest {
    /**
     * 
     */
    currentPeriod: Period;
    /**
     * 
     */
    pastPeriod?: PastPeriod;
    /**
     * Список артикулов WB для фильтрации
     */
    nmIds?: Array<number>;
    /**
     * Список ID предметов для фильтрации
     */
    subjectIds?: Array<number>;
    /**
     * Список брендов для фильтрации
     */
    brandNames?: Array<string>;
    /**
     * Список ID ярлыков для фильтрации
     */
    tagIds?: Array<number>;
    /**
     * 
     */
    orderBy: OrderByGrTe;
    /**
     * 
     */
    positionCluster: PositionCluster;
    /**
     * Показать данные по прямым запросам с [подменным артикулом](https://seller.wildberries.ru/help-center/article/A-524)
     */
    includeSubstitutedSKUs?: boolean;
    /**
     * Показать данные по поисковым запросам без учёта подменного артикула
     */
    includeSearchTexts?: boolean;
    /**
     * Количество групп товаров в ответе
     */
    limit: number;
    /**
     * После какого элемента выдавать данные
     */
    offset: number;
}



/**
 * Check if a given object implements the TableGroupRequest interface.
 */
export function instanceOfTableGroupRequest(value: object): value is TableGroupRequest {
    if (!('currentPeriod' in value) || value['currentPeriod'] === undefined) return false;
    if (!('orderBy' in value) || value['orderBy'] === undefined) return false;
    if (!('positionCluster' in value) || value['positionCluster'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function TableGroupRequestFromJSON(json: any): TableGroupRequest {
    return TableGroupRequestFromJSONTyped(json, false);
}

export function TableGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPeriod': PeriodFromJSON(json['currentPeriod']),
        'pastPeriod': json['pastPeriod'] == null ? undefined : PastPeriodFromJSON(json['pastPeriod']),
        'nmIds': json['nmIds'] == null ? undefined : json['nmIds'],
        'subjectIds': json['subjectIds'] == null ? undefined : json['subjectIds'],
        'brandNames': json['brandNames'] == null ? undefined : json['brandNames'],
        'tagIds': json['tagIds'] == null ? undefined : json['tagIds'],
        'orderBy': OrderByGrTeFromJSON(json['orderBy']),
        'positionCluster': PositionClusterFromJSON(json['positionCluster']),
        'includeSubstitutedSKUs': json['includeSubstitutedSKUs'] == null ? undefined : json['includeSubstitutedSKUs'],
        'includeSearchTexts': json['includeSearchTexts'] == null ? undefined : json['includeSearchTexts'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function TableGroupRequestToJSON(json: any): TableGroupRequest {
    return TableGroupRequestToJSONTyped(json, false);
}

export function TableGroupRequestToJSONTyped(value?: TableGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPeriod': PeriodToJSON(value['currentPeriod']),
        'pastPeriod': PastPeriodToJSON(value['pastPeriod']),
        'nmIds': value['nmIds'],
        'subjectIds': value['subjectIds'],
        'brandNames': value['brandNames'],
        'tagIds': value['tagIds'],
        'orderBy': OrderByGrTeToJSON(value['orderBy']),
        'positionCluster': PositionClusterToJSON(value['positionCluster']),
        'includeSubstitutedSKUs': value['includeSubstitutedSKUs'],
        'includeSearchTexts': value['includeSearchTexts'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

