/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Цена
 * @export
 * @interface TableItemItemAllOfPrice
 */
export interface TableItemItemAllOfPrice {
    /**
     * Минимальная цена продавца со скидкой продавца (без учёта скидки WB Клуба)
     */
    minPrice: number;
    /**
     * Максимальная цена продавца со скидкой продавца (без учёта скидки WB Клуба)
     */
    maxPrice: number;
}

/**
 * Check if a given object implements the TableItemItemAllOfPrice interface.
 */
export function instanceOfTableItemItemAllOfPrice(value: object): value is TableItemItemAllOfPrice {
    if (!('minPrice' in value) || value['minPrice'] === undefined) return false;
    if (!('maxPrice' in value) || value['maxPrice'] === undefined) return false;
    return true;
}

export function TableItemItemAllOfPriceFromJSON(json: any): TableItemItemAllOfPrice {
    return TableItemItemAllOfPriceFromJSONTyped(json, false);
}

export function TableItemItemAllOfPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableItemItemAllOfPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'minPrice': json['minPrice'],
        'maxPrice': json['maxPrice'],
    };
}

export function TableItemItemAllOfPriceToJSON(json: any): TableItemItemAllOfPrice {
    return TableItemItemAllOfPriceToJSONTyped(json, false);
}

export function TableItemItemAllOfPriceToJSONTyped(value?: TableItemItemAllOfPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'minPrice': value['minPrice'],
        'maxPrice': value['maxPrice'],
    };
}

