/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/salesFunnel)   2. [Ленты заказов](/openapi/analytics#tag/orderFeed)   3. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/searchQueriesForYourItems)   4. [Истории остатков](/openapi/analytics#tag/stocksReport)   5. [Оценки товара](/openapi/analytics#tag/itemRating)   6. [Аналитики продавца в формате CSV](/openapi/analytics#tag/sellerAnalyticsCsv)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Рейтинг продавца
 * @export
 * @interface TableItemFloat
 */
export interface TableItemFloat {
    /**
     * Текущий рейтинг
     */
    current: number;
    /**
     * Динамика по сравнению с предыдущим периодом, %
     */
    dynamics?: number;
}

/**
 * Check if a given object implements the TableItemFloat interface.
 */
export function instanceOfTableItemFloat(value: object): value is TableItemFloat {
    if (!('current' in value) || value['current'] === undefined) return false;
    return true;
}

export function TableItemFloatFromJSON(json: any): TableItemFloat {
    return TableItemFloatFromJSONTyped(json, false);
}

export function TableItemFloatFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableItemFloat {
    if (json == null) {
        return json;
    }
    return {
        
        'current': json['current'],
        'dynamics': json['dynamics'] == null ? undefined : json['dynamics'],
    };
}

export function TableItemFloatToJSON(json: any): TableItemFloat {
    return TableItemFloatToJSONTyped(json, false);
}

export function TableItemFloatToJSONTyped(value?: TableItemFloat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current': value['current'],
        'dynamics': value['dynamics'],
    };
}

