/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * <div class=\"api-block\">  С помощью методов этого раздела вы можете:   - [создавать](/openapi/work-with-products#tag/listingItems) и [редактировать](/openapi/work-with-products#tag/listings) карточки товаров   - получать [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/categoriesSubcategoriesAndCharacteristics)   - загружать [медиафайлы](/openapi/work-with-products#tag/mediaFiles) в карточки товаров   - настраивать [ярлыки](/openapi/work-with-products#tag/labels) для поиска товаров   - работать с [рекомендациями](/openapi/work-with-products#tag/recommendations) для товаров   - устанавливать [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца  Вы можете протестировать методы работы с товарами в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Rabota-s-tovarami) для управления карточками товаров  </div>  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami\">инструкции</a> по <strong>работе с товарами</strong> </div> 
 *
 * The version of the OpenAPI document: items
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRecomResDataInner
 */
export interface GetRecomResDataInner {
    /**
     * Артикул WB
     * @type {number}
     * @memberof GetRecomResDataInner
     */
    nmId: number;
    /**
     * ID для [объединённых](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami#obuedinenie-i-razuedinenie-kartochek-tovarov) карточек товаров
     * @type {number}
     * @memberof GetRecomResDataInner
     */
    imtId: number;
    /**
     * Артикул продавца
     * @type {string}
     * @memberof GetRecomResDataInner
     */
    vendorCode: string;
    /**
     * Бренд
     * @type {string}
     * @memberof GetRecomResDataInner
     */
    brandName: string;
    /**
     * Дата и время последнего обновления рекомендаций
     * @type {Date}
     * @memberof GetRecomResDataInner
     */
    updatedAt?: Date | null;
    /**
     * Количество изображений в карточке товара
     * @type {number}
     * @memberof GetRecomResDataInner
     */
    picsCount: number;
    /**
     * Название товара
     * @type {string}
     * @memberof GetRecomResDataInner
     */
    title: string;
    /**
     * Предмет
     * @type {string}
     * @memberof GetRecomResDataInner
     */
    subjectName: string;
    /**
     * URL основного изображения в карточке товара
     * @type {string}
     * @memberof GetRecomResDataInner
     */
    pic: string;
    /**
     * Количество рекомендуемых товаров
     * @type {number}
     * @memberof GetRecomResDataInner
     */
    recomCount: number;
    /**
     * Список URL основных изображений рекомендуемых товаров
     * @type {Array<string>}
     * @memberof GetRecomResDataInner
     */
    recomPics: Array<string>;
    /**
     * Список `nmId` рекомендуемых товаров
     * @type {Array<number>}
     * @memberof GetRecomResDataInner
     */
    recomNms: Array<number>;
}

/**
 * Check if a given object implements the GetRecomResDataInner interface.
 */
export function instanceOfGetRecomResDataInner(value: object): value is GetRecomResDataInner {
    if (!('nmId' in value) || value['nmId'] === undefined) return false;
    if (!('imtId' in value) || value['imtId'] === undefined) return false;
    if (!('vendorCode' in value) || value['vendorCode'] === undefined) return false;
    if (!('brandName' in value) || value['brandName'] === undefined) return false;
    if (!('picsCount' in value) || value['picsCount'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('subjectName' in value) || value['subjectName'] === undefined) return false;
    if (!('pic' in value) || value['pic'] === undefined) return false;
    if (!('recomCount' in value) || value['recomCount'] === undefined) return false;
    if (!('recomPics' in value) || value['recomPics'] === undefined) return false;
    if (!('recomNms' in value) || value['recomNms'] === undefined) return false;
    return true;
}

export function GetRecomResDataInnerFromJSON(json: any): GetRecomResDataInner {
    return GetRecomResDataInnerFromJSONTyped(json, false);
}

export function GetRecomResDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRecomResDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'nmId': json['nmId'],
        'imtId': json['imtId'],
        'vendorCode': json['vendorCode'],
        'brandName': json['brandName'],
        'updatedAt': json['updatedAt'] === undefined ? undefined : json['updatedAt'] === null ? null : (new Date(json['updatedAt'])),
        'picsCount': json['picsCount'],
        'title': json['title'],
        'subjectName': json['subjectName'],
        'pic': json['pic'],
        'recomCount': json['recomCount'],
        'recomPics': json['recomPics'],
        'recomNms': json['recomNms'],
    };
}

export function GetRecomResDataInnerToJSON(json: any): GetRecomResDataInner {
    return GetRecomResDataInnerToJSONTyped(json, false);
}

export function GetRecomResDataInnerToJSONTyped(value?: GetRecomResDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nmId': value['nmId'],
        'imtId': value['imtId'],
        'vendorCode': value['vendorCode'],
        'brandName': value['brandName'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'picsCount': value['picsCount'],
        'title': value['title'],
        'subjectName': value['subjectName'],
        'pic': value['pic'],
        'recomCount': value['recomCount'],
        'recomPics': value['recomPics'],
        'recomNms': value['recomNms'],
    };
}

