/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * <div class=\"api-block\">  С помощью методов этого раздела вы можете:   - [создавать](/openapi/work-with-products#tag/listingItems) и [редактировать](/openapi/work-with-products#tag/listings) карточки товаров   - получать [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/categoriesSubcategoriesAndCharacteristics)   - загружать [медиафайлы](/openapi/work-with-products#tag/mediaFiles) в карточки товаров   - настраивать [ярлыки](/openapi/work-with-products#tag/labels) для поиска товаров   - работать с [рекомендациями](/openapi/work-with-products#tag/recommendations) для товаров   - устанавливать [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца  Вы можете протестировать методы работы с товарами в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Rabota-s-tovarami) для управления карточками товаров  </div>   <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami\">инструкции</a> по <strong>работе с товарами</strong> </div>  
 *
 * The version of the OpenAPI document: items
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestMoveNmsImtConn
 */
export interface RequestMoveNmsImtConn {
    /**
     * Существующий `imtID`, под которым необходимо [объединить](/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami#obuedinenie-i-razuedinenie-kartochek-tovarov) карточки товаров
     */
    targetIMT: number;
    /**
     * `nmID`, которые необходимо объединить
     * 
     */
    nmIDs: Array<number>;
}

/**
 * Check if a given object implements the RequestMoveNmsImtConn interface.
 */
export function instanceOfRequestMoveNmsImtConn(value: object): value is RequestMoveNmsImtConn {
    if (!('targetIMT' in value) || value['targetIMT'] === undefined) return false;
    if (!('nmIDs' in value) || value['nmIDs'] === undefined) return false;
    return true;
}

export function RequestMoveNmsImtConnFromJSON(json: any): RequestMoveNmsImtConn {
    return RequestMoveNmsImtConnFromJSONTyped(json, false);
}

export function RequestMoveNmsImtConnFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestMoveNmsImtConn {
    if (json == null) {
        return json;
    }
    return {
        
        'targetIMT': json['targetIMT'],
        'nmIDs': json['nmIDs'],
    };
}

export function RequestMoveNmsImtConnToJSON(json: any): RequestMoveNmsImtConn {
    return RequestMoveNmsImtConnToJSONTyped(json, false);
}

export function RequestMoveNmsImtConnToJSONTyped(value?: RequestMoveNmsImtConn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetIMT': value['targetIMT'],
        'nmIDs': value['nmIDs'],
    };
}

