/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * <div class=\"api-block\">  С помощью методов этого раздела вы можете:   - [создавать](/openapi/item-management#tag/listingItems) и [редактировать](/openapi/item-management#tag/listings) карточки товаров   - получать [категории, предметы, характеристики и бренды товаров](/openapi/item-management#tag/categoriesSubcategoriesAndCharacteristics)   - загружать [медиафайлы](/openapi/item-management#tag/mediaFiles) в карточки товаров   - настраивать [ярлыки](/openapi/item-management#tag/labels) для поиска товаров   - работать с [рекомендациями](/openapi/item-management#tag/recommendations) для товаров   - устанавливать [цены и скидки](/openapi/item-management#tag/pricesAndDiscounts)   - управлять [остатками товаров](/openapi/item-management#tag/sellerWarehousesInventory) и [складами](/openapi/item-management#tag/sellerWarehouses), если вы работаете по модели продаж со склада продавца  Вы можете протестировать методы работы с товарами в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/itemManagement) для управления карточками товаров  </div>   <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami\">инструкции</a> по <strong>работе с товарами</strong> </div>  
 *
 * The version of the OpenAPI document: items
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetRecomResErrorsInner } from './SetRecomResErrorsInner';
import {
    SetRecomResErrorsInnerFromJSON,
    SetRecomResErrorsInnerFromJSONTyped,
    SetRecomResErrorsInnerToJSON,
    SetRecomResErrorsInnerToJSONTyped,
} from './SetRecomResErrorsInner';

/**
 * 
 * @export
 * @interface SetRecomRes
 */
export interface SetRecomRes {
    /**
     * Есть ли ошибки:
     *   - `false` — ошибок нет. Запрос полностью успешен
     *   - `true` — ошибки есть
     * 
     */
    isError: boolean;
    /**
     * Ошибки. При `"isError":true`
     */
    errors?: Array<SetRecomResErrorsInner>;
}

/**
 * Check if a given object implements the SetRecomRes interface.
 */
export function instanceOfSetRecomRes(value: object): value is SetRecomRes {
    if (!('isError' in value) || value['isError'] === undefined) return false;
    return true;
}

export function SetRecomResFromJSON(json: any): SetRecomRes {
    return SetRecomResFromJSONTyped(json, false);
}

export function SetRecomResFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetRecomRes {
    if (json == null) {
        return json;
    }
    return {
        
        'isError': json['isError'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(SetRecomResErrorsInnerFromJSON)),
    };
}

export function SetRecomResToJSON(json: any): SetRecomRes {
    return SetRecomResToJSONTyped(json, false);
}

export function SetRecomResToJSONTyped(value?: SetRecomRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isError': value['isError'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(SetRecomResErrorsInnerToJSON)),
    };
}

