/* tslint:disable */
/* eslint-disable */
/**
 * Заказы Самовывоз
 * <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/in-store-pickup#tag/inStorePickupAssemblyOrders) и [идентификаторами маркировки](/openapi/in-store-pickup#tag/inStorePickupLabelIdentifiers) заказов модели Самовывоз.<br><br>  Вы можете протестировать методы заказов Самовывоз в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-Samovyvoz) для эмуляции действий пользователя  </div> 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInner } from './PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInner';
import {
    PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInnerFromJSON,
    PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInnerFromJSONTyped,
    PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInnerToJSON,
    PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInnerToJSONTyped,
} from './PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInner';

/**
 * 
 * @export
 * @interface PostV3ClickCollectOrdersMetaCustomsDeclarationRequest
 */
export interface PostV3ClickCollectOrdersMetaCustomsDeclarationRequest {
    /**
     * 
     * @type {Array<PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInner>}
     * @memberof PostV3ClickCollectOrdersMetaCustomsDeclarationRequest
     */
    orders?: Array<PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInner>;
}

/**
 * Check if a given object implements the PostV3ClickCollectOrdersMetaCustomsDeclarationRequest interface.
 */
export function instanceOfPostV3ClickCollectOrdersMetaCustomsDeclarationRequest(value: object): value is PostV3ClickCollectOrdersMetaCustomsDeclarationRequest {
    return true;
}

export function PostV3ClickCollectOrdersMetaCustomsDeclarationRequestFromJSON(json: any): PostV3ClickCollectOrdersMetaCustomsDeclarationRequest {
    return PostV3ClickCollectOrdersMetaCustomsDeclarationRequestFromJSONTyped(json, false);
}

export function PostV3ClickCollectOrdersMetaCustomsDeclarationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostV3ClickCollectOrdersMetaCustomsDeclarationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInnerFromJSON)),
    };
}

export function PostV3ClickCollectOrdersMetaCustomsDeclarationRequestToJSON(json: any): PostV3ClickCollectOrdersMetaCustomsDeclarationRequest {
    return PostV3ClickCollectOrdersMetaCustomsDeclarationRequestToJSONTyped(json, false);
}

export function PostV3ClickCollectOrdersMetaCustomsDeclarationRequestToJSONTyped(value?: PostV3ClickCollectOrdersMetaCustomsDeclarationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(PostV3ClickCollectOrdersMetaCustomsDeclarationRequestOrdersInnerToJSON)),
    };
}

