/*
Заказы DBS

<div class=\"description_important\">   Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/orders-dbs#tag/Sborochnye-zadaniya-DBS) и [идентификаторами маркировки](/openapi/orders-dbs#tag/dbsLabelIdentifiers) заказов DBS (Delivery by Seller).<br><br>  Вы можете протестировать методы заказов DBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-DBS) для эмуляции действий пользователя  </div> 

API version: order
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orders_dbs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiOrdersMetaDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiOrdersMetaDeleteRequest{}

// ApiOrdersMetaDeleteRequest struct for ApiOrdersMetaDeleteRequest
type ApiOrdersMetaDeleteRequest struct {
	// Название идентификатора маркировки для удаления. Передаётся только одно значение
	Key string `json:"key"`
	// Список ID сборочных заданий
	OrderIds []int32 `json:"orderIds"`
}

type _ApiOrdersMetaDeleteRequest ApiOrdersMetaDeleteRequest

// NewApiOrdersMetaDeleteRequest instantiates a new ApiOrdersMetaDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiOrdersMetaDeleteRequest(key string, orderIds []int32) *ApiOrdersMetaDeleteRequest {
	this := ApiOrdersMetaDeleteRequest{}
	this.Key = key
	this.OrderIds = orderIds
	return &this
}

// NewApiOrdersMetaDeleteRequestWithDefaults instantiates a new ApiOrdersMetaDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiOrdersMetaDeleteRequestWithDefaults() *ApiOrdersMetaDeleteRequest {
	this := ApiOrdersMetaDeleteRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *ApiOrdersMetaDeleteRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ApiOrdersMetaDeleteRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ApiOrdersMetaDeleteRequest) SetKey(v string) {
	o.Key = v
}

// GetOrderIds returns the OrderIds field value
func (o *ApiOrdersMetaDeleteRequest) GetOrderIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.OrderIds
}

// GetOrderIdsOk returns a tuple with the OrderIds field value
// and a boolean to check if the value has been set.
func (o *ApiOrdersMetaDeleteRequest) GetOrderIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderIds, true
}

// SetOrderIds sets field value
func (o *ApiOrdersMetaDeleteRequest) SetOrderIds(v []int32) {
	o.OrderIds = v
}

func (o ApiOrdersMetaDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiOrdersMetaDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["orderIds"] = o.OrderIds
	return toSerialize, nil
}

func (o *ApiOrdersMetaDeleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"orderIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiOrdersMetaDeleteRequest := _ApiOrdersMetaDeleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiOrdersMetaDeleteRequest)

	if err != nil {
		return err
	}

	*o = ApiOrdersMetaDeleteRequest(varApiOrdersMetaDeleteRequest)

	return err
}

type NullableApiOrdersMetaDeleteRequest struct {
	value *ApiOrdersMetaDeleteRequest
	isSet bool
}

func (v NullableApiOrdersMetaDeleteRequest) Get() *ApiOrdersMetaDeleteRequest {
	return v.value
}

func (v *NullableApiOrdersMetaDeleteRequest) Set(val *ApiOrdersMetaDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiOrdersMetaDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiOrdersMetaDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiOrdersMetaDeleteRequest(val *ApiOrdersMetaDeleteRequest) *NullableApiOrdersMetaDeleteRequest {
	return &NullableApiOrdersMetaDeleteRequest{value: val, isSet: true}
}

func (v NullableApiOrdersMetaDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiOrdersMetaDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


