/*
Заказы DBS

<div class=\"description_important\">   Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/orders-dbs#tag/Sborochnye-zadaniya-DBS) и [идентификаторами маркировки](/openapi/orders-dbs#tag/dbsLabelIdentifiers) заказов DBS (Delivery by Seller).<br><br>  Вы можете протестировать методы заказов DBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-DBS) для эмуляции действий пользователя  </div> 

API version: order
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orders_dbs

import (
	"encoding/json"
)

// checks if the ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest{}

// ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest struct for ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest
type ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest struct {
	Orders []ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequestOrdersInner `json:"orders,omitempty"`
}

// NewApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest instantiates a new ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest() *ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest {
	this := ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest{}
	return &this
}

// NewApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequestWithDefaults instantiates a new ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequestWithDefaults() *ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest {
	this := ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest{}
	return &this
}

// GetOrders returns the Orders field value if set, zero value otherwise.
func (o *ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) GetOrders() []ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequestOrdersInner {
	if o == nil || IsNil(o.Orders) {
		var ret []ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequestOrdersInner
		return ret
	}
	return o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) GetOrdersOk() ([]ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequestOrdersInner, bool) {
	if o == nil || IsNil(o.Orders) {
		return nil, false
	}
	return o.Orders, true
}

// HasOrders returns a boolean if a field has been set.
func (o *ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) HasOrders() bool {
	if o != nil && !IsNil(o.Orders) {
		return true
	}

	return false
}

// SetOrders gets a reference to the given []ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequestOrdersInner and assigns it to the Orders field.
func (o *ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) SetOrders(v []ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequestOrdersInner) {
	o.Orders = v
}

func (o ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Orders) {
		toSerialize["orders"] = o.Orders
	}
	return toSerialize, nil
}

type NullableApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest struct {
	value *ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest
	isSet bool
}

func (v NullableApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) Get() *ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest {
	return v.value
}

func (v *NullableApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) Set(val *ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest(val *ApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) *NullableApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest {
	return &NullableApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest{value: val, isSet: true}
}

func (v NullableApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMarketplaceV3DbsOrdersMetaCustomsDeclarationPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


