/* tslint:disable */
/* eslint-disable */
/**
 * Отчёты
 * <div class=\"description_important\">   Узнать больше об отчётах можно в <a href=\"https://seller.wildberries.ru/instructions/subcategory/5f2162c5-069b-416d-a4e1-48da2a76e6b0\">справочном центре</a> </div>  <div class=\"api-block\">  С помощью этих методов вы можете получать [основные отчёты](/openapi/reports#tag/Osnovnye-otchyoty) и отчёты о:   1. [Остатках на складах](/openapi/reports#tag/Otchyot-ob-ostatkah-na-skladah)   2. [Товарах с обязательной маркировкой](/openapi/reports#tag/Otchyot-o-tovarah-c-obyazatelnoj-markirovkoj)   3. [Удержаниях](/openapi/reports#tag/Otchyoty-ob-uderzhaniyah)   4. [Операциях при приёмке](/openapi/reports#tag/Operacii-pri-priyomke)   5. [Платном хранении](/openapi/reports#tag/Platnoe-hranenie)   6. [Продажах по регионам](/openapi/reports#tag/Prodazhi-po-regionam)   7. [Доле бренда в продажах](/openapi/reports#tag/Dolya-brenda-v-prodazhah)   8. [Заблокированных карточках](/openapi/reports#tag/Zablokirovannye-kartochki)   9. [Возвратах и перемещении товаров](/openapi/reports#tag/Otchyot-o-vozvratah-i-peremeshenii-tovarov)  </div> 
 *
 * The version of the OpenAPI document: reports
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner
 */
export interface ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner {
    /**
     * Название склада
     * @type {string}
     * @memberof ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner
     */
    warehouseName?: string;
    /**
     * Количество, шт.
     * 
     * @type {number}
     * @memberof ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner
     */
    quantity?: number;
}

/**
 * Check if a given object implements the ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner interface.
 */
export function instanceOfApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner(value: object): value is ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner {
    return true;
}

export function ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInnerFromJSON(json: any): ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner {
    return ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInnerFromJSONTyped(json, false);
}

export function ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'warehouseName': json['warehouseName'] == null ? undefined : json['warehouseName'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInnerToJSON(json: any): ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner {
    return ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInnerToJSONTyped(json, false);
}

export function ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInnerToJSONTyped(value?: ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInnerWarehousesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'warehouseName': value['warehouseName'],
        'quantity': value['quantity'],
    };
}

