/* tslint:disable */
/* eslint-disable */
/**
 * Отчёты
 * <div class=\"description_important\">   Узнать больше об отчётах можно в <a href=\"https://seller.wildberries.ru/instructions/subcategory/5f2162c5-069b-416d-a4e1-48da2a76e6b0\">справочном центре</a> </div>  <div class=\"api-block\">  С помощью этих методов вы можете получать [основные отчёты](/openapi/reports#tag/mainReports) и отчёты о:   1. [Остатках на складах](/openapi/reports#tag/warehousesInventoryReport)   2. [Товарах с обязательной маркировкой](/openapi/reports#tag/reportOnItemsWithMandatoryLabeling)   3. [Удержаниях](/openapi/reports#tag/retentionReports)   4. [Операциях при приёмке](/openapi/reports#tag/acceptanceExpenses)   5. [Платном хранении](/openapi/reports#tag/paidStorage)   6. [Продажах по регионам](/openapi/reports#tag/salesByRegions)   7. [Доле бренда в продажах](/openapi/reports#tag/shareOfBrandInSales)   8. [Заблокированных карточках](/openapi/reports#tag/blockedItems)   9. [Возвратах и перемещении товаров](/openapi/reports#tag/returnsAndItemMovementReport)  </div> 
 *
 * The version of the OpenAPI document: reports
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTaskResponseData
 */
export interface CreateTaskResponseData {
    /**
     * ID задания на генерацию
     */
    taskId?: string;
}

/**
 * Check if a given object implements the CreateTaskResponseData interface.
 */
export function instanceOfCreateTaskResponseData(value: object): value is CreateTaskResponseData {
    return true;
}

export function CreateTaskResponseDataFromJSON(json: any): CreateTaskResponseData {
    return CreateTaskResponseDataFromJSONTyped(json, false);
}

export function CreateTaskResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
    };
}

export function CreateTaskResponseDataToJSON(json: any): CreateTaskResponseData {
    return CreateTaskResponseDataToJSONTyped(json, false);
}

export function CreateTaskResponseDataToJSONTyped(value?: CreateTaskResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
    };
}

