/* tslint:disable */
/* eslint-disable */
/**
 * Отчёты
 * <div class=\"description_important\">   Узнать больше об отчётах можно в <a href=\"https://seller.wildberries.ru/instructions/subcategory/5f2162c5-069b-416d-a4e1-48da2a76e6b0\">справочном центре</a> </div>  <div class=\"api-block\">  С помощью этих методов вы можете получать [основные отчёты](/openapi/reports#tag/Osnovnye-otchyoty) и отчёты о:   1. [Остатках на складах](/openapi/reports#tag/Otchyot-ob-ostatkah-na-skladah)   2. [Товарах с обязательной маркировкой](/openapi/reports#tag/Otchyot-o-tovarah-c-obyazatelnoj-markirovkoj)   3. [Удержаниях](/openapi/reports#tag/Otchyoty-ob-uderzhaniyah)   4. [Операциях при приёмке](/openapi/reports#tag/Operacii-pri-priyomke)   5. [Платном хранении](/openapi/reports#tag/Platnoe-hranenie)   6. [Продажах по регионам](/openapi/reports#tag/Prodazhi-po-regionam)   7. [Доле бренда в продажах](/openapi/reports#tag/Dolya-brenda-v-prodazhah)   8. [Заблокированных карточках](/openapi/reports#tag/Zablokirovannye-kartochki)   9. [Возвратах и перемещении товаров](/openapi/reports#tag/Otchyot-o-vozvratah-i-peremeshenii-tovarov)  </div> 
 *
 * The version of the OpenAPI document: reports
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SalesItem
 */
export interface SalesItem {
    /**
     * Дата и время продажи. Это поле соответствует параметру `dateFrom` в запросе, если параметр `flag`=1. Если часовой пояс не указан, то берётся Московское время (UTC+3).
     */
    date?: string;
    /**
     * Дата и время обновления информации в сервисе. Это поле соответствует параметру `dateFrom` в запросе, если параметр `flag`=0 или не указан. Если часовой пояс не указан, то берётся Московское время (UTC+3).
     */
    lastChangeDate?: string;
    /**
     * Склад отгрузки
     */
    warehouseName?: string;
    /**
     * Тип склада хранения товаров
     */
    warehouseType?: SalesItemWarehouseTypeEnum;
    /**
     * Страна
     */
    countryName?: string;
    /**
     * Округ
     */
    oblastOkrugName?: string;
    /**
     * Регион
     */
    regionName?: string;
    /**
     * Артикул продавца
     */
    supplierArticle?: string;
    /**
     * Артикул WB
     */
    nmId?: number;
    /**
     * Баркод
     */
    barcode?: string;
    /**
     * Категория
     */
    category?: string;
    /**
     * Предмет
     */
    subject?: string;
    /**
     * Бренд
     */
    brand?: string;
    /**
     * Размер товара
     */
    techSize?: string;
    /**
     * Номер поставки
     */
    incomeID?: number;
    /**
     * Договор поставки
     */
    isSupply?: boolean;
    /**
     * Договор реализации
     */
    isRealization?: boolean;
    /**
     * Цена без скидок
     */
    totalPrice?: number;
    /**
     * Скидка продавца, %
     */
    discountPercent?: number;
    /**
     * Скидка WB, %
     */
    spp?: number;
    /**
     * Скидка за оплату WB Кошельком, ₽
     */
    paymentSaleAmount?: number;
    /**
     * К перечислению продавцу.<br>Синхронизация данных занимает до 24 часов, в течение этого времени в поле может отображаться значение `0`
     */
    forPay?: number;
    /**
     * Фактическая цена с учётом всех скидок (к взиманию с покупателя).<br>Синхронизация данных занимает до 24 часов, в течение этого времени в поле может отображаться значение `0`
     */
    finishedPrice?: number;
    /**
     * Цена со скидкой продавца, в том числе со скидкой WB Клуба, от которой рассчитывается сумма к перечислению продавцу `forPay`.<br>Синхронизация данных занимает до 24 часов, в течение этого времени в поле может отображаться значение `0`
     */
    priceWithDisc?: number;
    /**
     * Уникальный ID продажи/возврата
     * - `S**********` — продажа
     * - `R**********` — возврат (на склад WB)
     * 
     */
    saleID?: string;
    /**
     * ID стикера
     */
    sticker?: string;
    /**
     * ID корзины покупателя. Заказы одной транзакции будут иметь одинаковый `gNumber`
     */
    gNumber?: string;
    /**
     * Уникальный ID заказа.<br>
     * Примечание для использующих API Маркетплейс: `srid` равен `rid` в ответах методов сборочных заданий.
     * 
     */
    srid?: string;
}


/**
 * @export
 */
export const SalesItemWarehouseTypeEnum = {
    Wb: 'Склад WB',
    Value1: 'Склад продавца'
} as const;
export type SalesItemWarehouseTypeEnum = typeof SalesItemWarehouseTypeEnum[keyof typeof SalesItemWarehouseTypeEnum];


/**
 * Check if a given object implements the SalesItem interface.
 */
export function instanceOfSalesItem(value: object): value is SalesItem {
    return true;
}

export function SalesItemFromJSON(json: any): SalesItem {
    return SalesItemFromJSONTyped(json, false);
}

export function SalesItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesItem {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'lastChangeDate': json['lastChangeDate'] == null ? undefined : json['lastChangeDate'],
        'warehouseName': json['warehouseName'] == null ? undefined : json['warehouseName'],
        'warehouseType': json['warehouseType'] == null ? undefined : json['warehouseType'],
        'countryName': json['countryName'] == null ? undefined : json['countryName'],
        'oblastOkrugName': json['oblastOkrugName'] == null ? undefined : json['oblastOkrugName'],
        'regionName': json['regionName'] == null ? undefined : json['regionName'],
        'supplierArticle': json['supplierArticle'] == null ? undefined : json['supplierArticle'],
        'nmId': json['nmId'] == null ? undefined : json['nmId'],
        'barcode': json['barcode'] == null ? undefined : json['barcode'],
        'category': json['category'] == null ? undefined : json['category'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'techSize': json['techSize'] == null ? undefined : json['techSize'],
        'incomeID': json['incomeID'] == null ? undefined : json['incomeID'],
        'isSupply': json['isSupply'] == null ? undefined : json['isSupply'],
        'isRealization': json['isRealization'] == null ? undefined : json['isRealization'],
        'totalPrice': json['totalPrice'] == null ? undefined : json['totalPrice'],
        'discountPercent': json['discountPercent'] == null ? undefined : json['discountPercent'],
        'spp': json['spp'] == null ? undefined : json['spp'],
        'paymentSaleAmount': json['paymentSaleAmount'] == null ? undefined : json['paymentSaleAmount'],
        'forPay': json['forPay'] == null ? undefined : json['forPay'],
        'finishedPrice': json['finishedPrice'] == null ? undefined : json['finishedPrice'],
        'priceWithDisc': json['priceWithDisc'] == null ? undefined : json['priceWithDisc'],
        'saleID': json['saleID'] == null ? undefined : json['saleID'],
        'sticker': json['sticker'] == null ? undefined : json['sticker'],
        'gNumber': json['gNumber'] == null ? undefined : json['gNumber'],
        'srid': json['srid'] == null ? undefined : json['srid'],
    };
}

export function SalesItemToJSON(json: any): SalesItem {
    return SalesItemToJSONTyped(json, false);
}

export function SalesItemToJSONTyped(value?: SalesItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'lastChangeDate': value['lastChangeDate'],
        'warehouseName': value['warehouseName'],
        'warehouseType': value['warehouseType'],
        'countryName': value['countryName'],
        'oblastOkrugName': value['oblastOkrugName'],
        'regionName': value['regionName'],
        'supplierArticle': value['supplierArticle'],
        'nmId': value['nmId'],
        'barcode': value['barcode'],
        'category': value['category'],
        'subject': value['subject'],
        'brand': value['brand'],
        'techSize': value['techSize'],
        'incomeID': value['incomeID'],
        'isSupply': value['isSupply'],
        'isRealization': value['isRealization'],
        'totalPrice': value['totalPrice'],
        'discountPercent': value['discountPercent'],
        'spp': value['spp'],
        'paymentSaleAmount': value['paymentSaleAmount'],
        'forPay': value['forPay'],
        'finishedPrice': value['finishedPrice'],
        'priceWithDisc': value['priceWithDisc'],
        'saleID': value['saleID'],
        'sticker': value['sticker'],
        'gNumber': value['gNumber'],
        'srid': value['srid'],
    };
}

