/* tslint:disable */
/* eslint-disable */
/**
 * Общение с покупателями
 * <div class=\"description_important\">   Узнать больше об общении с покупателями можно в <a href=\"https://seller.wildberries.ru/instructions/category/f7f6c465-dd12-422d-80a0-a6d9562115d5?goBackOption=prevRoute&categoryId=30817062-14cc-4a82-bc78-3600c2b0685b\">справочном центре</a> </div>  <div class=\"api-block\">  С помощью методов общения с покупателями вы можете работать с:   1. [Вопросами](/openapi/user-communication#tag/Voprosy) и [отзывами](/openapi/user-communication#tag/Otzyvy) покупателей   2. [Закреплёнными отзывами](/openapi/user-communication#tag/Zakreplyonnye-otzyvy)   3. [Чатами с покупателями](/openapi/user-communication#tag/Chat-s-pokupatelyami)   4. [Заявками покупателей на возврат](/openapi/user-communication#tag/Vozvraty-pokupatelyami)  Вы можете протестировать методы общения с покупателями в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Voprosy-i-otzyvy) для управления тестовыми вопросами и отзывами  </div>  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-0b26-7620-8d0b-e3050b7cd01d/obshchenie-s-pokupateliami\">инструкции</a> по работе с разделом <strong>Общение с покупателями</strong> </div> 
 *
 * The version of the OpenAPI document: communication
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventsResult } from './EventsResult';
import {
    EventsResultFromJSON,
    EventsResultFromJSONTyped,
    EventsResultToJSON,
    EventsResultToJSONTyped,
} from './EventsResult';

/**
 * 
 * @export
 * @interface EventsResponse
 */
export interface EventsResponse {
    /**
     * 
     * @type {EventsResult}
     * @memberof EventsResponse
     */
    result?: EventsResult;
    /**
     * Ошибки, если есть
     * @type {Array<string>}
     * @memberof EventsResponse
     */
    errors?: Array<string> | null;
}

/**
 * Check if a given object implements the EventsResponse interface.
 */
export function instanceOfEventsResponse(value: object): value is EventsResponse {
    return true;
}

export function EventsResponseFromJSON(json: any): EventsResponse {
    return EventsResponseFromJSONTyped(json, false);
}

export function EventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : EventsResultFromJSON(json['result']),
        'errors': json['errors'] === undefined ? undefined : json['errors'] === null ? null : json['errors'],
    };
}

export function EventsResponseToJSON(json: any): EventsResponse {
    return EventsResponseToJSONTyped(json, false);
}

export function EventsResponseToJSONTyped(value?: EventsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': EventsResultToJSON(value['result']),
        'errors': value['errors'],
    };
}

