/* tslint:disable */
/* eslint-disable */
/**
 * Общение с покупателями
 * <div class=\"description_important\">   Узнать больше об общении с покупателями можно в <a href=\"https://seller.wildberries.ru/instructions/category/f7f6c465-dd12-422d-80a0-a6d9562115d5?goBackOption=prevRoute&categoryId=30817062-14cc-4a82-bc78-3600c2b0685b\">справочном центре</a> </div>  <div class=\"api-block\">  С помощью методов общения с покупателями вы можете работать с:   1. [Вопросами](/openapi/user-communication#tag/questions) и [отзывами](/openapi/user-communication#tag/feedbacks) покупателей   2. [Закреплёнными отзывами](/openapi/user-communication#tag/pinnedFeedbacks)   3. [Чатами с покупателями](/openapi/user-communication#tag/buyersChat)   4. [Заявками покупателей на возврат](/openapi/user-communication#tag/buyersReturns)  Вы можете протестировать методы общения с покупателями в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Voprosy-i-otzyvy) для управления тестовыми вопросами и отзывами  </div>   <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-0b26-7620-8d0b-e3050b7cd01d/obshchenie-s-pokupateliami\">инструкции</a> по работе с разделом <strong>Общение с покупателями</strong> </div>  
 *
 * The version of the OpenAPI document: communication
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { GetV1Feedback200ResponseDataPhotoLinksInner } from './GetV1Feedback200ResponseDataPhotoLinksInner';
import {
    GetV1Feedback200ResponseDataPhotoLinksInnerFromJSON,
    GetV1Feedback200ResponseDataPhotoLinksInnerFromJSONTyped,
    GetV1Feedback200ResponseDataPhotoLinksInnerToJSON,
    GetV1Feedback200ResponseDataPhotoLinksInnerToJSONTyped,
} from './GetV1Feedback200ResponseDataPhotoLinksInner';
import type { GetV1Feedback200ResponseDataProductDetails } from './GetV1Feedback200ResponseDataProductDetails';
import {
    GetV1Feedback200ResponseDataProductDetailsFromJSON,
    GetV1Feedback200ResponseDataProductDetailsFromJSONTyped,
    GetV1Feedback200ResponseDataProductDetailsToJSON,
    GetV1Feedback200ResponseDataProductDetailsToJSONTyped,
} from './GetV1Feedback200ResponseDataProductDetails';
import type { GetV1Feedback200ResponseDataVideo } from './GetV1Feedback200ResponseDataVideo';
import {
    GetV1Feedback200ResponseDataVideoFromJSON,
    GetV1Feedback200ResponseDataVideoFromJSONTyped,
    GetV1Feedback200ResponseDataVideoToJSON,
    GetV1Feedback200ResponseDataVideoToJSONTyped,
} from './GetV1Feedback200ResponseDataVideo';
import type { GetV1Feedback200ResponseDataAnswer } from './GetV1Feedback200ResponseDataAnswer';
import {
    GetV1Feedback200ResponseDataAnswerFromJSON,
    GetV1Feedback200ResponseDataAnswerFromJSONTyped,
    GetV1Feedback200ResponseDataAnswerToJSON,
    GetV1Feedback200ResponseDataAnswerToJSONTyped,
} from './GetV1Feedback200ResponseDataAnswer';

/**
 * 
 * @export
 * @interface GetV1Feedback200ResponseData
 */
export interface GetV1Feedback200ResponseData {
    /**
     * ID отзыва
     */
    id?: string;
    /**
     * Текст отзыва
     */
    text?: string;
    /**
     * Достоинства товара
     */
    pros?: string;
    /**
     * Недостатки товара
     */
    cons?: string;
    /**
     * Соответствие заявленного размера реальному.
     * <br>Возможные значения:
     * - ` ` - для безразмерных товаров
     * - `ок` - соответствует размеру
     * - `smaller` - маломерит
     * - `bigger` - большемерит
     * 
     */
    matchingSize?: string;
    /**
     * Оценка товара
     */
    productValuation?: number;
    /**
     * Дата и время создания отзыва
     */
    createdDate?: Date;
    /**
     * 
     */
    answer?: GetV1Feedback200ResponseDataAnswer | null;
    /**
     * Статус отзыва:
     *   - `none` - не обработан (новый)
     *   - `wbRu` - обработан
     * 
     */
    state?: string;
    /**
     * 
     */
    productDetails?: GetV1Feedback200ResponseDataProductDetails;
    /**
     * Массив структур фотографий
     */
    photoLinks?: Array<GetV1Feedback200ResponseDataPhotoLinksInner> | null;
    /**
     * Имя автора отзыва
     */
    userName?: string;
    /**
     * Статус заказа.
     * <br>Возможные значения:
     * - `buyout` — выкуплен
     * - `rejected` — отказались
     * - `returned` — возврат
     * - `notSpecified` — статус не присвоен
     * 
     */
    orderStatus?: string;
    /**
     * 
     */
    video?: GetV1Feedback200ResponseDataVideo | null;
    /**
     * Просмотрен ли отзыв
     */
    wasViewed?: boolean;
    /**
     * Доступна ли продавцу возможность оставить жалобу на отзыв:
     *   - `true`— да
     *   - `false` — нет
     * 
     */
    isAbleSupplierFeedbackValuation?: boolean;
    /**
     * Ключ причины жалобы на отзыв
     * 
     */
    supplierFeedbackValuation?: number;
    /**
     * Доступна ли продавцу возможность сообщить о проблеме с товаром  (`true` - доступна, `false` - не доступна)
     */
    isAbleSupplierProductValuation?: boolean;
    /**
     * Ключ проблемы с товаром
     * 
     */
    supplierProductValuation?: number;
    /**
     * Опция возврата товара:
     *   - `true` — доступна
     *   - `false` — недоступна
     * 
     */
    isAbleReturnProductOrders?: boolean;
    /**
     * Дата и время, когда на запрос возврата был получен ответ со статус-кодом 200.
     */
    returnProductOrdersDate?: string | null;
    /**
     * Список тегов покупателя
     */
    bables?: Array<string> | null;
    /**
     * Штрихкод единицы товара
     */
    lastOrderShkId?: number;
    /**
     * Дата покупки
     */
    lastOrderCreatedAt?: string;
    /**
     * Цвет товара
     */
    color?: string;
    /**
     * ID предмета
     */
    subjectId?: number;
    /**
     * Название предмета
     */
    subjectName?: string;
    /**
     * ID начального отзыва (`null`, если этот отзыв начальный)
     */
    parentFeedbackId?: string | null;
    /**
     * ID дополненного отзыва (`null`, если этот отзыв дополненный)
     */
    childFeedbackId?: string | null;
}

/**
 * Check if a given object implements the GetV1Feedback200ResponseData interface.
 */
export function instanceOfGetV1Feedback200ResponseData(value: object): value is GetV1Feedback200ResponseData {
    return true;
}

export function GetV1Feedback200ResponseDataFromJSON(json: any): GetV1Feedback200ResponseData {
    return GetV1Feedback200ResponseDataFromJSONTyped(json, false);
}

export function GetV1Feedback200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetV1Feedback200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
        'pros': json['pros'] == null ? undefined : json['pros'],
        'cons': json['cons'] == null ? undefined : json['cons'],
        'matchingSize': json['matchingSize'] == null ? undefined : json['matchingSize'],
        'productValuation': json['productValuation'] == null ? undefined : json['productValuation'],
        'createdDate': json['createdDate'] == null ? undefined : (parseDateTime(json['createdDate'])),
        'answer': json['answer'] === undefined ? undefined : json['answer'] === null ? null : GetV1Feedback200ResponseDataAnswerFromJSON(json['answer']),
        'state': json['state'] == null ? undefined : json['state'],
        'productDetails': json['productDetails'] == null ? undefined : GetV1Feedback200ResponseDataProductDetailsFromJSON(json['productDetails']),
        'photoLinks': json['photoLinks'] === undefined ? undefined : json['photoLinks'] === null ? null : ((json['photoLinks'] as Array<any>).map(GetV1Feedback200ResponseDataPhotoLinksInnerFromJSON)),
        'userName': json['userName'] == null ? undefined : json['userName'],
        'orderStatus': json['orderStatus'] == null ? undefined : json['orderStatus'],
        'video': json['video'] === undefined ? undefined : json['video'] === null ? null : GetV1Feedback200ResponseDataVideoFromJSON(json['video']),
        'wasViewed': json['wasViewed'] == null ? undefined : json['wasViewed'],
        'isAbleSupplierFeedbackValuation': json['isAbleSupplierFeedbackValuation'] == null ? undefined : json['isAbleSupplierFeedbackValuation'],
        'supplierFeedbackValuation': json['supplierFeedbackValuation'] == null ? undefined : json['supplierFeedbackValuation'],
        'isAbleSupplierProductValuation': json['isAbleSupplierProductValuation'] == null ? undefined : json['isAbleSupplierProductValuation'],
        'supplierProductValuation': json['supplierProductValuation'] == null ? undefined : json['supplierProductValuation'],
        'isAbleReturnProductOrders': json['isAbleReturnProductOrders'] == null ? undefined : json['isAbleReturnProductOrders'],
        'returnProductOrdersDate': json['returnProductOrdersDate'] === undefined ? undefined : json['returnProductOrdersDate'] === null ? null : json['returnProductOrdersDate'],
        'bables': json['bables'] === undefined ? undefined : json['bables'] === null ? null : json['bables'],
        'lastOrderShkId': json['lastOrderShkId'] == null ? undefined : json['lastOrderShkId'],
        'lastOrderCreatedAt': json['lastOrderCreatedAt'] == null ? undefined : json['lastOrderCreatedAt'],
        'color': json['color'] == null ? undefined : json['color'],
        'subjectId': json['subjectId'] == null ? undefined : json['subjectId'],
        'subjectName': json['subjectName'] == null ? undefined : json['subjectName'],
        'parentFeedbackId': json['parentFeedbackId'] === undefined ? undefined : json['parentFeedbackId'] === null ? null : json['parentFeedbackId'],
        'childFeedbackId': json['childFeedbackId'] === undefined ? undefined : json['childFeedbackId'] === null ? null : json['childFeedbackId'],
    };
}

export function GetV1Feedback200ResponseDataToJSON(json: any): GetV1Feedback200ResponseData {
    return GetV1Feedback200ResponseDataToJSONTyped(json, false);
}

export function GetV1Feedback200ResponseDataToJSONTyped(value?: GetV1Feedback200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'pros': value['pros'],
        'cons': value['cons'],
        'matchingSize': value['matchingSize'],
        'productValuation': value['productValuation'],
        'createdDate': value['createdDate'] == null ? value['createdDate'] : serializeDateTime(value['createdDate']),
        'answer': GetV1Feedback200ResponseDataAnswerToJSON(value['answer']),
        'state': value['state'],
        'productDetails': GetV1Feedback200ResponseDataProductDetailsToJSON(value['productDetails']),
        'photoLinks': value['photoLinks'] == null ? undefined : ((value['photoLinks'] as Array<any>).map(GetV1Feedback200ResponseDataPhotoLinksInnerToJSON)),
        'userName': value['userName'],
        'orderStatus': value['orderStatus'],
        'video': GetV1Feedback200ResponseDataVideoToJSON(value['video']),
        'wasViewed': value['wasViewed'],
        'isAbleSupplierFeedbackValuation': value['isAbleSupplierFeedbackValuation'],
        'supplierFeedbackValuation': value['supplierFeedbackValuation'],
        'isAbleSupplierProductValuation': value['isAbleSupplierProductValuation'],
        'supplierProductValuation': value['supplierProductValuation'],
        'isAbleReturnProductOrders': value['isAbleReturnProductOrders'],
        'returnProductOrdersDate': value['returnProductOrdersDate'],
        'bables': value['bables'],
        'lastOrderShkId': value['lastOrderShkId'],
        'lastOrderCreatedAt': value['lastOrderCreatedAt'],
        'color': value['color'],
        'subjectId': value['subjectId'],
        'subjectName': value['subjectName'],
        'parentFeedbackId': value['parentFeedbackId'],
        'childFeedbackId': value['childFeedbackId'],
    };
}

