/* tslint:disable */
/* eslint-disable */
/**
 * Маркетинг и продвижение
 * <div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/promoCalendar)  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.<br><br>  Вы можете протестировать методы продвижения в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Prodvizhenie) для управления тестовым балансом  </div> 
 *
 * The version of the OpenAPI document: promotion
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdvV1BalanceGet200ResponseCashbacksInner
 */
export interface AdvV1BalanceGet200ResponseCashbacksInner {
    /**
     * Промо-бонусы в базовых единицах валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)
     * @type {number}
     * @memberof AdvV1BalanceGet200ResponseCashbacksInner
     */
    sum?: number;
    /**
     * Процент от суммы пополнения бюджета кампании, который можно оплатить промо-бонусами за один раз
     * @type {number}
     * @memberof AdvV1BalanceGet200ResponseCashbacksInner
     */
    percent?: number;
    /**
     * Дата окончания действия промо-бонусов
     * @type {string}
     * @memberof AdvV1BalanceGet200ResponseCashbacksInner
     */
    expirationDate?: string;
}

/**
 * Check if a given object implements the AdvV1BalanceGet200ResponseCashbacksInner interface.
 */
export function instanceOfAdvV1BalanceGet200ResponseCashbacksInner(value: object): value is AdvV1BalanceGet200ResponseCashbacksInner {
    return true;
}

export function AdvV1BalanceGet200ResponseCashbacksInnerFromJSON(json: any): AdvV1BalanceGet200ResponseCashbacksInner {
    return AdvV1BalanceGet200ResponseCashbacksInnerFromJSONTyped(json, false);
}

export function AdvV1BalanceGet200ResponseCashbacksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvV1BalanceGet200ResponseCashbacksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'sum': json['sum'] == null ? undefined : json['sum'],
        'percent': json['percent'] == null ? undefined : json['percent'],
        'expirationDate': json['expiration_date'] == null ? undefined : json['expiration_date'],
    };
}

export function AdvV1BalanceGet200ResponseCashbacksInnerToJSON(json: any): AdvV1BalanceGet200ResponseCashbacksInner {
    return AdvV1BalanceGet200ResponseCashbacksInnerToJSONTyped(json, false);
}

export function AdvV1BalanceGet200ResponseCashbacksInnerToJSONTyped(value?: AdvV1BalanceGet200ResponseCashbacksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sum': value['sum'],
        'percent': value['percent'],
        'expiration_date': value['expirationDate'],
    };
}

