/* tslint:disable */
/* eslint-disable */
/**
 * Маркетинг и продвижение
 * <div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/campaigns) и [медиакампаниях](/openapi/promotion#tag/media)   2. [Создавать](/openapi/promotion#tag/creatingCampaigns) и [управлять](/openapi/promotion#tag/campaignManagement) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/finances) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/statistics) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/promoCalendar)  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.<br><br>  Вы можете протестировать методы продвижения в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Prodvizhenie) для управления тестовым балансом  </div> 
 *
 * The version of the OpenAPI document: promotion
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PatchV1BidsRequestBidsInnerNmBidsInner } from './PatchV1BidsRequestBidsInnerNmBidsInner';
import {
    PatchV1BidsRequestBidsInnerNmBidsInnerFromJSON,
    PatchV1BidsRequestBidsInnerNmBidsInnerFromJSONTyped,
    PatchV1BidsRequestBidsInnerNmBidsInnerToJSON,
    PatchV1BidsRequestBidsInnerNmBidsInnerToJSONTyped,
} from './PatchV1BidsRequestBidsInnerNmBidsInner';

/**
 * 
 * @export
 * @interface PatchV1BidsRequestBidsInner
 */
export interface PatchV1BidsRequestBidsInner {
    /**
     * ID кампании
     */
    advertId: number;
    /**
     * Ставки
     */
    nmBids: Array<PatchV1BidsRequestBidsInnerNmBidsInner>;
}

/**
 * Check if a given object implements the PatchV1BidsRequestBidsInner interface.
 */
export function instanceOfPatchV1BidsRequestBidsInner(value: object): value is PatchV1BidsRequestBidsInner {
    if ((!('advertId' in (value as Record<string, any>)) && !('advert_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['advertId'] === undefined && (value as Record<string, any>)['advert_id'] === undefined)) return false;
    if ((!('nmBids' in (value as Record<string, any>)) && !('nm_bids' in (value as Record<string, any>))) || ((value as Record<string, any>)['nmBids'] === undefined && (value as Record<string, any>)['nm_bids'] === undefined)) return false;
    return true;
}

export function PatchV1BidsRequestBidsInnerFromJSON(json: any): PatchV1BidsRequestBidsInner {
    return PatchV1BidsRequestBidsInnerFromJSONTyped(json, false);
}

export function PatchV1BidsRequestBidsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchV1BidsRequestBidsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'advertId': json['advert_id'],
        'nmBids': ((json['nm_bids'] as Array<any>).map(PatchV1BidsRequestBidsInnerNmBidsInnerFromJSON)),
    };
}

export function PatchV1BidsRequestBidsInnerToJSON(json: any): PatchV1BidsRequestBidsInner {
    return PatchV1BidsRequestBidsInnerToJSONTyped(json, false);
}

export function PatchV1BidsRequestBidsInnerToJSONTyped(value?: PatchV1BidsRequestBidsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advert_id': value['advertId'],
        'nm_bids': ((value['nmBids'] as Array<any>).map(PatchV1BidsRequestBidsInnerNmBidsInnerToJSON)),
    };
}

