/*
Маркетинг и продвижение

<div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij)  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  </div> 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
)

// checks if the ResponseAdvError1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseAdvError1{}

// ResponseAdvError1 struct for ResponseAdvError1
type ResponseAdvError1 struct {
	Error *string `json:"error,omitempty"`
}

// NewResponseAdvError1 instantiates a new ResponseAdvError1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseAdvError1() *ResponseAdvError1 {
	this := ResponseAdvError1{}
	return &this
}

// NewResponseAdvError1WithDefaults instantiates a new ResponseAdvError1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseAdvError1WithDefaults() *ResponseAdvError1 {
	this := ResponseAdvError1{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ResponseAdvError1) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseAdvError1) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ResponseAdvError1) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ResponseAdvError1) SetError(v string) {
	o.Error = &v
}

func (o ResponseAdvError1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseAdvError1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableResponseAdvError1 struct {
	value *ResponseAdvError1
	isSet bool
}

func (v NullableResponseAdvError1) Get() *ResponseAdvError1 {
	return v.value
}

func (v *NullableResponseAdvError1) Set(val *ResponseAdvError1) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseAdvError1) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseAdvError1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseAdvError1(val *ResponseAdvError1) *NullableResponseAdvError1 {
	return &NullableResponseAdvError1{value: val, isSet: true}
}

func (v NullableResponseAdvError1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseAdvError1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


