/*
Маркетинг и продвижение

<div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/promoCalendar)  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.<br><br>  Вы можете протестировать методы продвижения в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Prodvizhenie) для управления тестовым балансом  </div> 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
)

// checks if the ApiV1CalendarPromotionsUploadPost422Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1CalendarPromotionsUploadPost422Response{}

// ApiV1CalendarPromotionsUploadPost422Response struct for ApiV1CalendarPromotionsUploadPost422Response
type ApiV1CalendarPromotionsUploadPost422Response struct {
	// Текст ошибки
	ErrorText *string `json:"errorText,omitempty"`
}

// NewApiV1CalendarPromotionsUploadPost422Response instantiates a new ApiV1CalendarPromotionsUploadPost422Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1CalendarPromotionsUploadPost422Response() *ApiV1CalendarPromotionsUploadPost422Response {
	this := ApiV1CalendarPromotionsUploadPost422Response{}
	return &this
}

// NewApiV1CalendarPromotionsUploadPost422ResponseWithDefaults instantiates a new ApiV1CalendarPromotionsUploadPost422Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1CalendarPromotionsUploadPost422ResponseWithDefaults() *ApiV1CalendarPromotionsUploadPost422Response {
	this := ApiV1CalendarPromotionsUploadPost422Response{}
	return &this
}

// GetErrorText returns the ErrorText field value if set, zero value otherwise.
func (o *ApiV1CalendarPromotionsUploadPost422Response) GetErrorText() string {
	if o == nil || IsNil(o.ErrorText) {
		var ret string
		return ret
	}
	return *o.ErrorText
}

// GetErrorTextOk returns a tuple with the ErrorText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1CalendarPromotionsUploadPost422Response) GetErrorTextOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorText) {
		return nil, false
	}
	return o.ErrorText, true
}

// HasErrorText returns a boolean if a field has been set.
func (o *ApiV1CalendarPromotionsUploadPost422Response) HasErrorText() bool {
	if o != nil && !IsNil(o.ErrorText) {
		return true
	}

	return false
}

// SetErrorText gets a reference to the given string and assigns it to the ErrorText field.
func (o *ApiV1CalendarPromotionsUploadPost422Response) SetErrorText(v string) {
	o.ErrorText = &v
}

func (o ApiV1CalendarPromotionsUploadPost422Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1CalendarPromotionsUploadPost422Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorText) {
		toSerialize["errorText"] = o.ErrorText
	}
	return toSerialize, nil
}

type NullableApiV1CalendarPromotionsUploadPost422Response struct {
	value *ApiV1CalendarPromotionsUploadPost422Response
	isSet bool
}

func (v NullableApiV1CalendarPromotionsUploadPost422Response) Get() *ApiV1CalendarPromotionsUploadPost422Response {
	return v.value
}

func (v *NullableApiV1CalendarPromotionsUploadPost422Response) Set(val *ApiV1CalendarPromotionsUploadPost422Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1CalendarPromotionsUploadPost422Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1CalendarPromotionsUploadPost422Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1CalendarPromotionsUploadPost422Response(val *ApiV1CalendarPromotionsUploadPost422Response) *NullableApiV1CalendarPromotionsUploadPost422Response {
	return &NullableApiV1CalendarPromotionsUploadPost422Response{value: val, isSet: true}
}

func (v NullableApiV1CalendarPromotionsUploadPost422Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1CalendarPromotionsUploadPost422Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


