/*
Маркетинг и продвижение

<div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/promoCalendar)  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.<br><br>  Вы можете протестировать методы продвижения в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Prodvizhenie) для управления тестовым балансом  </div> 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"time"
)

// checks if the DailyStats2Inner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DailyStats2Inner{}

// DailyStats2Inner struct for DailyStats2Inner
type DailyStats2Inner struct {
	// Дата
	Date *time.Time `json:"date,omitempty"`
	// Статистика по платформам
	AppTypeStats []DailyStats2InnerAppTypeStatsInner `json:"app_type_stats,omitempty"`
}

// NewDailyStats2Inner instantiates a new DailyStats2Inner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDailyStats2Inner() *DailyStats2Inner {
	this := DailyStats2Inner{}
	return &this
}

// NewDailyStats2InnerWithDefaults instantiates a new DailyStats2Inner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDailyStats2InnerWithDefaults() *DailyStats2Inner {
	this := DailyStats2Inner{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *DailyStats2Inner) GetDate() time.Time {
	if o == nil || IsNil(o.Date) {
		var ret time.Time
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DailyStats2Inner) GetDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *DailyStats2Inner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given time.Time and assigns it to the Date field.
func (o *DailyStats2Inner) SetDate(v time.Time) {
	o.Date = &v
}

// GetAppTypeStats returns the AppTypeStats field value if set, zero value otherwise.
func (o *DailyStats2Inner) GetAppTypeStats() []DailyStats2InnerAppTypeStatsInner {
	if o == nil || IsNil(o.AppTypeStats) {
		var ret []DailyStats2InnerAppTypeStatsInner
		return ret
	}
	return o.AppTypeStats
}

// GetAppTypeStatsOk returns a tuple with the AppTypeStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DailyStats2Inner) GetAppTypeStatsOk() ([]DailyStats2InnerAppTypeStatsInner, bool) {
	if o == nil || IsNil(o.AppTypeStats) {
		return nil, false
	}
	return o.AppTypeStats, true
}

// HasAppTypeStats returns a boolean if a field has been set.
func (o *DailyStats2Inner) HasAppTypeStats() bool {
	if o != nil && !IsNil(o.AppTypeStats) {
		return true
	}

	return false
}

// SetAppTypeStats gets a reference to the given []DailyStats2InnerAppTypeStatsInner and assigns it to the AppTypeStats field.
func (o *DailyStats2Inner) SetAppTypeStats(v []DailyStats2InnerAppTypeStatsInner) {
	o.AppTypeStats = v
}

func (o DailyStats2Inner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DailyStats2Inner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.AppTypeStats) {
		toSerialize["app_type_stats"] = o.AppTypeStats
	}
	return toSerialize, nil
}

type NullableDailyStats2Inner struct {
	value *DailyStats2Inner
	isSet bool
}

func (v NullableDailyStats2Inner) Get() *DailyStats2Inner {
	return v.value
}

func (v *NullableDailyStats2Inner) Set(val *DailyStats2Inner) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyStats2Inner) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyStats2Inner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyStats2Inner(val *DailyStats2Inner) *NullableDailyStats2Inner {
	return &NullableDailyStats2Inner{value: val, isSet: true}
}

func (v NullableDailyStats2Inner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyStats2Inner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


