/*
Маркетинг и продвижение

<div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/promoCalendar)  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.<br><br>  Вы можете протестировать методы продвижения в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Prodvizhenie) для управления тестовым балансом  </div> 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
)

// checks if the V0BidRecommendationBaseBidTop2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0BidRecommendationBaseBidTop2{}

// V0BidRecommendationBaseBidTop2 Топ-ставка 
type V0BidRecommendationBaseBidTop2 struct {
	// Рекомендуемая ставка в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances). Если `0`, для данного предмета топ-ставка не используется
	BidKopecks *int32 `json:"bidKopecks,omitempty"`
}

// NewV0BidRecommendationBaseBidTop2 instantiates a new V0BidRecommendationBaseBidTop2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0BidRecommendationBaseBidTop2() *V0BidRecommendationBaseBidTop2 {
	this := V0BidRecommendationBaseBidTop2{}
	return &this
}

// NewV0BidRecommendationBaseBidTop2WithDefaults instantiates a new V0BidRecommendationBaseBidTop2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0BidRecommendationBaseBidTop2WithDefaults() *V0BidRecommendationBaseBidTop2 {
	this := V0BidRecommendationBaseBidTop2{}
	return &this
}

// GetBidKopecks returns the BidKopecks field value if set, zero value otherwise.
func (o *V0BidRecommendationBaseBidTop2) GetBidKopecks() int32 {
	if o == nil || IsNil(o.BidKopecks) {
		var ret int32
		return ret
	}
	return *o.BidKopecks
}

// GetBidKopecksOk returns a tuple with the BidKopecks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0BidRecommendationBaseBidTop2) GetBidKopecksOk() (*int32, bool) {
	if o == nil || IsNil(o.BidKopecks) {
		return nil, false
	}
	return o.BidKopecks, true
}

// HasBidKopecks returns a boolean if a field has been set.
func (o *V0BidRecommendationBaseBidTop2) HasBidKopecks() bool {
	if o != nil && !IsNil(o.BidKopecks) {
		return true
	}

	return false
}

// SetBidKopecks gets a reference to the given int32 and assigns it to the BidKopecks field.
func (o *V0BidRecommendationBaseBidTop2) SetBidKopecks(v int32) {
	o.BidKopecks = &v
}

func (o V0BidRecommendationBaseBidTop2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0BidRecommendationBaseBidTop2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BidKopecks) {
		toSerialize["bidKopecks"] = o.BidKopecks
	}
	return toSerialize, nil
}

type NullableV0BidRecommendationBaseBidTop2 struct {
	value *V0BidRecommendationBaseBidTop2
	isSet bool
}

func (v NullableV0BidRecommendationBaseBidTop2) Get() *V0BidRecommendationBaseBidTop2 {
	return v.value
}

func (v *NullableV0BidRecommendationBaseBidTop2) Set(val *V0BidRecommendationBaseBidTop2) {
	v.value = val
	v.isSet = true
}

func (v NullableV0BidRecommendationBaseBidTop2) IsSet() bool {
	return v.isSet
}

func (v *NullableV0BidRecommendationBaseBidTop2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0BidRecommendationBaseBidTop2(val *V0BidRecommendationBaseBidTop2) *NullableV0BidRecommendationBaseBidTop2 {
	return &NullableV0BidRecommendationBaseBidTop2{value: val, isSet: true}
}

func (v NullableV0BidRecommendationBaseBidTop2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0BidRecommendationBaseBidTop2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


