/*
Маркетинг и продвижение

<div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij)  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  </div> 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetAdvertsAdvertsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAdvertsAdvertsInner{}

// GetAdvertsAdvertsInner struct for GetAdvertsAdvertsInner
type GetAdvertsAdvertsInner struct {
	// Тип ставки:   - `unified` — единая ставка   - `manual` — ручная ставка 
	BidType string `json:"bid_type"`
	// ID кампании
	Id int64 `json:"id"`
	// Настройки товаров
	NmSettings []AdvertNMsSettings `json:"nm_settings"`
	Settings AdvertSettings `json:"settings"`
	// Статус кампании: - `-1` — удалена, процесс удаления будет завершён в течение 10 минут - `4` — готова к запуску - `7` — завершена - `8` — отменена - `9` — активна - `11` — на паузе 
	Status int32 `json:"status"`
	Timestamps Timestamps `json:"timestamps"`
}

type _GetAdvertsAdvertsInner GetAdvertsAdvertsInner

// NewGetAdvertsAdvertsInner instantiates a new GetAdvertsAdvertsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAdvertsAdvertsInner(bidType string, id int64, nmSettings []AdvertNMsSettings, settings AdvertSettings, status int32, timestamps Timestamps) *GetAdvertsAdvertsInner {
	this := GetAdvertsAdvertsInner{}
	this.BidType = bidType
	this.Id = id
	this.NmSettings = nmSettings
	this.Settings = settings
	this.Status = status
	this.Timestamps = timestamps
	return &this
}

// NewGetAdvertsAdvertsInnerWithDefaults instantiates a new GetAdvertsAdvertsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAdvertsAdvertsInnerWithDefaults() *GetAdvertsAdvertsInner {
	this := GetAdvertsAdvertsInner{}
	return &this
}

// GetBidType returns the BidType field value
func (o *GetAdvertsAdvertsInner) GetBidType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BidType
}

// GetBidTypeOk returns a tuple with the BidType field value
// and a boolean to check if the value has been set.
func (o *GetAdvertsAdvertsInner) GetBidTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BidType, true
}

// SetBidType sets field value
func (o *GetAdvertsAdvertsInner) SetBidType(v string) {
	o.BidType = v
}

// GetId returns the Id field value
func (o *GetAdvertsAdvertsInner) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetAdvertsAdvertsInner) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetAdvertsAdvertsInner) SetId(v int64) {
	o.Id = v
}

// GetNmSettings returns the NmSettings field value
// If the value is explicit nil, the zero value for []AdvertNMsSettings will be returned
func (o *GetAdvertsAdvertsInner) GetNmSettings() []AdvertNMsSettings {
	if o == nil {
		var ret []AdvertNMsSettings
		return ret
	}

	return o.NmSettings
}

// GetNmSettingsOk returns a tuple with the NmSettings field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAdvertsAdvertsInner) GetNmSettingsOk() ([]AdvertNMsSettings, bool) {
	if o == nil || IsNil(o.NmSettings) {
		return nil, false
	}
	return o.NmSettings, true
}

// SetNmSettings sets field value
func (o *GetAdvertsAdvertsInner) SetNmSettings(v []AdvertNMsSettings) {
	o.NmSettings = v
}

// GetSettings returns the Settings field value
func (o *GetAdvertsAdvertsInner) GetSettings() AdvertSettings {
	if o == nil {
		var ret AdvertSettings
		return ret
	}

	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value
// and a boolean to check if the value has been set.
func (o *GetAdvertsAdvertsInner) GetSettingsOk() (*AdvertSettings, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Settings, true
}

// SetSettings sets field value
func (o *GetAdvertsAdvertsInner) SetSettings(v AdvertSettings) {
	o.Settings = v
}

// GetStatus returns the Status field value
func (o *GetAdvertsAdvertsInner) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetAdvertsAdvertsInner) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetAdvertsAdvertsInner) SetStatus(v int32) {
	o.Status = v
}

// GetTimestamps returns the Timestamps field value
func (o *GetAdvertsAdvertsInner) GetTimestamps() Timestamps {
	if o == nil {
		var ret Timestamps
		return ret
	}

	return o.Timestamps
}

// GetTimestampsOk returns a tuple with the Timestamps field value
// and a boolean to check if the value has been set.
func (o *GetAdvertsAdvertsInner) GetTimestampsOk() (*Timestamps, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamps, true
}

// SetTimestamps sets field value
func (o *GetAdvertsAdvertsInner) SetTimestamps(v Timestamps) {
	o.Timestamps = v
}

func (o GetAdvertsAdvertsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAdvertsAdvertsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bid_type"] = o.BidType
	toSerialize["id"] = o.Id
	if o.NmSettings != nil {
		toSerialize["nm_settings"] = o.NmSettings
	}
	toSerialize["settings"] = o.Settings
	toSerialize["status"] = o.Status
	toSerialize["timestamps"] = o.Timestamps
	return toSerialize, nil
}

func (o *GetAdvertsAdvertsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bid_type",
		"id",
		"nm_settings",
		"settings",
		"status",
		"timestamps",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAdvertsAdvertsInner := _GetAdvertsAdvertsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAdvertsAdvertsInner)

	if err != nil {
		return err
	}

	*o = GetAdvertsAdvertsInner(varGetAdvertsAdvertsInner)

	return err
}

type NullableGetAdvertsAdvertsInner struct {
	value *GetAdvertsAdvertsInner
	isSet bool
}

func (v NullableGetAdvertsAdvertsInner) Get() *GetAdvertsAdvertsInner {
	return v.value
}

func (v *NullableGetAdvertsAdvertsInner) Set(val *GetAdvertsAdvertsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAdvertsAdvertsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAdvertsAdvertsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAdvertsAdvertsInner(val *GetAdvertsAdvertsInner) *NullableGetAdvertsAdvertsInner {
	return &NullableGetAdvertsAdvertsInner{value: val, isSet: true}
}

func (v NullableGetAdvertsAdvertsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAdvertsAdvertsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


