/*
 * Общее
 *
 * <div class=\"api-block\">  В этом разделе: - [общая информация о WB API](/openapi/api-information#tag/introduction) - как [начать работу с WB API](/openapi/api-information#tag/introduction/Kak-nachat-rabotu-s-API) - как [авторизоваться](/openapi/api-information#tag/authorization) и [создавать токены](/openapi/api-information#tag/authorization/Kak-sozdat-personalnyj-bazovyj-ili-testovyj-token) - основные [статус-коды ответов](/openapi/api-information#tag/introduction/Status-kody-HTTP) - [лимиты запросов](/openapi/api-information#tag/introduction/Limity-zaprosov) - как обратиться в [поддержку](/openapi/api-information#tag/introduction/Podderzhka)  С помощью методов этого раздела вы можете: - проверить [подключение к WB API](/openapi/api-information#tag/connectionCheck/operation/getPing) - получить [новости портала продавцов](/openapi/api-information#tag/newsApi/operation/getV2News) - получить [информацию о продавце](/openapi/api-information#tag/sellerInformation/operation/getV1SellerInfo) - [управлять пользователями продавца](/openapi/api-information#tag/sellerUserManagement)  </div> 
 *
 * The version of the OpenAPI document: general
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetUsersResponseUsersInnerInviteeInfo : Информация о приглашении, если пользователь приглашён
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUsersResponseUsersInnerInviteeInfo {
    /// Номер телефона приглашённого пользователя
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    /// Должность приглашённого пользователя
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
    /// ID приглашения
    #[serde(rename = "inviteUuid", skip_serializing_if = "Option::is_none")]
    pub invite_uuid: Option<uuid::Uuid>,
    /// Дата и время окончания срока действия приглашения
    #[serde(rename = "expiredAt", skip_serializing_if = "Option::is_none")]
    pub expired_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// - `true` — приглашение активно - `false` — приглашение неактивно 
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl GetUsersResponseUsersInnerInviteeInfo {
    /// Информация о приглашении, если пользователь приглашён
    pub fn new() -> GetUsersResponseUsersInnerInviteeInfo {
        GetUsersResponseUsersInnerInviteeInfo {
            phone_number: None,
            position: None,
            invite_uuid: None,
            expired_at: None,
            is_active: None,
        }
    }
}

