/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBS
 * <div class=\"description_important\">   Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/orders-dbs#tag/Sborochnye-zadaniya-DBS) и [идентификаторами маркировки](/openapi/orders-dbs#tag/dbsLabelIdentifiers) заказов DBS (Delivery by Seller).<br><br>  Вы можете протестировать методы заказов DBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-DBS) для эмуляции действий пользователя  </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiMarketplaceV3DbsOrdersStickersPostRequest
 */
export interface ApiMarketplaceV3DbsOrdersStickersPostRequest {
    /**
     * Список ID сборочных заданий
     * @type {Array<number>}
     * @memberof ApiMarketplaceV3DbsOrdersStickersPostRequest
     */
    orders: Array<number>;
}

/**
 * Check if a given object implements the ApiMarketplaceV3DbsOrdersStickersPostRequest interface.
 */
export function instanceOfApiMarketplaceV3DbsOrdersStickersPostRequest(value: object): value is ApiMarketplaceV3DbsOrdersStickersPostRequest {
    if (!('orders' in value) || value['orders'] === undefined) return false;
    return true;
}

export function ApiMarketplaceV3DbsOrdersStickersPostRequestFromJSON(json: any): ApiMarketplaceV3DbsOrdersStickersPostRequest {
    return ApiMarketplaceV3DbsOrdersStickersPostRequestFromJSONTyped(json, false);
}

export function ApiMarketplaceV3DbsOrdersStickersPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMarketplaceV3DbsOrdersStickersPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'],
    };
}

export function ApiMarketplaceV3DbsOrdersStickersPostRequestToJSON(json: any): ApiMarketplaceV3DbsOrdersStickersPostRequest {
    return ApiMarketplaceV3DbsOrdersStickersPostRequestToJSONTyped(json, false);
}

export function ApiMarketplaceV3DbsOrdersStickersPostRequestToJSONTyped(value?: ApiMarketplaceV3DbsOrdersStickersPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': value['orders'],
    };
}

