/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBS
 * <div class=\"description_important\">   Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/orders-dbs#tag/dbsAssemblyOrders) и [идентификаторами маркировки](/openapi/orders-dbs#tag/dbsLabelIdentifiers) заказов DBS (Delivery by Seller).<br><br>  Вы можете протестировать методы заказов DBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-DBS) для эмуляции действий пользователя  </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrdersRequestAPI
 */
export interface OrdersRequestAPI {
    /**
     * Список ID сборочных заданий
     */
    orders?: Array<number>;
}

/**
 * Check if a given object implements the OrdersRequestAPI interface.
 */
export function instanceOfOrdersRequestAPI(value: object): value is OrdersRequestAPI {
    return true;
}

export function OrdersRequestAPIFromJSON(json: any): OrdersRequestAPI {
    return OrdersRequestAPIFromJSONTyped(json, false);
}

export function OrdersRequestAPIFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrdersRequestAPI {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'] == null ? undefined : json['orders'],
    };
}

export function OrdersRequestAPIToJSON(json: any): OrdersRequestAPI {
    return OrdersRequestAPIToJSONTyped(json, false);
}

export function OrdersRequestAPIToJSONTyped(value?: OrdersRequestAPI | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': value['orders'],
    };
}

