/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBS
 * <div class=\"description_important\">   Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/orders-dbs#tag/dbsAssemblyOrders) и [идентификаторами маркировки](/openapi/orders-dbs#tag/dbsLabelIdentifiers) заказов DBS (Delivery by Seller).<br><br>  Вы можете протестировать методы заказов DBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-DBS) для эмуляции действий пользователя  </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInner } from './PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInner';
import {
    PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInnerFromJSON,
    PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInnerFromJSONTyped,
    PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInnerToJSON,
    PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInnerToJSONTyped,
} from './PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInner';

/**
 * 
 * @export
 * @interface PostV3DbsOrdersMetaCustomsDeclarationRequest
 */
export interface PostV3DbsOrdersMetaCustomsDeclarationRequest {
    /**
     * 
     * @type {Array<PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInner>}
     * @memberof PostV3DbsOrdersMetaCustomsDeclarationRequest
     */
    orders?: Array<PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInner>;
}

/**
 * Check if a given object implements the PostV3DbsOrdersMetaCustomsDeclarationRequest interface.
 */
export function instanceOfPostV3DbsOrdersMetaCustomsDeclarationRequest(value: object): value is PostV3DbsOrdersMetaCustomsDeclarationRequest {
    return true;
}

export function PostV3DbsOrdersMetaCustomsDeclarationRequestFromJSON(json: any): PostV3DbsOrdersMetaCustomsDeclarationRequest {
    return PostV3DbsOrdersMetaCustomsDeclarationRequestFromJSONTyped(json, false);
}

export function PostV3DbsOrdersMetaCustomsDeclarationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostV3DbsOrdersMetaCustomsDeclarationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInnerFromJSON)),
    };
}

export function PostV3DbsOrdersMetaCustomsDeclarationRequestToJSON(json: any): PostV3DbsOrdersMetaCustomsDeclarationRequest {
    return PostV3DbsOrdersMetaCustomsDeclarationRequestToJSONTyped(json, false);
}

export function PostV3DbsOrdersMetaCustomsDeclarationRequestToJSONTyped(value?: PostV3DbsOrdersMetaCustomsDeclarationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(PostV3DbsOrdersMetaCustomsDeclarationRequestOrdersInnerToJSON)),
    };
}

