/*
Заказы FBS

<div class=\"api-block\">  С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [идентификаторы маркировки](/openapi/orders-fbs#tag/fbsLabelIdentifiers) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  Вы можете протестировать методы заказов FBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-FBS) для эмуляции действий пользователя  </div>   <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-0771-7571-aea9-11d5b597f34c/zakazy-fbs\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>   <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 

API version: order
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orders_fbs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SupplySpotData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupplySpotData{}

// SupplySpotData struct for SupplySpotData
type SupplySpotData struct {
	// Статус СПОТ:   - `pending` — ожидается результат формирования ДОПП — документа о предстоящей поставке   - `completed` — ДОПП успешно сформирован. Можно [получить QR-код](./orders-fbs#tag/Postavki-FBS/operation/getV3FbsSuppliesSupplyIdStickersSpot)   - `failed` — ошибка формирования ДОПП. Подробнее в поле `errorCode` 
	Status string `json:"status"`
	// Наименование перевозчика
	CarrierName string `json:"carrierName"`
	// ИНН перевозчика
	CarrierTaxNumber string `json:"carrierTaxNumber"`
	// Код страны перевозчика по [ОКСМ](./orders-fbs#tag/Postavki-FBS/operation/getV3FbsDictionariesCountriesOksm)
	CarrierCountryCode string `json:"carrierCountryCode"`
	// Регистрационный номер транспортного средства
	VehicleRegistrationNumber string `json:"vehicleRegistrationNumber"`
	// Регистрационный номер прицепа
	TrailerRegistrationNumber *string `json:"trailerRegistrationNumber,omitempty"`
	// Код ошибки от сервиса формирования ДОПП — документа о предстоящей поставке. Возвращается при `\"status\": \"failed\"`. Чтобы исправить ошибку, проверьте данные СПОТ и [добавьте их в поставку](./orders-fbs#tag/Postavki-FBS/operation/getV3FbsSuppliesSupplyIdSpot) ещё раз 
	ErrorCode *string `json:"errorCode,omitempty"`
}

type _SupplySpotData SupplySpotData

// NewSupplySpotData instantiates a new SupplySpotData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupplySpotData(status string, carrierName string, carrierTaxNumber string, carrierCountryCode string, vehicleRegistrationNumber string) *SupplySpotData {
	this := SupplySpotData{}
	this.Status = status
	this.CarrierName = carrierName
	this.CarrierTaxNumber = carrierTaxNumber
	this.CarrierCountryCode = carrierCountryCode
	this.VehicleRegistrationNumber = vehicleRegistrationNumber
	return &this
}

// NewSupplySpotDataWithDefaults instantiates a new SupplySpotData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupplySpotDataWithDefaults() *SupplySpotData {
	this := SupplySpotData{}
	return &this
}

// GetStatus returns the Status field value
func (o *SupplySpotData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SupplySpotData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SupplySpotData) SetStatus(v string) {
	o.Status = v
}

// GetCarrierName returns the CarrierName field value
func (o *SupplySpotData) GetCarrierName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CarrierName
}

// GetCarrierNameOk returns a tuple with the CarrierName field value
// and a boolean to check if the value has been set.
func (o *SupplySpotData) GetCarrierNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CarrierName, true
}

// SetCarrierName sets field value
func (o *SupplySpotData) SetCarrierName(v string) {
	o.CarrierName = v
}

// GetCarrierTaxNumber returns the CarrierTaxNumber field value
func (o *SupplySpotData) GetCarrierTaxNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CarrierTaxNumber
}

// GetCarrierTaxNumberOk returns a tuple with the CarrierTaxNumber field value
// and a boolean to check if the value has been set.
func (o *SupplySpotData) GetCarrierTaxNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CarrierTaxNumber, true
}

// SetCarrierTaxNumber sets field value
func (o *SupplySpotData) SetCarrierTaxNumber(v string) {
	o.CarrierTaxNumber = v
}

// GetCarrierCountryCode returns the CarrierCountryCode field value
func (o *SupplySpotData) GetCarrierCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CarrierCountryCode
}

// GetCarrierCountryCodeOk returns a tuple with the CarrierCountryCode field value
// and a boolean to check if the value has been set.
func (o *SupplySpotData) GetCarrierCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CarrierCountryCode, true
}

// SetCarrierCountryCode sets field value
func (o *SupplySpotData) SetCarrierCountryCode(v string) {
	o.CarrierCountryCode = v
}

// GetVehicleRegistrationNumber returns the VehicleRegistrationNumber field value
func (o *SupplySpotData) GetVehicleRegistrationNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VehicleRegistrationNumber
}

// GetVehicleRegistrationNumberOk returns a tuple with the VehicleRegistrationNumber field value
// and a boolean to check if the value has been set.
func (o *SupplySpotData) GetVehicleRegistrationNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VehicleRegistrationNumber, true
}

// SetVehicleRegistrationNumber sets field value
func (o *SupplySpotData) SetVehicleRegistrationNumber(v string) {
	o.VehicleRegistrationNumber = v
}

// GetTrailerRegistrationNumber returns the TrailerRegistrationNumber field value if set, zero value otherwise.
func (o *SupplySpotData) GetTrailerRegistrationNumber() string {
	if o == nil || IsNil(o.TrailerRegistrationNumber) {
		var ret string
		return ret
	}
	return *o.TrailerRegistrationNumber
}

// GetTrailerRegistrationNumberOk returns a tuple with the TrailerRegistrationNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupplySpotData) GetTrailerRegistrationNumberOk() (*string, bool) {
	if o == nil || IsNil(o.TrailerRegistrationNumber) {
		return nil, false
	}
	return o.TrailerRegistrationNumber, true
}

// HasTrailerRegistrationNumber returns a boolean if a field has been set.
func (o *SupplySpotData) HasTrailerRegistrationNumber() bool {
	if o != nil && !IsNil(o.TrailerRegistrationNumber) {
		return true
	}

	return false
}

// SetTrailerRegistrationNumber gets a reference to the given string and assigns it to the TrailerRegistrationNumber field.
func (o *SupplySpotData) SetTrailerRegistrationNumber(v string) {
	o.TrailerRegistrationNumber = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *SupplySpotData) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupplySpotData) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *SupplySpotData) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *SupplySpotData) SetErrorCode(v string) {
	o.ErrorCode = &v
}

func (o SupplySpotData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupplySpotData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["carrierName"] = o.CarrierName
	toSerialize["carrierTaxNumber"] = o.CarrierTaxNumber
	toSerialize["carrierCountryCode"] = o.CarrierCountryCode
	toSerialize["vehicleRegistrationNumber"] = o.VehicleRegistrationNumber
	if !IsNil(o.TrailerRegistrationNumber) {
		toSerialize["trailerRegistrationNumber"] = o.TrailerRegistrationNumber
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	return toSerialize, nil
}

func (o *SupplySpotData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"carrierName",
		"carrierTaxNumber",
		"carrierCountryCode",
		"vehicleRegistrationNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSupplySpotData := _SupplySpotData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSupplySpotData)

	if err != nil {
		return err
	}

	*o = SupplySpotData(varSupplySpotData)

	return err
}

type NullableSupplySpotData struct {
	value *SupplySpotData
	isSet bool
}

func (v NullableSupplySpotData) Get() *SupplySpotData {
	return v.value
}

func (v *NullableSupplySpotData) Set(val *SupplySpotData) {
	v.value = val
	v.isSet = true
}

func (v NullableSupplySpotData) IsSet() bool {
	return v.isSet
}

func (v *NullableSupplySpotData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupplySpotData(val *SupplySpotData) *NullableSupplySpotData {
	return &NullableSupplySpotData{value: val, isSet: true}
}

func (v NullableSupplySpotData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupplySpotData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


