/*
Заказы FBS

<div class=\"api-block\">  С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/fbsAssemblyOrders) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [идентификаторы маркировки](/openapi/orders-fbs#tag/fbsLabelIdentifiers) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/fbsSupplies)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/fbsPasses) на склады WB  Вы можете протестировать методы заказов FBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/marketplaceFbs) для эмуляции действий пользователя  </div>   <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-0771-7571-aea9-11d5b597f34c/zakazy-fbs\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>   <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 

API version: order
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orders_fbs

import (
	"encoding/json"
)

// checks if the GetV3SuppliesSupplyIdBarcode200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetV3SuppliesSupplyIdBarcode200Response{}

// GetV3SuppliesSupplyIdBarcode200Response struct for GetV3SuppliesSupplyIdBarcode200Response
type GetV3SuppliesSupplyIdBarcode200Response struct {
	// Закодированное значение стикера (ID поставки)
	Barcode *string `json:"barcode,omitempty"`
	// Полное представление стикера в заданном формате (кодировка base64)
	File *string `json:"file,omitempty"`
}

// NewGetV3SuppliesSupplyIdBarcode200Response instantiates a new GetV3SuppliesSupplyIdBarcode200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetV3SuppliesSupplyIdBarcode200Response() *GetV3SuppliesSupplyIdBarcode200Response {
	this := GetV3SuppliesSupplyIdBarcode200Response{}
	return &this
}

// NewGetV3SuppliesSupplyIdBarcode200ResponseWithDefaults instantiates a new GetV3SuppliesSupplyIdBarcode200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetV3SuppliesSupplyIdBarcode200ResponseWithDefaults() *GetV3SuppliesSupplyIdBarcode200Response {
	this := GetV3SuppliesSupplyIdBarcode200Response{}
	return &this
}

// GetBarcode returns the Barcode field value if set, zero value otherwise.
func (o *GetV3SuppliesSupplyIdBarcode200Response) GetBarcode() string {
	if o == nil || IsNil(o.Barcode) {
		var ret string
		return ret
	}
	return *o.Barcode
}

// GetBarcodeOk returns a tuple with the Barcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetV3SuppliesSupplyIdBarcode200Response) GetBarcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Barcode) {
		return nil, false
	}
	return o.Barcode, true
}

// HasBarcode returns a boolean if a field has been set.
func (o *GetV3SuppliesSupplyIdBarcode200Response) HasBarcode() bool {
	if o != nil && !IsNil(o.Barcode) {
		return true
	}

	return false
}

// SetBarcode gets a reference to the given string and assigns it to the Barcode field.
func (o *GetV3SuppliesSupplyIdBarcode200Response) SetBarcode(v string) {
	o.Barcode = &v
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *GetV3SuppliesSupplyIdBarcode200Response) GetFile() string {
	if o == nil || IsNil(o.File) {
		var ret string
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetV3SuppliesSupplyIdBarcode200Response) GetFileOk() (*string, bool) {
	if o == nil || IsNil(o.File) {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *GetV3SuppliesSupplyIdBarcode200Response) HasFile() bool {
	if o != nil && !IsNil(o.File) {
		return true
	}

	return false
}

// SetFile gets a reference to the given string and assigns it to the File field.
func (o *GetV3SuppliesSupplyIdBarcode200Response) SetFile(v string) {
	o.File = &v
}

func (o GetV3SuppliesSupplyIdBarcode200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetV3SuppliesSupplyIdBarcode200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Barcode) {
		toSerialize["barcode"] = o.Barcode
	}
	if !IsNil(o.File) {
		toSerialize["file"] = o.File
	}
	return toSerialize, nil
}

type NullableGetV3SuppliesSupplyIdBarcode200Response struct {
	value *GetV3SuppliesSupplyIdBarcode200Response
	isSet bool
}

func (v NullableGetV3SuppliesSupplyIdBarcode200Response) Get() *GetV3SuppliesSupplyIdBarcode200Response {
	return v.value
}

func (v *NullableGetV3SuppliesSupplyIdBarcode200Response) Set(val *GetV3SuppliesSupplyIdBarcode200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetV3SuppliesSupplyIdBarcode200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetV3SuppliesSupplyIdBarcode200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetV3SuppliesSupplyIdBarcode200Response(val *GetV3SuppliesSupplyIdBarcode200Response) *NullableGetV3SuppliesSupplyIdBarcode200Response {
	return &NullableGetV3SuppliesSupplyIdBarcode200Response{value: val, isSet: true}
}

func (v NullableGetV3SuppliesSupplyIdBarcode200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetV3SuppliesSupplyIdBarcode200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


