/*
 * Аналитика и данные
 *
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/salesFunnel)   2. [Ленты заказов](/openapi/analytics#tag/orderFeed)   3. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/searchQueriesForYourItems)   4. [Истории остатков](/openapi/analytics#tag/stocksReport)   5. [Оценки товара](/openapi/analytics#tag/itemRating)   6. [Аналитики продавца в формате CSV](/openapi/analytics#tag/sellerAnalyticsCsv)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchReportItemReqParams : Параметры отчёта
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchReportItemReqParams {
    #[serde(rename = "currentPeriod")]
    pub current_period: Box<models::Period>,
    #[serde(rename = "pastPeriod", skip_serializing_if = "Option::is_none")]
    pub past_period: Option<Box<models::PastPeriod>>,
    /// ID предмета. Используйте значение `0`, чтобы получить отчёт по всем предметам
    #[serde(rename = "subjectId", skip_serializing_if = "Option::is_none")]
    pub subject_id: Option<i32>,
    /// Бренд
    #[serde(rename = "brandName", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    /// ID ярлыка. Чтобы получить отчёт по всем ярлыкам, укажите значение 0
    #[serde(rename = "tagId", skip_serializing_if = "Option::is_none")]
    pub tag_id: Option<i64>,
    /// Артикулы WB, по которым составить отчёт. Оставьте пустым, чтобы получить отчёт обо всех товарах 
    #[serde(rename = "nmIds", skip_serializing_if = "Option::is_none")]
    pub nm_ids: Option<Vec<i64>>,
    #[serde(rename = "positionCluster")]
    pub position_cluster: models::PositionCluster,
    #[serde(rename = "orderBy")]
    pub order_by: Box<models::OrderBy>,
    /// Показать данные по прямым запросам с [подменным артикулом](https://seller.wildberries.ru/help-center/article/A-524)
    #[serde(rename = "includeSubstitutedSKUs", skip_serializing_if = "Option::is_none")]
    pub include_substituted_skus: Option<bool>,
    /// Показать данные по поисковым запросам без учёта подменного артикула
    #[serde(rename = "includeSearchTexts", skip_serializing_if = "Option::is_none")]
    pub include_search_texts: Option<bool>,
}

impl SearchReportItemReqParams {
    /// Параметры отчёта
    pub fn new(current_period: models::Period, position_cluster: models::PositionCluster, order_by: models::OrderBy) -> SearchReportItemReqParams {
        SearchReportItemReqParams {
            current_period: Box::new(current_period),
            past_period: None,
            subject_id: None,
            brand_name: None,
            tag_id: None,
            nm_ids: None,
            position_cluster,
            order_by: Box::new(order_by),
            include_substituted_skus: None,
            include_search_texts: None,
        }
    }
}

