/*
 * Поставки FBW
 *
 * <div class=\"description_important\">   Узнать больше о поставках FBW можно в <a href=\"https://seller.wildberries.ru/instructions/subcategory/5a8e1202-0865-45b7-acae-5d0afc7add56?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   - [информации для формирования поставок](/openapi/orders-fbw#tag/informationForFormingSupplies)   - [информации о поставках](/openapi/orders-fbw#tag/suppliesInformation)  Вы можете создавать карточки товара в песочнице [Контента](/openapi/api-information#tag/authorization/Kategorii-tokenov), а потом использовать баркоды товаров в <a href='/sandbox'>песочнице</a> Поставок  </div> 
 *
 * The version of the OpenAPI document: ordersfbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsDraftItem {
    /// ID черновика
    #[serde(rename = "draftId")]
    pub draft_id: String,
    /// Телефон пользователя, создавшего черновик
    #[serde(rename = "phone")]
    pub phone: String,
    /// Дата и время создания черновика
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// Дата и время последнего обновления черновика
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// Количество баркодов
    #[serde(rename = "skuQuantity")]
    pub sku_quantity: i32,
    /// Количество единиц товара
    #[serde(rename = "itemQuantity")]
    pub item_quantity: i32,
}

impl ModelsDraftItem {
    pub fn new(draft_id: String, phone: String, created_at: String, updated_at: String, sku_quantity: i32, item_quantity: i32) -> ModelsDraftItem {
        ModelsDraftItem {
            draft_id,
            phone,
            created_at,
            updated_at,
            sku_quantity,
            item_quantity,
        }
    }
}

