/*
Аналитика и данные

<div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/salesFunnel)   2. [Ленты заказов](/openapi/analytics#tag/orderFeed)   3. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/searchQueriesForYourItems)   4. [Истории остатков](/openapi/analytics#tag/stocksReport)   5. [Оценки товара](/openapi/analytics#tag/itemRating)   6. [Аналитики продавца в формате CSV](/openapi/analytics#tag/sellerAnalyticsCsv)  </div> 

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ItemSearchTextsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemSearchTextsResponse{}

// ItemSearchTextsResponse struct for ItemSearchTextsResponse
type ItemSearchTextsResponse struct {
	// Элементы таблицы
	Items []TableSearchTextItem `json:"items"`
	// Валюта отчёта
	Currency string `json:"currency"`
}

type _ItemSearchTextsResponse ItemSearchTextsResponse

// NewItemSearchTextsResponse instantiates a new ItemSearchTextsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemSearchTextsResponse(items []TableSearchTextItem, currency string) *ItemSearchTextsResponse {
	this := ItemSearchTextsResponse{}
	this.Items = items
	this.Currency = currency
	return &this
}

// NewItemSearchTextsResponseWithDefaults instantiates a new ItemSearchTextsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemSearchTextsResponseWithDefaults() *ItemSearchTextsResponse {
	this := ItemSearchTextsResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *ItemSearchTextsResponse) GetItems() []TableSearchTextItem {
	if o == nil {
		var ret []TableSearchTextItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ItemSearchTextsResponse) GetItemsOk() ([]TableSearchTextItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ItemSearchTextsResponse) SetItems(v []TableSearchTextItem) {
	o.Items = v
}

// GetCurrency returns the Currency field value
func (o *ItemSearchTextsResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *ItemSearchTextsResponse) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *ItemSearchTextsResponse) SetCurrency(v string) {
	o.Currency = v
}

func (o ItemSearchTextsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemSearchTextsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["currency"] = o.Currency
	return toSerialize, nil
}

func (o *ItemSearchTextsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varItemSearchTextsResponse := _ItemSearchTextsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varItemSearchTextsResponse)

	if err != nil {
		return err
	}

	*o = ItemSearchTextsResponse(varItemSearchTextsResponse)

	return err
}

type NullableItemSearchTextsResponse struct {
	value *ItemSearchTextsResponse
	isSet bool
}

func (v NullableItemSearchTextsResponse) Get() *ItemSearchTextsResponse {
	return v.value
}

func (v *NullableItemSearchTextsResponse) Set(val *ItemSearchTextsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableItemSearchTextsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableItemSearchTextsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemSearchTextsResponse(val *ItemSearchTextsResponse) *NullableItemSearchTextsResponse {
	return &NullableItemSearchTextsResponse{value: val, isSet: true}
}

func (v NullableItemSearchTextsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemSearchTextsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


