/*
Аналитика и данные

<div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TableSizeResponseSizesInnerMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableSizeResponseSizesInnerMetrics{}

// TableSizeResponseSizesInnerMetrics Метрики размера
type TableSizeResponseSizesInnerMetrics struct {
	// Заказы, шт.
	OrdersCount int32 `json:"ordersCount"`
	// Заказы, сумма
	OrdersSum int32 `json:"ordersSum"`
	// Среднее количество заказов в день
	AvgOrders float32 `json:"avgOrders"`
	// Среднее количество заказов по месяцам
	AvgOrdersByMonth []FloatGraphByPeriodItem `json:"avgOrdersByMonth"`
	// Выкупы, шт.
	BuyoutCount int32 `json:"buyoutCount"`
	// Выкупы, сумма
	BuyoutSum int32 `json:"buyoutSum"`
	// Процент выкупа
	BuyoutPercent int32 `json:"buyoutPercent"`
	// Остатки на текущий день, шт.
	StockCount int32 `json:"stockCount"`
	// Стоимость остатков на текущий день
	StockSum int32 `json:"stockSum"`
	SaleRate TableCommonMetricsSaleRate `json:"saleRate"`
	AvgStockTurnover TableCommonMetricsSaleRate `json:"avgStockTurnover"`
	// В пути к клиенту, шт.
	ToClientCount int32 `json:"toClientCount"`
	// В пути от клиента, шт.
	FromClientCount int32 `json:"fromClientCount"`
	OfficeMissingTime TableCommonMetricsSaleRate `json:"officeMissingTime"`
	// Упущенные заказы, шт. Особые случаи:   1. Значение меньше `0` и не равно `-2` — значение не рассчитано   2. Значение `-2` — нулевое значение 
	LostOrdersCount float32 `json:"lostOrdersCount"`
	// Упущенные заказы, сумма. Особые случаи:   1. Значение меньше `0` и не равно `-2` — значение не рассчитано   2. Значение `-2` — нулевое значение 
	LostOrdersSum float32 `json:"lostOrdersSum"`
	// Упущенные выкупы, шт. Особые случаи:   1. Значение меньше `0` и не равно `-2` — значение не рассчитано   2. Значение `-2` — нулевое значение 
	LostBuyoutsCount float32 `json:"lostBuyoutsCount"`
	// Упущенные выкупы, сумма. Особые случаи:   1. Значение меньше `0` и не равно `-2` — значение не рассчитано   2. Значение `-2` — нулевое значение 
	LostBuyoutsSum float32 `json:"lostBuyoutsSum"`
	CurrentPrice TableItemItemStMetricsAllOfCurrentPrice `json:"currentPrice"`
}

type _TableSizeResponseSizesInnerMetrics TableSizeResponseSizesInnerMetrics

// NewTableSizeResponseSizesInnerMetrics instantiates a new TableSizeResponseSizesInnerMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableSizeResponseSizesInnerMetrics(ordersCount int32, ordersSum int32, avgOrders float32, avgOrdersByMonth []FloatGraphByPeriodItem, buyoutCount int32, buyoutSum int32, buyoutPercent int32, stockCount int32, stockSum int32, saleRate TableCommonMetricsSaleRate, avgStockTurnover TableCommonMetricsSaleRate, toClientCount int32, fromClientCount int32, officeMissingTime TableCommonMetricsSaleRate, lostOrdersCount float32, lostOrdersSum float32, lostBuyoutsCount float32, lostBuyoutsSum float32, currentPrice TableItemItemStMetricsAllOfCurrentPrice) *TableSizeResponseSizesInnerMetrics {
	this := TableSizeResponseSizesInnerMetrics{}
	this.OrdersCount = ordersCount
	this.OrdersSum = ordersSum
	this.AvgOrders = avgOrders
	this.AvgOrdersByMonth = avgOrdersByMonth
	this.BuyoutCount = buyoutCount
	this.BuyoutSum = buyoutSum
	this.BuyoutPercent = buyoutPercent
	this.StockCount = stockCount
	this.StockSum = stockSum
	this.SaleRate = saleRate
	this.AvgStockTurnover = avgStockTurnover
	this.ToClientCount = toClientCount
	this.FromClientCount = fromClientCount
	this.OfficeMissingTime = officeMissingTime
	this.LostOrdersCount = lostOrdersCount
	this.LostOrdersSum = lostOrdersSum
	this.LostBuyoutsCount = lostBuyoutsCount
	this.LostBuyoutsSum = lostBuyoutsSum
	this.CurrentPrice = currentPrice
	return &this
}

// NewTableSizeResponseSizesInnerMetricsWithDefaults instantiates a new TableSizeResponseSizesInnerMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableSizeResponseSizesInnerMetricsWithDefaults() *TableSizeResponseSizesInnerMetrics {
	this := TableSizeResponseSizesInnerMetrics{}
	return &this
}

// GetOrdersCount returns the OrdersCount field value
func (o *TableSizeResponseSizesInnerMetrics) GetOrdersCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrdersCount
}

// GetOrdersCountOk returns a tuple with the OrdersCount field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetOrdersCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrdersCount, true
}

// SetOrdersCount sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetOrdersCount(v int32) {
	o.OrdersCount = v
}

// GetOrdersSum returns the OrdersSum field value
func (o *TableSizeResponseSizesInnerMetrics) GetOrdersSum() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrdersSum
}

// GetOrdersSumOk returns a tuple with the OrdersSum field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetOrdersSumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrdersSum, true
}

// SetOrdersSum sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetOrdersSum(v int32) {
	o.OrdersSum = v
}

// GetAvgOrders returns the AvgOrders field value
func (o *TableSizeResponseSizesInnerMetrics) GetAvgOrders() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AvgOrders
}

// GetAvgOrdersOk returns a tuple with the AvgOrders field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetAvgOrdersOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvgOrders, true
}

// SetAvgOrders sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetAvgOrders(v float32) {
	o.AvgOrders = v
}

// GetAvgOrdersByMonth returns the AvgOrdersByMonth field value
func (o *TableSizeResponseSizesInnerMetrics) GetAvgOrdersByMonth() []FloatGraphByPeriodItem {
	if o == nil {
		var ret []FloatGraphByPeriodItem
		return ret
	}

	return o.AvgOrdersByMonth
}

// GetAvgOrdersByMonthOk returns a tuple with the AvgOrdersByMonth field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetAvgOrdersByMonthOk() ([]FloatGraphByPeriodItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvgOrdersByMonth, true
}

// SetAvgOrdersByMonth sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetAvgOrdersByMonth(v []FloatGraphByPeriodItem) {
	o.AvgOrdersByMonth = v
}

// GetBuyoutCount returns the BuyoutCount field value
func (o *TableSizeResponseSizesInnerMetrics) GetBuyoutCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BuyoutCount
}

// GetBuyoutCountOk returns a tuple with the BuyoutCount field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetBuyoutCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuyoutCount, true
}

// SetBuyoutCount sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetBuyoutCount(v int32) {
	o.BuyoutCount = v
}

// GetBuyoutSum returns the BuyoutSum field value
func (o *TableSizeResponseSizesInnerMetrics) GetBuyoutSum() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BuyoutSum
}

// GetBuyoutSumOk returns a tuple with the BuyoutSum field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetBuyoutSumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuyoutSum, true
}

// SetBuyoutSum sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetBuyoutSum(v int32) {
	o.BuyoutSum = v
}

// GetBuyoutPercent returns the BuyoutPercent field value
func (o *TableSizeResponseSizesInnerMetrics) GetBuyoutPercent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BuyoutPercent
}

// GetBuyoutPercentOk returns a tuple with the BuyoutPercent field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetBuyoutPercentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuyoutPercent, true
}

// SetBuyoutPercent sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetBuyoutPercent(v int32) {
	o.BuyoutPercent = v
}

// GetStockCount returns the StockCount field value
func (o *TableSizeResponseSizesInnerMetrics) GetStockCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StockCount
}

// GetStockCountOk returns a tuple with the StockCount field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetStockCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StockCount, true
}

// SetStockCount sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetStockCount(v int32) {
	o.StockCount = v
}

// GetStockSum returns the StockSum field value
func (o *TableSizeResponseSizesInnerMetrics) GetStockSum() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StockSum
}

// GetStockSumOk returns a tuple with the StockSum field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetStockSumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StockSum, true
}

// SetStockSum sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetStockSum(v int32) {
	o.StockSum = v
}

// GetSaleRate returns the SaleRate field value
func (o *TableSizeResponseSizesInnerMetrics) GetSaleRate() TableCommonMetricsSaleRate {
	if o == nil {
		var ret TableCommonMetricsSaleRate
		return ret
	}

	return o.SaleRate
}

// GetSaleRateOk returns a tuple with the SaleRate field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetSaleRateOk() (*TableCommonMetricsSaleRate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SaleRate, true
}

// SetSaleRate sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetSaleRate(v TableCommonMetricsSaleRate) {
	o.SaleRate = v
}

// GetAvgStockTurnover returns the AvgStockTurnover field value
func (o *TableSizeResponseSizesInnerMetrics) GetAvgStockTurnover() TableCommonMetricsSaleRate {
	if o == nil {
		var ret TableCommonMetricsSaleRate
		return ret
	}

	return o.AvgStockTurnover
}

// GetAvgStockTurnoverOk returns a tuple with the AvgStockTurnover field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetAvgStockTurnoverOk() (*TableCommonMetricsSaleRate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvgStockTurnover, true
}

// SetAvgStockTurnover sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetAvgStockTurnover(v TableCommonMetricsSaleRate) {
	o.AvgStockTurnover = v
}

// GetToClientCount returns the ToClientCount field value
func (o *TableSizeResponseSizesInnerMetrics) GetToClientCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ToClientCount
}

// GetToClientCountOk returns a tuple with the ToClientCount field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetToClientCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToClientCount, true
}

// SetToClientCount sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetToClientCount(v int32) {
	o.ToClientCount = v
}

// GetFromClientCount returns the FromClientCount field value
func (o *TableSizeResponseSizesInnerMetrics) GetFromClientCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FromClientCount
}

// GetFromClientCountOk returns a tuple with the FromClientCount field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetFromClientCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromClientCount, true
}

// SetFromClientCount sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetFromClientCount(v int32) {
	o.FromClientCount = v
}

// GetOfficeMissingTime returns the OfficeMissingTime field value
func (o *TableSizeResponseSizesInnerMetrics) GetOfficeMissingTime() TableCommonMetricsSaleRate {
	if o == nil {
		var ret TableCommonMetricsSaleRate
		return ret
	}

	return o.OfficeMissingTime
}

// GetOfficeMissingTimeOk returns a tuple with the OfficeMissingTime field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetOfficeMissingTimeOk() (*TableCommonMetricsSaleRate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfficeMissingTime, true
}

// SetOfficeMissingTime sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetOfficeMissingTime(v TableCommonMetricsSaleRate) {
	o.OfficeMissingTime = v
}

// GetLostOrdersCount returns the LostOrdersCount field value
func (o *TableSizeResponseSizesInnerMetrics) GetLostOrdersCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.LostOrdersCount
}

// GetLostOrdersCountOk returns a tuple with the LostOrdersCount field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetLostOrdersCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LostOrdersCount, true
}

// SetLostOrdersCount sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetLostOrdersCount(v float32) {
	o.LostOrdersCount = v
}

// GetLostOrdersSum returns the LostOrdersSum field value
func (o *TableSizeResponseSizesInnerMetrics) GetLostOrdersSum() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.LostOrdersSum
}

// GetLostOrdersSumOk returns a tuple with the LostOrdersSum field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetLostOrdersSumOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LostOrdersSum, true
}

// SetLostOrdersSum sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetLostOrdersSum(v float32) {
	o.LostOrdersSum = v
}

// GetLostBuyoutsCount returns the LostBuyoutsCount field value
func (o *TableSizeResponseSizesInnerMetrics) GetLostBuyoutsCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.LostBuyoutsCount
}

// GetLostBuyoutsCountOk returns a tuple with the LostBuyoutsCount field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetLostBuyoutsCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LostBuyoutsCount, true
}

// SetLostBuyoutsCount sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetLostBuyoutsCount(v float32) {
	o.LostBuyoutsCount = v
}

// GetLostBuyoutsSum returns the LostBuyoutsSum field value
func (o *TableSizeResponseSizesInnerMetrics) GetLostBuyoutsSum() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.LostBuyoutsSum
}

// GetLostBuyoutsSumOk returns a tuple with the LostBuyoutsSum field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetLostBuyoutsSumOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LostBuyoutsSum, true
}

// SetLostBuyoutsSum sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetLostBuyoutsSum(v float32) {
	o.LostBuyoutsSum = v
}

// GetCurrentPrice returns the CurrentPrice field value
func (o *TableSizeResponseSizesInnerMetrics) GetCurrentPrice() TableItemItemStMetricsAllOfCurrentPrice {
	if o == nil {
		var ret TableItemItemStMetricsAllOfCurrentPrice
		return ret
	}

	return o.CurrentPrice
}

// GetCurrentPriceOk returns a tuple with the CurrentPrice field value
// and a boolean to check if the value has been set.
func (o *TableSizeResponseSizesInnerMetrics) GetCurrentPriceOk() (*TableItemItemStMetricsAllOfCurrentPrice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPrice, true
}

// SetCurrentPrice sets field value
func (o *TableSizeResponseSizesInnerMetrics) SetCurrentPrice(v TableItemItemStMetricsAllOfCurrentPrice) {
	o.CurrentPrice = v
}

func (o TableSizeResponseSizesInnerMetrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableSizeResponseSizesInnerMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ordersCount"] = o.OrdersCount
	toSerialize["ordersSum"] = o.OrdersSum
	toSerialize["avgOrders"] = o.AvgOrders
	toSerialize["avgOrdersByMonth"] = o.AvgOrdersByMonth
	toSerialize["buyoutCount"] = o.BuyoutCount
	toSerialize["buyoutSum"] = o.BuyoutSum
	toSerialize["buyoutPercent"] = o.BuyoutPercent
	toSerialize["stockCount"] = o.StockCount
	toSerialize["stockSum"] = o.StockSum
	toSerialize["saleRate"] = o.SaleRate
	toSerialize["avgStockTurnover"] = o.AvgStockTurnover
	toSerialize["toClientCount"] = o.ToClientCount
	toSerialize["fromClientCount"] = o.FromClientCount
	toSerialize["officeMissingTime"] = o.OfficeMissingTime
	toSerialize["lostOrdersCount"] = o.LostOrdersCount
	toSerialize["lostOrdersSum"] = o.LostOrdersSum
	toSerialize["lostBuyoutsCount"] = o.LostBuyoutsCount
	toSerialize["lostBuyoutsSum"] = o.LostBuyoutsSum
	toSerialize["currentPrice"] = o.CurrentPrice
	return toSerialize, nil
}

func (o *TableSizeResponseSizesInnerMetrics) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ordersCount",
		"ordersSum",
		"avgOrders",
		"avgOrdersByMonth",
		"buyoutCount",
		"buyoutSum",
		"buyoutPercent",
		"stockCount",
		"stockSum",
		"saleRate",
		"avgStockTurnover",
		"toClientCount",
		"fromClientCount",
		"officeMissingTime",
		"lostOrdersCount",
		"lostOrdersSum",
		"lostBuyoutsCount",
		"lostBuyoutsSum",
		"currentPrice",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTableSizeResponseSizesInnerMetrics := _TableSizeResponseSizesInnerMetrics{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTableSizeResponseSizesInnerMetrics)

	if err != nil {
		return err
	}

	*o = TableSizeResponseSizesInnerMetrics(varTableSizeResponseSizesInnerMetrics)

	return err
}

type NullableTableSizeResponseSizesInnerMetrics struct {
	value *TableSizeResponseSizesInnerMetrics
	isSet bool
}

func (v NullableTableSizeResponseSizesInnerMetrics) Get() *TableSizeResponseSizesInnerMetrics {
	return v.value
}

func (v *NullableTableSizeResponseSizesInnerMetrics) Set(val *TableSizeResponseSizesInnerMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableTableSizeResponseSizesInnerMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableTableSizeResponseSizesInnerMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableSizeResponseSizesInnerMetrics(val *TableSizeResponseSizesInnerMetrics) *NullableTableSizeResponseSizesInnerMetrics {
	return &NullableTableSizeResponseSizesInnerMetrics{value: val, isSet: true}
}

func (v NullableTableSizeResponseSizesInnerMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableSizeResponseSizesInnerMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


