/*
Аналитика и данные

<div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/salesFunnel)   2. [Ленты заказов](/openapi/analytics#tag/orderFeed)   3. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/searchQueriesForYourItems)   4. [Истории остатков](/openapi/analytics#tag/stocksReport)   5. [Оценки товара](/openapi/analytics#tag/itemRating)   6. [Аналитики продавца в формате CSV](/openapi/analytics#tag/sellerAnalyticsCsv)  </div> 

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FeedbacksIncreaseItemThreeStar type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeedbacksIncreaseItemThreeStar{}

// FeedbacksIncreaseItemThreeStar Отзывы 3 звезды
type FeedbacksIncreaseItemThreeStar struct {
	// Прирост оценок за период
	Current int32 `json:"current"`
	// Динамика по сравнению с предыдущим периодом, %
	Dynamics *int32 `json:"dynamics,omitempty"`
	// Всего оценок
	Total int32 `json:"total"`
}

type _FeedbacksIncreaseItemThreeStar FeedbacksIncreaseItemThreeStar

// NewFeedbacksIncreaseItemThreeStar instantiates a new FeedbacksIncreaseItemThreeStar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeedbacksIncreaseItemThreeStar(current int32, total int32) *FeedbacksIncreaseItemThreeStar {
	this := FeedbacksIncreaseItemThreeStar{}
	this.Current = current
	this.Total = total
	return &this
}

// NewFeedbacksIncreaseItemThreeStarWithDefaults instantiates a new FeedbacksIncreaseItemThreeStar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeedbacksIncreaseItemThreeStarWithDefaults() *FeedbacksIncreaseItemThreeStar {
	this := FeedbacksIncreaseItemThreeStar{}
	return &this
}

// GetCurrent returns the Current field value
func (o *FeedbacksIncreaseItemThreeStar) GetCurrent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *FeedbacksIncreaseItemThreeStar) GetCurrentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *FeedbacksIncreaseItemThreeStar) SetCurrent(v int32) {
	o.Current = v
}

// GetDynamics returns the Dynamics field value if set, zero value otherwise.
func (o *FeedbacksIncreaseItemThreeStar) GetDynamics() int32 {
	if o == nil || IsNil(o.Dynamics) {
		var ret int32
		return ret
	}
	return *o.Dynamics
}

// GetDynamicsOk returns a tuple with the Dynamics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeedbacksIncreaseItemThreeStar) GetDynamicsOk() (*int32, bool) {
	if o == nil || IsNil(o.Dynamics) {
		return nil, false
	}
	return o.Dynamics, true
}

// HasDynamics returns a boolean if a field has been set.
func (o *FeedbacksIncreaseItemThreeStar) HasDynamics() bool {
	if o != nil && !IsNil(o.Dynamics) {
		return true
	}

	return false
}

// SetDynamics gets a reference to the given int32 and assigns it to the Dynamics field.
func (o *FeedbacksIncreaseItemThreeStar) SetDynamics(v int32) {
	o.Dynamics = &v
}

// GetTotal returns the Total field value
func (o *FeedbacksIncreaseItemThreeStar) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *FeedbacksIncreaseItemThreeStar) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *FeedbacksIncreaseItemThreeStar) SetTotal(v int32) {
	o.Total = v
}

func (o FeedbacksIncreaseItemThreeStar) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeedbacksIncreaseItemThreeStar) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current"] = o.Current
	if !IsNil(o.Dynamics) {
		toSerialize["dynamics"] = o.Dynamics
	}
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *FeedbacksIncreaseItemThreeStar) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFeedbacksIncreaseItemThreeStar := _FeedbacksIncreaseItemThreeStar{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFeedbacksIncreaseItemThreeStar)

	if err != nil {
		return err
	}

	*o = FeedbacksIncreaseItemThreeStar(varFeedbacksIncreaseItemThreeStar)

	return err
}

type NullableFeedbacksIncreaseItemThreeStar struct {
	value *FeedbacksIncreaseItemThreeStar
	isSet bool
}

func (v NullableFeedbacksIncreaseItemThreeStar) Get() *FeedbacksIncreaseItemThreeStar {
	return v.value
}

func (v *NullableFeedbacksIncreaseItemThreeStar) Set(val *FeedbacksIncreaseItemThreeStar) {
	v.value = val
	v.isSet = true
}

func (v NullableFeedbacksIncreaseItemThreeStar) IsSet() bool {
	return v.isSet
}

func (v *NullableFeedbacksIncreaseItemThreeStar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeedbacksIncreaseItemThreeStar(val *FeedbacksIncreaseItemThreeStar) *NullableFeedbacksIncreaseItemThreeStar {
	return &NullableFeedbacksIncreaseItemThreeStar{value: val, isSet: true}
}

func (v NullableFeedbacksIncreaseItemThreeStar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeedbacksIncreaseItemThreeStar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


