/*
Аналитика и данные

<div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ItemRatingRequestV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemRatingRequestV1{}

// ItemRatingRequestV1 Параметры запроса
type ItemRatingRequestV1 struct {
	CurrentPeriod PeriodItemRating `json:"currentPeriod"`
	PastPeriod *PastPeriodItemRating `json:"pastPeriod,omitempty"`
	// Список артикулов WB для фильтрации
	NmIds []int32 `json:"nmIds,omitempty"`
	// Список ID предметов для фильтрации
	SubjectIds []int32 `json:"subjectIds,omitempty"`
	// Список брендов для фильтрации
	BrandNames []string `json:"brandNames,omitempty"`
	// Список ID ярлыков для фильтрации
	TagIds []int64 `json:"tagIds,omitempty"`
	// Не учитывать товары без продаж
	IsNotIncludeNMsWithoutSales *bool `json:"isNotIncludeNMsWithoutSales,omitempty"`
	OrderBy OrderByItemRating `json:"orderBy"`
	// Количество товаров в ответе
	Limit *int32 `json:"limit,omitempty"`
	// Сколько элементов пропустить. Например, для значения `10` ответ начнётся с 11 элемента
	Offset int32 `json:"offset"`
}

type _ItemRatingRequestV1 ItemRatingRequestV1

// NewItemRatingRequestV1 instantiates a new ItemRatingRequestV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemRatingRequestV1(currentPeriod PeriodItemRating, orderBy OrderByItemRating, offset int32) *ItemRatingRequestV1 {
	this := ItemRatingRequestV1{}
	this.CurrentPeriod = currentPeriod
	var isNotIncludeNMsWithoutSales bool = false
	this.IsNotIncludeNMsWithoutSales = &isNotIncludeNMsWithoutSales
	this.OrderBy = orderBy
	var limit int32 = 100
	this.Limit = &limit
	this.Offset = offset
	return &this
}

// NewItemRatingRequestV1WithDefaults instantiates a new ItemRatingRequestV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemRatingRequestV1WithDefaults() *ItemRatingRequestV1 {
	this := ItemRatingRequestV1{}
	var isNotIncludeNMsWithoutSales bool = false
	this.IsNotIncludeNMsWithoutSales = &isNotIncludeNMsWithoutSales
	var limit int32 = 100
	this.Limit = &limit
	return &this
}

// GetCurrentPeriod returns the CurrentPeriod field value
func (o *ItemRatingRequestV1) GetCurrentPeriod() PeriodItemRating {
	if o == nil {
		var ret PeriodItemRating
		return ret
	}

	return o.CurrentPeriod
}

// GetCurrentPeriodOk returns a tuple with the CurrentPeriod field value
// and a boolean to check if the value has been set.
func (o *ItemRatingRequestV1) GetCurrentPeriodOk() (*PeriodItemRating, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPeriod, true
}

// SetCurrentPeriod sets field value
func (o *ItemRatingRequestV1) SetCurrentPeriod(v PeriodItemRating) {
	o.CurrentPeriod = v
}

// GetPastPeriod returns the PastPeriod field value if set, zero value otherwise.
func (o *ItemRatingRequestV1) GetPastPeriod() PastPeriodItemRating {
	if o == nil || IsNil(o.PastPeriod) {
		var ret PastPeriodItemRating
		return ret
	}
	return *o.PastPeriod
}

// GetPastPeriodOk returns a tuple with the PastPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemRatingRequestV1) GetPastPeriodOk() (*PastPeriodItemRating, bool) {
	if o == nil || IsNil(o.PastPeriod) {
		return nil, false
	}
	return o.PastPeriod, true
}

// HasPastPeriod returns a boolean if a field has been set.
func (o *ItemRatingRequestV1) HasPastPeriod() bool {
	if o != nil && !IsNil(o.PastPeriod) {
		return true
	}

	return false
}

// SetPastPeriod gets a reference to the given PastPeriodItemRating and assigns it to the PastPeriod field.
func (o *ItemRatingRequestV1) SetPastPeriod(v PastPeriodItemRating) {
	o.PastPeriod = &v
}

// GetNmIds returns the NmIds field value if set, zero value otherwise.
func (o *ItemRatingRequestV1) GetNmIds() []int32 {
	if o == nil || IsNil(o.NmIds) {
		var ret []int32
		return ret
	}
	return o.NmIds
}

// GetNmIdsOk returns a tuple with the NmIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemRatingRequestV1) GetNmIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.NmIds) {
		return nil, false
	}
	return o.NmIds, true
}

// HasNmIds returns a boolean if a field has been set.
func (o *ItemRatingRequestV1) HasNmIds() bool {
	if o != nil && !IsNil(o.NmIds) {
		return true
	}

	return false
}

// SetNmIds gets a reference to the given []int32 and assigns it to the NmIds field.
func (o *ItemRatingRequestV1) SetNmIds(v []int32) {
	o.NmIds = v
}

// GetSubjectIds returns the SubjectIds field value if set, zero value otherwise.
func (o *ItemRatingRequestV1) GetSubjectIds() []int32 {
	if o == nil || IsNil(o.SubjectIds) {
		var ret []int32
		return ret
	}
	return o.SubjectIds
}

// GetSubjectIdsOk returns a tuple with the SubjectIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemRatingRequestV1) GetSubjectIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.SubjectIds) {
		return nil, false
	}
	return o.SubjectIds, true
}

// HasSubjectIds returns a boolean if a field has been set.
func (o *ItemRatingRequestV1) HasSubjectIds() bool {
	if o != nil && !IsNil(o.SubjectIds) {
		return true
	}

	return false
}

// SetSubjectIds gets a reference to the given []int32 and assigns it to the SubjectIds field.
func (o *ItemRatingRequestV1) SetSubjectIds(v []int32) {
	o.SubjectIds = v
}

// GetBrandNames returns the BrandNames field value if set, zero value otherwise.
func (o *ItemRatingRequestV1) GetBrandNames() []string {
	if o == nil || IsNil(o.BrandNames) {
		var ret []string
		return ret
	}
	return o.BrandNames
}

// GetBrandNamesOk returns a tuple with the BrandNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemRatingRequestV1) GetBrandNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.BrandNames) {
		return nil, false
	}
	return o.BrandNames, true
}

// HasBrandNames returns a boolean if a field has been set.
func (o *ItemRatingRequestV1) HasBrandNames() bool {
	if o != nil && !IsNil(o.BrandNames) {
		return true
	}

	return false
}

// SetBrandNames gets a reference to the given []string and assigns it to the BrandNames field.
func (o *ItemRatingRequestV1) SetBrandNames(v []string) {
	o.BrandNames = v
}

// GetTagIds returns the TagIds field value if set, zero value otherwise.
func (o *ItemRatingRequestV1) GetTagIds() []int64 {
	if o == nil || IsNil(o.TagIds) {
		var ret []int64
		return ret
	}
	return o.TagIds
}

// GetTagIdsOk returns a tuple with the TagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemRatingRequestV1) GetTagIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.TagIds) {
		return nil, false
	}
	return o.TagIds, true
}

// HasTagIds returns a boolean if a field has been set.
func (o *ItemRatingRequestV1) HasTagIds() bool {
	if o != nil && !IsNil(o.TagIds) {
		return true
	}

	return false
}

// SetTagIds gets a reference to the given []int64 and assigns it to the TagIds field.
func (o *ItemRatingRequestV1) SetTagIds(v []int64) {
	o.TagIds = v
}

// GetIsNotIncludeNMsWithoutSales returns the IsNotIncludeNMsWithoutSales field value if set, zero value otherwise.
func (o *ItemRatingRequestV1) GetIsNotIncludeNMsWithoutSales() bool {
	if o == nil || IsNil(o.IsNotIncludeNMsWithoutSales) {
		var ret bool
		return ret
	}
	return *o.IsNotIncludeNMsWithoutSales
}

// GetIsNotIncludeNMsWithoutSalesOk returns a tuple with the IsNotIncludeNMsWithoutSales field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemRatingRequestV1) GetIsNotIncludeNMsWithoutSalesOk() (*bool, bool) {
	if o == nil || IsNil(o.IsNotIncludeNMsWithoutSales) {
		return nil, false
	}
	return o.IsNotIncludeNMsWithoutSales, true
}

// HasIsNotIncludeNMsWithoutSales returns a boolean if a field has been set.
func (o *ItemRatingRequestV1) HasIsNotIncludeNMsWithoutSales() bool {
	if o != nil && !IsNil(o.IsNotIncludeNMsWithoutSales) {
		return true
	}

	return false
}

// SetIsNotIncludeNMsWithoutSales gets a reference to the given bool and assigns it to the IsNotIncludeNMsWithoutSales field.
func (o *ItemRatingRequestV1) SetIsNotIncludeNMsWithoutSales(v bool) {
	o.IsNotIncludeNMsWithoutSales = &v
}

// GetOrderBy returns the OrderBy field value
func (o *ItemRatingRequestV1) GetOrderBy() OrderByItemRating {
	if o == nil {
		var ret OrderByItemRating
		return ret
	}

	return o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value
// and a boolean to check if the value has been set.
func (o *ItemRatingRequestV1) GetOrderByOk() (*OrderByItemRating, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderBy, true
}

// SetOrderBy sets field value
func (o *ItemRatingRequestV1) SetOrderBy(v OrderByItemRating) {
	o.OrderBy = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ItemRatingRequestV1) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemRatingRequestV1) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ItemRatingRequestV1) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ItemRatingRequestV1) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value
func (o *ItemRatingRequestV1) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *ItemRatingRequestV1) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *ItemRatingRequestV1) SetOffset(v int32) {
	o.Offset = v
}

func (o ItemRatingRequestV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemRatingRequestV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currentPeriod"] = o.CurrentPeriod
	if !IsNil(o.PastPeriod) {
		toSerialize["pastPeriod"] = o.PastPeriod
	}
	if !IsNil(o.NmIds) {
		toSerialize["nmIds"] = o.NmIds
	}
	if !IsNil(o.SubjectIds) {
		toSerialize["subjectIds"] = o.SubjectIds
	}
	if !IsNil(o.BrandNames) {
		toSerialize["brandNames"] = o.BrandNames
	}
	if !IsNil(o.TagIds) {
		toSerialize["tagIds"] = o.TagIds
	}
	if !IsNil(o.IsNotIncludeNMsWithoutSales) {
		toSerialize["isNotIncludeNMsWithoutSales"] = o.IsNotIncludeNMsWithoutSales
	}
	toSerialize["orderBy"] = o.OrderBy
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

func (o *ItemRatingRequestV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currentPeriod",
		"orderBy",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varItemRatingRequestV1 := _ItemRatingRequestV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varItemRatingRequestV1)

	if err != nil {
		return err
	}

	*o = ItemRatingRequestV1(varItemRatingRequestV1)

	return err
}

type NullableItemRatingRequestV1 struct {
	value *ItemRatingRequestV1
	isSet bool
}

func (v NullableItemRatingRequestV1) Get() *ItemRatingRequestV1 {
	return v.value
}

func (v *NullableItemRatingRequestV1) Set(val *ItemRatingRequestV1) {
	v.value = val
	v.isSet = true
}

func (v NullableItemRatingRequestV1) IsSet() bool {
	return v.isSet
}

func (v *NullableItemRatingRequestV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemRatingRequestV1(val *ItemRatingRequestV1) *NullableItemRatingRequestV1 {
	return &NullableItemRatingRequestV1{value: val, isSet: true}
}

func (v NullableItemRatingRequestV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemRatingRequestV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


