/*
Аналитика и данные

<div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/salesFunnel)   2. [Ленты заказов](/openapi/analytics#tag/orderFeed)   3. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/searchQueriesForYourItems)   4. [Истории остатков](/openapi/analytics#tag/stocksReport)   5. [Оценки товара](/openapi/analytics#tag/itemRating)   6. [Аналитики продавца в формате CSV](/openapi/analytics#tag/sellerAnalyticsCsv)  </div> 

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TableSearchTextItemAllOfAddToCart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableSearchTextItemAllOfAddToCart{}

// TableSearchTextItemAllOfAddToCart Сколько раз товар из поиска добавили в корзину
type TableSearchTextItemAllOfAddToCart struct {
	// Текущее количество
	Current int32 `json:"current"`
	// Динамика по сравнению с предыдущим периодом, %
	Dynamics *int32 `json:"dynamics,omitempty"`
	// Процент, на который показатель добавлений в корзину выше, чем у карточек других продавцов по поисковому запросу
	Percentile int32 `json:"percentile"`
}

type _TableSearchTextItemAllOfAddToCart TableSearchTextItemAllOfAddToCart

// NewTableSearchTextItemAllOfAddToCart instantiates a new TableSearchTextItemAllOfAddToCart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableSearchTextItemAllOfAddToCart(current int32, percentile int32) *TableSearchTextItemAllOfAddToCart {
	this := TableSearchTextItemAllOfAddToCart{}
	this.Current = current
	this.Percentile = percentile
	return &this
}

// NewTableSearchTextItemAllOfAddToCartWithDefaults instantiates a new TableSearchTextItemAllOfAddToCart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableSearchTextItemAllOfAddToCartWithDefaults() *TableSearchTextItemAllOfAddToCart {
	this := TableSearchTextItemAllOfAddToCart{}
	return &this
}

// GetCurrent returns the Current field value
func (o *TableSearchTextItemAllOfAddToCart) GetCurrent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *TableSearchTextItemAllOfAddToCart) GetCurrentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *TableSearchTextItemAllOfAddToCart) SetCurrent(v int32) {
	o.Current = v
}

// GetDynamics returns the Dynamics field value if set, zero value otherwise.
func (o *TableSearchTextItemAllOfAddToCart) GetDynamics() int32 {
	if o == nil || IsNil(o.Dynamics) {
		var ret int32
		return ret
	}
	return *o.Dynamics
}

// GetDynamicsOk returns a tuple with the Dynamics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableSearchTextItemAllOfAddToCart) GetDynamicsOk() (*int32, bool) {
	if o == nil || IsNil(o.Dynamics) {
		return nil, false
	}
	return o.Dynamics, true
}

// HasDynamics returns a boolean if a field has been set.
func (o *TableSearchTextItemAllOfAddToCart) HasDynamics() bool {
	if o != nil && !IsNil(o.Dynamics) {
		return true
	}

	return false
}

// SetDynamics gets a reference to the given int32 and assigns it to the Dynamics field.
func (o *TableSearchTextItemAllOfAddToCart) SetDynamics(v int32) {
	o.Dynamics = &v
}

// GetPercentile returns the Percentile field value
func (o *TableSearchTextItemAllOfAddToCart) GetPercentile() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Percentile
}

// GetPercentileOk returns a tuple with the Percentile field value
// and a boolean to check if the value has been set.
func (o *TableSearchTextItemAllOfAddToCart) GetPercentileOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percentile, true
}

// SetPercentile sets field value
func (o *TableSearchTextItemAllOfAddToCart) SetPercentile(v int32) {
	o.Percentile = v
}

func (o TableSearchTextItemAllOfAddToCart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableSearchTextItemAllOfAddToCart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current"] = o.Current
	if !IsNil(o.Dynamics) {
		toSerialize["dynamics"] = o.Dynamics
	}
	toSerialize["percentile"] = o.Percentile
	return toSerialize, nil
}

func (o *TableSearchTextItemAllOfAddToCart) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current",
		"percentile",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTableSearchTextItemAllOfAddToCart := _TableSearchTextItemAllOfAddToCart{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTableSearchTextItemAllOfAddToCart)

	if err != nil {
		return err
	}

	*o = TableSearchTextItemAllOfAddToCart(varTableSearchTextItemAllOfAddToCart)

	return err
}

type NullableTableSearchTextItemAllOfAddToCart struct {
	value *TableSearchTextItemAllOfAddToCart
	isSet bool
}

func (v NullableTableSearchTextItemAllOfAddToCart) Get() *TableSearchTextItemAllOfAddToCart {
	return v.value
}

func (v *NullableTableSearchTextItemAllOfAddToCart) Set(val *TableSearchTextItemAllOfAddToCart) {
	v.value = val
	v.isSet = true
}

func (v NullableTableSearchTextItemAllOfAddToCart) IsSet() bool {
	return v.isSet
}

func (v *NullableTableSearchTextItemAllOfAddToCart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableSearchTextItemAllOfAddToCart(val *TableSearchTextItemAllOfAddToCart) *NullableTableSearchTextItemAllOfAddToCart {
	return &NullableTableSearchTextItemAllOfAddToCart{value: val, isSet: true}
}

func (v NullableTableSearchTextItemAllOfAddToCart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableSearchTextItemAllOfAddToCart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


