/*
Заказы DBW

<div class=\"api-block\">  С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/dbwAssemblyOrders), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/dbwLabelIdentifiers) сборочных заданий  </div>  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-036a-7721-98e8-bed5f1a4f72d/zakazy-dbw\">инструкции</a> по работе с <strong>заказами DBW</strong> </div> 

API version: ordersdbw
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orders_dbw

import (
	"encoding/json"
)

// checks if the ApiOrdersRequestV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiOrdersRequestV2{}

// ApiOrdersRequestV2 struct for ApiOrdersRequestV2
type ApiOrdersRequestV2 struct {
	// Список ID сборочных заданий
	OrdersIds []int32 `json:"ordersIds,omitempty"`
}

// NewApiOrdersRequestV2 instantiates a new ApiOrdersRequestV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiOrdersRequestV2() *ApiOrdersRequestV2 {
	this := ApiOrdersRequestV2{}
	return &this
}

// NewApiOrdersRequestV2WithDefaults instantiates a new ApiOrdersRequestV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiOrdersRequestV2WithDefaults() *ApiOrdersRequestV2 {
	this := ApiOrdersRequestV2{}
	return &this
}

// GetOrdersIds returns the OrdersIds field value if set, zero value otherwise.
func (o *ApiOrdersRequestV2) GetOrdersIds() []int32 {
	if o == nil || IsNil(o.OrdersIds) {
		var ret []int32
		return ret
	}
	return o.OrdersIds
}

// GetOrdersIdsOk returns a tuple with the OrdersIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiOrdersRequestV2) GetOrdersIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.OrdersIds) {
		return nil, false
	}
	return o.OrdersIds, true
}

// HasOrdersIds returns a boolean if a field has been set.
func (o *ApiOrdersRequestV2) HasOrdersIds() bool {
	if o != nil && !IsNil(o.OrdersIds) {
		return true
	}

	return false
}

// SetOrdersIds gets a reference to the given []int32 and assigns it to the OrdersIds field.
func (o *ApiOrdersRequestV2) SetOrdersIds(v []int32) {
	o.OrdersIds = v
}

func (o ApiOrdersRequestV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiOrdersRequestV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrdersIds) {
		toSerialize["ordersIds"] = o.OrdersIds
	}
	return toSerialize, nil
}

type NullableApiOrdersRequestV2 struct {
	value *ApiOrdersRequestV2
	isSet bool
}

func (v NullableApiOrdersRequestV2) Get() *ApiOrdersRequestV2 {
	return v.value
}

func (v *NullableApiOrdersRequestV2) Set(val *ApiOrdersRequestV2) {
	v.value = val
	v.isSet = true
}

func (v NullableApiOrdersRequestV2) IsSet() bool {
	return v.isSet
}

func (v *NullableApiOrdersRequestV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiOrdersRequestV2(val *ApiOrdersRequestV2) *NullableApiOrdersRequestV2 {
	return &NullableApiOrdersRequestV2{value: val, isSet: true}
}

func (v NullableApiOrdersRequestV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiOrdersRequestV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


