/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * <div class=\"api-block\">  С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [идентификаторы маркировки](/openapi/orders-fbs#tag/fbsLabelIdentifiers) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  Вы можете протестировать методы заказов FBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-FBS) для эмуляции действий пользователя  </div>  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-0771-7571-aea9-11d5b597f34c/zakazy-fbs\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>  <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner
 */
export interface ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    /**
     * ID сборочного задания
     */
    orderId?: number;
    /**
     * Статус генерации стикера:
     *   - `awaitingTrackNumber` — стикер не готов. Ожидается трек-номер от перевозчика.
     *   - `ready` — стикер готов
     * 
     */
    status?: ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerStatusEnum;
    /**
     * Трек-номер в стикере для отслеживания сборочного задания
     */
    parcelId?: string;
    /**
     * Стикер в формате PDF, кодировка base64
     */
    file?: string;
    /**
     * Первая часть ID стикера для печати подписи
     */
    partA?: string;
    /**
     * Вторая часть ID стикера для печати подписи
     */
    partB?: string;
    /**
     * Закодированное значение стикера
     */
    barcode?: string;
}


/**
 * @export
 */
export const ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerStatusEnum = {
    AwaitingTrackNumber: 'awaitingTrackNumber',
    Ready: 'ready'
} as const;
export type ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerStatusEnum = typeof ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerStatusEnum[keyof typeof ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerStatusEnum];


/**
 * Check if a given object implements the ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner interface.
 */
export function instanceOfApiV3OrdersStickersCrossBorderPost200ResponseStickersInner(value: object): value is ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    return true;
}

export function ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerFromJSON(json: any): ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    return ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerFromJSONTyped(json, false);
}

export function ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'status': json['status'] == null ? undefined : json['status'],
        'parcelId': json['parcelId'] == null ? undefined : json['parcelId'],
        'file': json['file'] == null ? undefined : json['file'],
        'partA': json['partA'] == null ? undefined : json['partA'],
        'partB': json['partB'] == null ? undefined : json['partB'],
        'barcode': json['barcode'] == null ? undefined : json['barcode'],
    };
}

export function ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerToJSON(json: any): ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    return ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerToJSONTyped(json, false);
}

export function ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerToJSONTyped(value?: ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'status': value['status'],
        'parcelId': value['parcelId'],
        'file': value['file'],
        'partA': value['partA'],
        'partB': value['partB'],
        'barcode': value['barcode'],
    };
}

