/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * <div class=\"api-block\">  С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [идентификаторы маркировки](/openapi/orders-fbs#tag/fbsLabelIdentifiers) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  Вы можете протестировать методы заказов FBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-FBS) для эмуляции действий пользователя  </div>  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-0771-7571-aea9-11d5b597f34c/zakazy-fbs\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>  <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Опции заказа
 * @export
 * @interface OrderOptions
 */
export interface OrderOptions {
    /**
     * Признак B2B-продажи:
     *   - `false` — не B2B-продажа
     *   - `true` — B2B-продажа
     * 
     * @type {boolean}
     * @memberof OrderOptions
     */
    isB2B?: boolean;
}

/**
 * Check if a given object implements the OrderOptions interface.
 */
export function instanceOfOrderOptions(value: object): value is OrderOptions {
    return true;
}

export function OrderOptionsFromJSON(json: any): OrderOptions {
    return OrderOptionsFromJSONTyped(json, false);
}

export function OrderOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'isB2B': json['isB2B'] == null ? undefined : json['isB2B'],
    };
}

export function OrderOptionsToJSON(json: any): OrderOptions {
    return OrderOptionsToJSONTyped(json, false);
}

export function OrderOptionsToJSONTyped(value?: OrderOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isB2B': value['isB2B'],
    };
}

