/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * <div class=\"api-block\">  С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [идентификаторы маркировки](/openapi/orders-fbs#tag/fbsLabelIdentifiers) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  Вы можете протестировать методы заказов FBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-FBS) для эмуляции действий пользователя  </div>   <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-0771-7571-aea9-11d5b597f34c/zakazy-fbs\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>   <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReplyBatchError } from './ReplyBatchError';
import {
    ReplyBatchErrorFromJSON,
    ReplyBatchErrorFromJSONTyped,
    ReplyBatchErrorToJSON,
    ReplyBatchErrorToJSONTyped,
} from './ReplyBatchError';

/**
 * Результат обработки запроса для одной поставки
 * @export
 * @interface UpdatedSupplies
 */
export interface UpdatedSupplies {
    /**
     * 
     */
    error?: ReplyBatchError;
    /**
     * Успешна ли обработка запроса для данной поставки. Может быть только `true`
     */
    success?: boolean;
    /**
     * ID поставки
     */
    supplyId: string;
}

/**
 * Check if a given object implements the UpdatedSupplies interface.
 */
export function instanceOfUpdatedSupplies(value: object): value is UpdatedSupplies {
    if (!('supplyId' in value) || value['supplyId'] === undefined) return false;
    return true;
}

export function UpdatedSuppliesFromJSON(json: any): UpdatedSupplies {
    return UpdatedSuppliesFromJSONTyped(json, false);
}

export function UpdatedSuppliesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatedSupplies {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : ReplyBatchErrorFromJSON(json['error']),
        'success': json['success'] == null ? undefined : json['success'],
        'supplyId': json['supplyId'],
    };
}

export function UpdatedSuppliesToJSON(json: any): UpdatedSupplies {
    return UpdatedSuppliesToJSONTyped(json, false);
}

export function UpdatedSuppliesToJSONTyped(value?: UpdatedSupplies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': ReplyBatchErrorToJSON(value['error']),
        'success': value['success'],
        'supplyId': value['supplyId'],
    };
}

