/* tslint:disable */
/* eslint-disable */
/**
 * Документы и бухгалтерия
 * <div class=\"description_important\">   Узнать больше о документах и бухгалтерии можно в <a href=\"https://seller.wildberries.ru/instructions/category/ba929b64-1f89-4426-82d7-ce998ee552bd?goBackOption=prevRoute&categoryId=3c971375-9939-45e8-ab82-376019be8942\">справочном центре</a> </div>  <div class=\"api-block\">  Просмотр [баланса](/openapi/financial-reports-and-accounting#tag/balance), [финансовых отчётов](/openapi/financial-reports-and-accounting#tag/financialReports) и [документов](/openapi/financial-reports-and-accounting#tag/documents) продавца.  </div> 
 *
 * The version of the OpenAPI document: finances
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Детализации к отчётам об издержках на приём платежей
 * @export
 * @interface AcquiringReportsDetailedRes
 */
export interface AcquiringReportsDetailedRes {
    /**
     * ID строки
     * @type {number}
     * @memberof AcquiringReportsDetailedRes
     */
    rrdId: number;
    /**
     * ID отчёта
     * @type {number}
     * @memberof AcquiringReportsDetailedRes
     */
    reportId: number;
    /**
     * Дата операции
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    acqDate: string;
    /**
     * Наименование банка-эквайера
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    acquiringBank: string;
    /**
     * ИНН
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    tin: string;
    /**
     * КПП
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    taxRegistrationReasonCode: string;
    /**
     * Дата продажи
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    saleDate: string;
    /**
     * ID заказа.<br>В ответах методов сборочных заданий [FBS](./orders-fbs#tag/Sborochnye-zadaniya-FBS), [DBW](./orders-dbw#tag/dbwAssemblyOrders), [DBS](./orders-dbs#tag/dbsAssemblyOrders) и [Самовывоз](./in-store-pickup#tag/inStorePickupAssemblyOrders) `srid` равен `rid`
     * 
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    srid: string;
    /**
     * Тип документа
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    docTypeName: string;
    /**
     * Артикул WB
     * @type {number}
     * @memberof AcquiringReportsDetailedRes
     */
    nmId: number;
    /**
     * Вайлдберриз реализовал Товар (Пр)
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    retailAmount: string;
    /**
     * Размер комиссии за эквайринг, в том числе НДС
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    acquiringFee: string;
    /**
     * Сумма НДС
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    acquiringFeeVat: string;
    /**
     * Номер счёта-фактуры
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    invoiceNumber: string;
    /**
     * Дата счёта-фактуры
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    invoiceDate: string;
    /**
     * Штрихкод
     * @type {number}
     * @memberof AcquiringReportsDetailedRes
     */
    shkId: number;
    /**
     * Валюта отчёта
     * @type {string}
     * @memberof AcquiringReportsDetailedRes
     */
    currency: string;
}

/**
 * Check if a given object implements the AcquiringReportsDetailedRes interface.
 */
export function instanceOfAcquiringReportsDetailedRes(value: object): value is AcquiringReportsDetailedRes {
    if (!('rrdId' in value) || value['rrdId'] === undefined) return false;
    if (!('reportId' in value) || value['reportId'] === undefined) return false;
    if (!('acqDate' in value) || value['acqDate'] === undefined) return false;
    if (!('acquiringBank' in value) || value['acquiringBank'] === undefined) return false;
    if (!('tin' in value) || value['tin'] === undefined) return false;
    if (!('taxRegistrationReasonCode' in value) || value['taxRegistrationReasonCode'] === undefined) return false;
    if (!('saleDate' in value) || value['saleDate'] === undefined) return false;
    if (!('srid' in value) || value['srid'] === undefined) return false;
    if (!('docTypeName' in value) || value['docTypeName'] === undefined) return false;
    if (!('nmId' in value) || value['nmId'] === undefined) return false;
    if (!('retailAmount' in value) || value['retailAmount'] === undefined) return false;
    if (!('acquiringFee' in value) || value['acquiringFee'] === undefined) return false;
    if (!('acquiringFeeVat' in value) || value['acquiringFeeVat'] === undefined) return false;
    if (!('invoiceNumber' in value) || value['invoiceNumber'] === undefined) return false;
    if (!('invoiceDate' in value) || value['invoiceDate'] === undefined) return false;
    if (!('shkId' in value) || value['shkId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function AcquiringReportsDetailedResFromJSON(json: any): AcquiringReportsDetailedRes {
    return AcquiringReportsDetailedResFromJSONTyped(json, false);
}

export function AcquiringReportsDetailedResFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcquiringReportsDetailedRes {
    if (json == null) {
        return json;
    }
    return {
        
        'rrdId': json['rrdId'],
        'reportId': json['reportId'],
        'acqDate': json['acqDate'],
        'acquiringBank': json['acquiringBank'],
        'tin': json['tin'],
        'taxRegistrationReasonCode': json['taxRegistrationReasonCode'],
        'saleDate': json['saleDate'],
        'srid': json['srid'],
        'docTypeName': json['docTypeName'],
        'nmId': json['nmId'],
        'retailAmount': json['retailAmount'],
        'acquiringFee': json['acquiringFee'],
        'acquiringFeeVat': json['acquiringFeeVat'],
        'invoiceNumber': json['invoiceNumber'],
        'invoiceDate': json['invoiceDate'],
        'shkId': json['shkId'],
        'currency': json['currency'],
    };
}

export function AcquiringReportsDetailedResToJSON(json: any): AcquiringReportsDetailedRes {
    return AcquiringReportsDetailedResToJSONTyped(json, false);
}

export function AcquiringReportsDetailedResToJSONTyped(value?: AcquiringReportsDetailedRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rrdId': value['rrdId'],
        'reportId': value['reportId'],
        'acqDate': value['acqDate'],
        'acquiringBank': value['acquiringBank'],
        'tin': value['tin'],
        'taxRegistrationReasonCode': value['taxRegistrationReasonCode'],
        'saleDate': value['saleDate'],
        'srid': value['srid'],
        'docTypeName': value['docTypeName'],
        'nmId': value['nmId'],
        'retailAmount': value['retailAmount'],
        'acquiringFee': value['acquiringFee'],
        'acquiringFeeVat': value['acquiringFeeVat'],
        'invoiceNumber': value['invoiceNumber'],
        'invoiceDate': value['invoiceDate'],
        'shkId': value['shkId'],
        'currency': value['currency'],
    };
}

