/*
Работа с товарами

<div class=\"api-block\">  С помощью методов этого раздела вы можете:   - [создавать](/openapi/work-with-products#tag/listingItems) и [редактировать](/openapi/work-with-products#tag/listings) карточки товаров   - получать [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/categoriesSubcategoriesAndCharacteristics)   - загружать [медиафайлы](/openapi/work-with-products#tag/mediaFiles) в карточки товаров   - настраивать [ярлыки](/openapi/work-with-products#tag/labels) для поиска товаров   - работать с [рекомендациями](/openapi/work-with-products#tag/recommendations) для товаров   - устанавливать [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца  Вы можете протестировать методы работы с товарами в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Rabota-s-tovarami) для управления карточками товаров  </div>   <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami\">инструкции</a> по <strong>работе с товарами</strong> </div>  

API version: items
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package items

import (
	"encoding/json"
)

// checks if the QuarantineItems type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuarantineItems{}

// QuarantineItems struct for QuarantineItems
type QuarantineItems struct {
	// Артикул WB
	NmID *int32 `json:"nmID,omitempty"`
	// Не используется
	SizeID NullableInt32 `json:"sizeID,omitempty"`
	// Не используется
	TechSizeName *string `json:"techSizeName,omitempty"`
	// Валюта по стандарту ISO 4217
	CurrencyIsoCode4217 *string `json:"currencyIsoCode4217,omitempty"`
	// Новая цена продавца до скидки
	NewPrice NullableFloat32 `json:"newPrice,omitempty"`
	// Текущая цена продавца до скидки
	OldPrice *float32 `json:"oldPrice,omitempty"`
	// Новая скидка продавца, %
	NewDiscount NullableInt32 `json:"newDiscount,omitempty"`
	// Текущая скидка продавца, %
	OldDiscount *int32 `json:"oldDiscount,omitempty"`
	// Разница: `newPrice` * (1 - `newDiscount` / 100) - `oldPrice` * (1 - `oldDiscount` / 100)
	PriceDiff *float32 `json:"priceDiff,omitempty"`
}

// NewQuarantineItems instantiates a new QuarantineItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuarantineItems() *QuarantineItems {
	this := QuarantineItems{}
	return &this
}

// NewQuarantineItemsWithDefaults instantiates a new QuarantineItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuarantineItemsWithDefaults() *QuarantineItems {
	this := QuarantineItems{}
	return &this
}

// GetNmID returns the NmID field value if set, zero value otherwise.
func (o *QuarantineItems) GetNmID() int32 {
	if o == nil || IsNil(o.NmID) {
		var ret int32
		return ret
	}
	return *o.NmID
}

// GetNmIDOk returns a tuple with the NmID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuarantineItems) GetNmIDOk() (*int32, bool) {
	if o == nil || IsNil(o.NmID) {
		return nil, false
	}
	return o.NmID, true
}

// HasNmID returns a boolean if a field has been set.
func (o *QuarantineItems) HasNmID() bool {
	if o != nil && !IsNil(o.NmID) {
		return true
	}

	return false
}

// SetNmID gets a reference to the given int32 and assigns it to the NmID field.
func (o *QuarantineItems) SetNmID(v int32) {
	o.NmID = &v
}

// GetSizeID returns the SizeID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QuarantineItems) GetSizeID() int32 {
	if o == nil || IsNil(o.SizeID.Get()) {
		var ret int32
		return ret
	}
	return *o.SizeID.Get()
}

// GetSizeIDOk returns a tuple with the SizeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuarantineItems) GetSizeIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SizeID.Get(), o.SizeID.IsSet()
}

// HasSizeID returns a boolean if a field has been set.
func (o *QuarantineItems) HasSizeID() bool {
	if o != nil && o.SizeID.IsSet() {
		return true
	}

	return false
}

// SetSizeID gets a reference to the given NullableInt32 and assigns it to the SizeID field.
func (o *QuarantineItems) SetSizeID(v int32) {
	o.SizeID.Set(&v)
}
// SetSizeIDNil sets the value for SizeID to be an explicit nil
func (o *QuarantineItems) SetSizeIDNil() {
	o.SizeID.Set(nil)
}

// UnsetSizeID ensures that no value is present for SizeID, not even an explicit nil
func (o *QuarantineItems) UnsetSizeID() {
	o.SizeID.Unset()
}

// GetTechSizeName returns the TechSizeName field value if set, zero value otherwise.
func (o *QuarantineItems) GetTechSizeName() string {
	if o == nil || IsNil(o.TechSizeName) {
		var ret string
		return ret
	}
	return *o.TechSizeName
}

// GetTechSizeNameOk returns a tuple with the TechSizeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuarantineItems) GetTechSizeNameOk() (*string, bool) {
	if o == nil || IsNil(o.TechSizeName) {
		return nil, false
	}
	return o.TechSizeName, true
}

// HasTechSizeName returns a boolean if a field has been set.
func (o *QuarantineItems) HasTechSizeName() bool {
	if o != nil && !IsNil(o.TechSizeName) {
		return true
	}

	return false
}

// SetTechSizeName gets a reference to the given string and assigns it to the TechSizeName field.
func (o *QuarantineItems) SetTechSizeName(v string) {
	o.TechSizeName = &v
}

// GetCurrencyIsoCode4217 returns the CurrencyIsoCode4217 field value if set, zero value otherwise.
func (o *QuarantineItems) GetCurrencyIsoCode4217() string {
	if o == nil || IsNil(o.CurrencyIsoCode4217) {
		var ret string
		return ret
	}
	return *o.CurrencyIsoCode4217
}

// GetCurrencyIsoCode4217Ok returns a tuple with the CurrencyIsoCode4217 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuarantineItems) GetCurrencyIsoCode4217Ok() (*string, bool) {
	if o == nil || IsNil(o.CurrencyIsoCode4217) {
		return nil, false
	}
	return o.CurrencyIsoCode4217, true
}

// HasCurrencyIsoCode4217 returns a boolean if a field has been set.
func (o *QuarantineItems) HasCurrencyIsoCode4217() bool {
	if o != nil && !IsNil(o.CurrencyIsoCode4217) {
		return true
	}

	return false
}

// SetCurrencyIsoCode4217 gets a reference to the given string and assigns it to the CurrencyIsoCode4217 field.
func (o *QuarantineItems) SetCurrencyIsoCode4217(v string) {
	o.CurrencyIsoCode4217 = &v
}

// GetNewPrice returns the NewPrice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QuarantineItems) GetNewPrice() float32 {
	if o == nil || IsNil(o.NewPrice.Get()) {
		var ret float32
		return ret
	}
	return *o.NewPrice.Get()
}

// GetNewPriceOk returns a tuple with the NewPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuarantineItems) GetNewPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NewPrice.Get(), o.NewPrice.IsSet()
}

// HasNewPrice returns a boolean if a field has been set.
func (o *QuarantineItems) HasNewPrice() bool {
	if o != nil && o.NewPrice.IsSet() {
		return true
	}

	return false
}

// SetNewPrice gets a reference to the given NullableFloat32 and assigns it to the NewPrice field.
func (o *QuarantineItems) SetNewPrice(v float32) {
	o.NewPrice.Set(&v)
}
// SetNewPriceNil sets the value for NewPrice to be an explicit nil
func (o *QuarantineItems) SetNewPriceNil() {
	o.NewPrice.Set(nil)
}

// UnsetNewPrice ensures that no value is present for NewPrice, not even an explicit nil
func (o *QuarantineItems) UnsetNewPrice() {
	o.NewPrice.Unset()
}

// GetOldPrice returns the OldPrice field value if set, zero value otherwise.
func (o *QuarantineItems) GetOldPrice() float32 {
	if o == nil || IsNil(o.OldPrice) {
		var ret float32
		return ret
	}
	return *o.OldPrice
}

// GetOldPriceOk returns a tuple with the OldPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuarantineItems) GetOldPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.OldPrice) {
		return nil, false
	}
	return o.OldPrice, true
}

// HasOldPrice returns a boolean if a field has been set.
func (o *QuarantineItems) HasOldPrice() bool {
	if o != nil && !IsNil(o.OldPrice) {
		return true
	}

	return false
}

// SetOldPrice gets a reference to the given float32 and assigns it to the OldPrice field.
func (o *QuarantineItems) SetOldPrice(v float32) {
	o.OldPrice = &v
}

// GetNewDiscount returns the NewDiscount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QuarantineItems) GetNewDiscount() int32 {
	if o == nil || IsNil(o.NewDiscount.Get()) {
		var ret int32
		return ret
	}
	return *o.NewDiscount.Get()
}

// GetNewDiscountOk returns a tuple with the NewDiscount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuarantineItems) GetNewDiscountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NewDiscount.Get(), o.NewDiscount.IsSet()
}

// HasNewDiscount returns a boolean if a field has been set.
func (o *QuarantineItems) HasNewDiscount() bool {
	if o != nil && o.NewDiscount.IsSet() {
		return true
	}

	return false
}

// SetNewDiscount gets a reference to the given NullableInt32 and assigns it to the NewDiscount field.
func (o *QuarantineItems) SetNewDiscount(v int32) {
	o.NewDiscount.Set(&v)
}
// SetNewDiscountNil sets the value for NewDiscount to be an explicit nil
func (o *QuarantineItems) SetNewDiscountNil() {
	o.NewDiscount.Set(nil)
}

// UnsetNewDiscount ensures that no value is present for NewDiscount, not even an explicit nil
func (o *QuarantineItems) UnsetNewDiscount() {
	o.NewDiscount.Unset()
}

// GetOldDiscount returns the OldDiscount field value if set, zero value otherwise.
func (o *QuarantineItems) GetOldDiscount() int32 {
	if o == nil || IsNil(o.OldDiscount) {
		var ret int32
		return ret
	}
	return *o.OldDiscount
}

// GetOldDiscountOk returns a tuple with the OldDiscount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuarantineItems) GetOldDiscountOk() (*int32, bool) {
	if o == nil || IsNil(o.OldDiscount) {
		return nil, false
	}
	return o.OldDiscount, true
}

// HasOldDiscount returns a boolean if a field has been set.
func (o *QuarantineItems) HasOldDiscount() bool {
	if o != nil && !IsNil(o.OldDiscount) {
		return true
	}

	return false
}

// SetOldDiscount gets a reference to the given int32 and assigns it to the OldDiscount field.
func (o *QuarantineItems) SetOldDiscount(v int32) {
	o.OldDiscount = &v
}

// GetPriceDiff returns the PriceDiff field value if set, zero value otherwise.
func (o *QuarantineItems) GetPriceDiff() float32 {
	if o == nil || IsNil(o.PriceDiff) {
		var ret float32
		return ret
	}
	return *o.PriceDiff
}

// GetPriceDiffOk returns a tuple with the PriceDiff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuarantineItems) GetPriceDiffOk() (*float32, bool) {
	if o == nil || IsNil(o.PriceDiff) {
		return nil, false
	}
	return o.PriceDiff, true
}

// HasPriceDiff returns a boolean if a field has been set.
func (o *QuarantineItems) HasPriceDiff() bool {
	if o != nil && !IsNil(o.PriceDiff) {
		return true
	}

	return false
}

// SetPriceDiff gets a reference to the given float32 and assigns it to the PriceDiff field.
func (o *QuarantineItems) SetPriceDiff(v float32) {
	o.PriceDiff = &v
}

func (o QuarantineItems) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuarantineItems) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NmID) {
		toSerialize["nmID"] = o.NmID
	}
	if o.SizeID.IsSet() {
		toSerialize["sizeID"] = o.SizeID.Get()
	}
	if !IsNil(o.TechSizeName) {
		toSerialize["techSizeName"] = o.TechSizeName
	}
	if !IsNil(o.CurrencyIsoCode4217) {
		toSerialize["currencyIsoCode4217"] = o.CurrencyIsoCode4217
	}
	if o.NewPrice.IsSet() {
		toSerialize["newPrice"] = o.NewPrice.Get()
	}
	if !IsNil(o.OldPrice) {
		toSerialize["oldPrice"] = o.OldPrice
	}
	if o.NewDiscount.IsSet() {
		toSerialize["newDiscount"] = o.NewDiscount.Get()
	}
	if !IsNil(o.OldDiscount) {
		toSerialize["oldDiscount"] = o.OldDiscount
	}
	if !IsNil(o.PriceDiff) {
		toSerialize["priceDiff"] = o.PriceDiff
	}
	return toSerialize, nil
}

type NullableQuarantineItems struct {
	value *QuarantineItems
	isSet bool
}

func (v NullableQuarantineItems) Get() *QuarantineItems {
	return v.value
}

func (v *NullableQuarantineItems) Set(val *QuarantineItems) {
	v.value = val
	v.isSet = true
}

func (v NullableQuarantineItems) IsSet() bool {
	return v.isSet
}

func (v *NullableQuarantineItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuarantineItems(val *QuarantineItems) *NullableQuarantineItems {
	return &NullableQuarantineItems{value: val, isSet: true}
}

func (v NullableQuarantineItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuarantineItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


