/*
Тарифы

<div class=\"description_important\">   Узнать больше о тарифах можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/material/fees-site-section\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Комиссий](/openapi/wb-tariffs#tag/Komissii)   2. [Тарифов на поставку](/openapi/wb-tariffs#tag/Tarify-na-postavku)   3. [Тарифов на остаток](/openapi/wb-tariffs#tag/Tarify-na-ostatok)   4. [Тарифов на возврат товаров продавцу](/openapi/wb-tariffs#tag/Stoimost-vozvrata-prodavcu)  </div> 

API version: tariffs
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tariffs

import (
	"encoding/json"
)

// checks if the ModelsTariffsPalletResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsTariffsPalletResponse{}

// ModelsTariffsPalletResponse struct for ModelsTariffsPalletResponse
type ModelsTariffsPalletResponse struct {
	Data *ModelsWarehousesPalletRates `json:"data,omitempty"`
}

// NewModelsTariffsPalletResponse instantiates a new ModelsTariffsPalletResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsTariffsPalletResponse() *ModelsTariffsPalletResponse {
	this := ModelsTariffsPalletResponse{}
	return &this
}

// NewModelsTariffsPalletResponseWithDefaults instantiates a new ModelsTariffsPalletResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsTariffsPalletResponseWithDefaults() *ModelsTariffsPalletResponse {
	this := ModelsTariffsPalletResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ModelsTariffsPalletResponse) GetData() ModelsWarehousesPalletRates {
	if o == nil || IsNil(o.Data) {
		var ret ModelsWarehousesPalletRates
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTariffsPalletResponse) GetDataOk() (*ModelsWarehousesPalletRates, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ModelsTariffsPalletResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ModelsWarehousesPalletRates and assigns it to the Data field.
func (o *ModelsTariffsPalletResponse) SetData(v ModelsWarehousesPalletRates) {
	o.Data = &v
}

func (o ModelsTariffsPalletResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsTariffsPalletResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableModelsTariffsPalletResponse struct {
	value *ModelsTariffsPalletResponse
	isSet bool
}

func (v NullableModelsTariffsPalletResponse) Get() *ModelsTariffsPalletResponse {
	return v.value
}

func (v *NullableModelsTariffsPalletResponse) Set(val *ModelsTariffsPalletResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsTariffsPalletResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsTariffsPalletResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsTariffsPalletResponse(val *ModelsTariffsPalletResponse) *NullableModelsTariffsPalletResponse {
	return &NullableModelsTariffsPalletResponse{value: val, isSet: true}
}

func (v NullableModelsTariffsPalletResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsTariffsPalletResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


