/*
 * Заказы Самовывоз
 *
 * <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [идентификаторами маркировки](/openapi/in-store-pickup#tag/inStorePickupLabelIdentifiers) заказов модели Самовывоз.<br><br>  Вы можете протестировать методы заказов Самовывоз в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-Samovyvoz) для эмуляции действий пользователя  </div> 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3ClickCollectOrdersNewGet401Response {
    /// Заголовок ошибки
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Детали ошибки
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// Внутренний код ошибки
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Уникальный ID запроса
    #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// ID внутреннего сервиса WB
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,
    /// HTTP статус-код
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<f64>,
    /// Расшифровка HTTP статус-кода
    #[serde(rename = "statusText", skip_serializing_if = "Option::is_none")]
    pub status_text: Option<String>,
    /// Дата и время запроса
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl ApiV3ClickCollectOrdersNewGet401Response {
    pub fn new() -> ApiV3ClickCollectOrdersNewGet401Response {
        ApiV3ClickCollectOrdersNewGet401Response {
            title: None,
            detail: None,
            code: None,
            request_id: None,
            origin: None,
            status: None,
            status_text: None,
            timestamp: None,
        }
    }
}

