/*
 * Заказы Самовывоз
 *
 * <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/in-store-pickup#tag/inStorePickupAssemblyOrders) и [идентификаторами маркировки](/openapi/in-store-pickup#tag/inStorePickupLabelIdentifiers) заказов модели Самовывоз.<br><br>  Вы можете протестировать методы заказов Самовывоз в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-Samovyvoz) для эмуляции действий пользователя  </div> 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiCheckIdentityRequest {
    /// Уникальный ID заказа покупателя
    #[serde(rename = "orderCode", skip_serializing_if = "Option::is_none")]
    pub order_code: Option<String>,
    /// Код подтверждения
    #[serde(rename = "passcode", skip_serializing_if = "Option::is_none")]
    pub passcode: Option<String>,
}

impl ApiCheckIdentityRequest {
    pub fn new() -> ApiCheckIdentityRequest {
        ApiCheckIdentityRequest {
            order_code: None,
            passcode: None,
        }
    }
}

