/* tslint:disable */
/* eslint-disable */
/**
 * DBS
 * <div class=\"description_important\">   Узнать больше о модели DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/orders-dbs#tag/dbsAssemblyOrders) и [идентификаторами маркировки](/openapi/orders-dbs#tag/dbsLabelIdentifiers) DBS (Delivery by Seller).<br><br>  Вы можете протестировать методы DBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-DBS) для эмуляции действий пользователя  </div> 
 *
 * The version of the OpenAPI document: dbs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiBatchErrorDeliverResponseMetaDetailsInner
 */
export interface ApiBatchErrorDeliverResponseMetaDetailsInner {
    /**
     * Идентификатор маркировки
     */
    key?: string;
    /**
     * Значение идентификатора маркировки
     */
    value?: string;
    /**
     * Статус проверки:
     * - `sgtin`
     *   - `sgtinInvalidFormat` — Неверный формат маркировки
     *   - `sgtinNotFound` — Маркировка не найдена в [Честном знаке](https://chestnyznak.ru)
     *   - `sgtinEmitted` —  Маркировка эмитирована
     *   - `sgtinApplied` — Не пройдена процедура Ввод в оборот
     *   - `sgtinWrittenOff` — Списан
     *   - `sgtinRetired` — Выбыл
     *   - `sgtinWithdrawn` — Выбыл
     *   - `sgtinDisaggregation` — Расформирован
     *   - `sgtinDisaggregated` — Расформирован
     *   - `sgtinAppliedNotPaid` — Не оплачен
     *   - `pending` — Маркировка на проверке
     * 
     */
    decision?: string;
}

/**
 * Check if a given object implements the ApiBatchErrorDeliverResponseMetaDetailsInner interface.
 */
export function instanceOfApiBatchErrorDeliverResponseMetaDetailsInner(value: object): value is ApiBatchErrorDeliverResponseMetaDetailsInner {
    return true;
}

export function ApiBatchErrorDeliverResponseMetaDetailsInnerFromJSON(json: any): ApiBatchErrorDeliverResponseMetaDetailsInner {
    return ApiBatchErrorDeliverResponseMetaDetailsInnerFromJSONTyped(json, false);
}

export function ApiBatchErrorDeliverResponseMetaDetailsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiBatchErrorDeliverResponseMetaDetailsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'decision': json['decision'] == null ? undefined : json['decision'],
    };
}

export function ApiBatchErrorDeliverResponseMetaDetailsInnerToJSON(json: any): ApiBatchErrorDeliverResponseMetaDetailsInner {
    return ApiBatchErrorDeliverResponseMetaDetailsInnerToJSONTyped(json, false);
}

export function ApiBatchErrorDeliverResponseMetaDetailsInnerToJSONTyped(value?: ApiBatchErrorDeliverResponseMetaDetailsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
        'decision': value['decision'],
    };
}

