/*
DBS

<div class=\"description_important\">   Узнать больше о модели DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/orders-dbs#tag/dbsAssemblyOrders) и [идентификаторами маркировки](/openapi/orders-dbs#tag/dbsLabelIdentifiers) DBS (Delivery by Seller).<br><br>  Вы можете протестировать методы DBS в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/Marketplejs-DBS) для эмуляции действий пользователя  </div> 

API version: dbs
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dbs

import (
	"encoding/json"
)

// checks if the ApiOrderStatusV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiOrderStatusV2{}

// ApiOrderStatusV2 struct for ApiOrderStatusV2
type ApiOrderStatusV2 struct {
	// Информация об ошибке
	Errors []ApiBatchErrorResponse `json:"errors,omitempty"`
	// ID сборочного задания
	OrderId *int32 `json:"orderId,omitempty"`
	// Статус сборочного задания, установленный продавцом
	SupplierStatus *string `json:"supplierStatus,omitempty"`
	// Статус сборочного задания в системе Wildberries
	WbStatus *string `json:"wbStatus,omitempty"`
}

// NewApiOrderStatusV2 instantiates a new ApiOrderStatusV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiOrderStatusV2() *ApiOrderStatusV2 {
	this := ApiOrderStatusV2{}
	return &this
}

// NewApiOrderStatusV2WithDefaults instantiates a new ApiOrderStatusV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiOrderStatusV2WithDefaults() *ApiOrderStatusV2 {
	this := ApiOrderStatusV2{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ApiOrderStatusV2) GetErrors() []ApiBatchErrorResponse {
	if o == nil || IsNil(o.Errors) {
		var ret []ApiBatchErrorResponse
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiOrderStatusV2) GetErrorsOk() ([]ApiBatchErrorResponse, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ApiOrderStatusV2) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ApiBatchErrorResponse and assigns it to the Errors field.
func (o *ApiOrderStatusV2) SetErrors(v []ApiBatchErrorResponse) {
	o.Errors = v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *ApiOrderStatusV2) GetOrderId() int32 {
	if o == nil || IsNil(o.OrderId) {
		var ret int32
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiOrderStatusV2) GetOrderIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *ApiOrderStatusV2) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given int32 and assigns it to the OrderId field.
func (o *ApiOrderStatusV2) SetOrderId(v int32) {
	o.OrderId = &v
}

// GetSupplierStatus returns the SupplierStatus field value if set, zero value otherwise.
func (o *ApiOrderStatusV2) GetSupplierStatus() string {
	if o == nil || IsNil(o.SupplierStatus) {
		var ret string
		return ret
	}
	return *o.SupplierStatus
}

// GetSupplierStatusOk returns a tuple with the SupplierStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiOrderStatusV2) GetSupplierStatusOk() (*string, bool) {
	if o == nil || IsNil(o.SupplierStatus) {
		return nil, false
	}
	return o.SupplierStatus, true
}

// HasSupplierStatus returns a boolean if a field has been set.
func (o *ApiOrderStatusV2) HasSupplierStatus() bool {
	if o != nil && !IsNil(o.SupplierStatus) {
		return true
	}

	return false
}

// SetSupplierStatus gets a reference to the given string and assigns it to the SupplierStatus field.
func (o *ApiOrderStatusV2) SetSupplierStatus(v string) {
	o.SupplierStatus = &v
}

// GetWbStatus returns the WbStatus field value if set, zero value otherwise.
func (o *ApiOrderStatusV2) GetWbStatus() string {
	if o == nil || IsNil(o.WbStatus) {
		var ret string
		return ret
	}
	return *o.WbStatus
}

// GetWbStatusOk returns a tuple with the WbStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiOrderStatusV2) GetWbStatusOk() (*string, bool) {
	if o == nil || IsNil(o.WbStatus) {
		return nil, false
	}
	return o.WbStatus, true
}

// HasWbStatus returns a boolean if a field has been set.
func (o *ApiOrderStatusV2) HasWbStatus() bool {
	if o != nil && !IsNil(o.WbStatus) {
		return true
	}

	return false
}

// SetWbStatus gets a reference to the given string and assigns it to the WbStatus field.
func (o *ApiOrderStatusV2) SetWbStatus(v string) {
	o.WbStatus = &v
}

func (o ApiOrderStatusV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiOrderStatusV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}
	if !IsNil(o.SupplierStatus) {
		toSerialize["supplierStatus"] = o.SupplierStatus
	}
	if !IsNil(o.WbStatus) {
		toSerialize["wbStatus"] = o.WbStatus
	}
	return toSerialize, nil
}

type NullableApiOrderStatusV2 struct {
	value *ApiOrderStatusV2
	isSet bool
}

func (v NullableApiOrderStatusV2) Get() *ApiOrderStatusV2 {
	return v.value
}

func (v *NullableApiOrderStatusV2) Set(val *ApiOrderStatusV2) {
	v.value = val
	v.isSet = true
}

func (v NullableApiOrderStatusV2) IsSet() bool {
	return v.isSet
}

func (v *NullableApiOrderStatusV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiOrderStatusV2(val *ApiOrderStatusV2) *NullableApiOrderStatusV2 {
	return &NullableApiOrderStatusV2{value: val, isSet: true}
}

func (v NullableApiOrderStatusV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiOrderStatusV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


