/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBW
 * <div class=\"api-block\">  С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/dbwLabelIdentifiers) сборочных заданий  </div>  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-036a-7721-98e8-bed5f1a4f72d/zakazy-dbw\">инструкции</a> по работе с <strong>заказами DBW</strong> </div> 
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';

/**
 * 
 * @export
 * @interface ApiV3DbwOrdersOrderIdMetaGet200Response
 */
export interface ApiV3DbwOrdersOrderIdMetaGet200Response {
    /**
     * 
     * @type {Meta}
     * @memberof ApiV3DbwOrdersOrderIdMetaGet200Response
     */
    meta?: Meta | null;
}

/**
 * Check if a given object implements the ApiV3DbwOrdersOrderIdMetaGet200Response interface.
 */
export function instanceOfApiV3DbwOrdersOrderIdMetaGet200Response(value: object): value is ApiV3DbwOrdersOrderIdMetaGet200Response {
    return true;
}

export function ApiV3DbwOrdersOrderIdMetaGet200ResponseFromJSON(json: any): ApiV3DbwOrdersOrderIdMetaGet200Response {
    return ApiV3DbwOrdersOrderIdMetaGet200ResponseFromJSONTyped(json, false);
}

export function ApiV3DbwOrdersOrderIdMetaGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3DbwOrdersOrderIdMetaGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] === undefined ? undefined : json['meta'] === null ? null : MetaFromJSON(json['meta']),
    };
}

export function ApiV3DbwOrdersOrderIdMetaGet200ResponseToJSON(json: any): ApiV3DbwOrdersOrderIdMetaGet200Response {
    return ApiV3DbwOrdersOrderIdMetaGet200ResponseToJSONTyped(json, false);
}

export function ApiV3DbwOrdersOrderIdMetaGet200ResponseToJSONTyped(value?: ApiV3DbwOrdersOrderIdMetaGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': MetaToJSON(value['meta']),
    };
}

