/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBW
 * <div class=\"api-block\">  С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/dbwAssemblyOrders), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/dbwLabelIdentifiers) сборочных заданий  </div>  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"/knowledge-base/articles/019d49a4-036a-7721-98e8-bed5f1a4f72d/zakazy-dbw\">инструкции</a> по работе с <strong>заказами DBW</strong> </div> 
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryDatesInfoRespOrdersInner
 */
export interface DeliveryDatesInfoRespOrdersInner {
    /**
     * Актуальное время доставки "с"
     */
    dTimeFrom?: string | null;
    /**
     * Актуальное время доставки "по"
     */
    dTimeTo?: string | null;
    /**
     * Прежнее время доставки "с". Доступно первые сутки после изменения
     */
    dTimeFromOld?: string | null;
    /**
     * Прежнее время доставки "по". Доступно первые сутки после изменения
     */
    dTimeToOld?: string | null;
    /**
     * Прежняя дата доставки. Доступна первые сутки после изменения
     */
    dDateOld?: string | null;
    /**
     * Актуальная дата доставки
     */
    dDate?: string;
    /**
     * ID сборочного задания
     */
    id?: number;
}

/**
 * Check if a given object implements the DeliveryDatesInfoRespOrdersInner interface.
 */
export function instanceOfDeliveryDatesInfoRespOrdersInner(value: object): value is DeliveryDatesInfoRespOrdersInner {
    return true;
}

export function DeliveryDatesInfoRespOrdersInnerFromJSON(json: any): DeliveryDatesInfoRespOrdersInner {
    return DeliveryDatesInfoRespOrdersInnerFromJSONTyped(json, false);
}

export function DeliveryDatesInfoRespOrdersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryDatesInfoRespOrdersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'dTimeFrom': json['dTimeFrom'] === undefined ? undefined : json['dTimeFrom'] === null ? null : json['dTimeFrom'],
        'dTimeTo': json['dTimeTo'] === undefined ? undefined : json['dTimeTo'] === null ? null : json['dTimeTo'],
        'dTimeFromOld': json['dTimeFromOld'] === undefined ? undefined : json['dTimeFromOld'] === null ? null : json['dTimeFromOld'],
        'dTimeToOld': json['dTimeToOld'] === undefined ? undefined : json['dTimeToOld'] === null ? null : json['dTimeToOld'],
        'dDateOld': json['dDateOld'] === undefined ? undefined : json['dDateOld'] === null ? null : json['dDateOld'],
        'dDate': json['dDate'] == null ? undefined : json['dDate'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function DeliveryDatesInfoRespOrdersInnerToJSON(json: any): DeliveryDatesInfoRespOrdersInner {
    return DeliveryDatesInfoRespOrdersInnerToJSONTyped(json, false);
}

export function DeliveryDatesInfoRespOrdersInnerToJSONTyped(value?: DeliveryDatesInfoRespOrdersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dTimeFrom': value['dTimeFrom'],
        'dTimeTo': value['dTimeTo'],
        'dTimeFromOld': value['dTimeFromOld'],
        'dTimeToOld': value['dTimeToOld'],
        'dDateOld': value['dDateOld'],
        'dDate': value['dDate'],
        'id': value['id'],
    };
}

